// AUTO-GENERATED parity spike for field::DrawPos @ $00:C276.
// Generated by translator/generate_spike.py from port/field/DrawPos.c.
// DO NOT EDIT BY HAND — regenerate via:
//   python translator/generate_spike.py port/field/DrawPos.c

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdint.h>
#include <stdbool.h>

#include "snes.h"
#include "cpu.h"

#define TARGET_ADDR_24 0x00C276u

// Forward declarations for helpers defined later in this TU but used by the
// inlined LLM translation below.
static void run_emulated_func(Snes *snes, uint32_t pc24);
static inline uint16_t read16(const uint8_t *ram, int addr);
static inline void write16(uint8_t *ram, int addr, uint16_t v);

// ---------------------------------------------------------------------------
// Auto-emitted *_emu delegation helpers (one per stub referenced by the
// translation but not defined in port/field/DrawPos.c).
// ---------------------------------------------------------------------------

// (no auto-emitted helpers)

// ---------------------------------------------------------------------------
// LLM-translated C function (verbatim copy from port/field/DrawPos.c)
// ---------------------------------------------------------------------------

#include "snes/snes.h"

// Logic: Draws coordinates (X, Y) and MapID to the screen using VRAM writes.
// It breaks each value into a high nibble and a low nibble.
// If a nibble is < 10, it is ORed with 0x80 (font offset for digits).
// If a nibble is >= 10, it is offset by 0x38 (font offset for hex/chars).
// Each character is written to VRAM via the $2115 (address low), $2116 (address high),
// and $2118 (data) registers.
static void DrawPos_c(Snes *snes) {
    uint8_t *ram = snes->ram;
    
    // Constants defined by the assembly labels (Release/Standard build)
    const int ADDR_POS_X = 0x86;
    const int ADDR_POS_Y = 0x87;
    const int ADDR_MAP_ID = 0x88;

    // Helper to simulate the repetitive VRAM write sequence
    // 1. Set character data to $2118
    // 2. Set trigger/command to $2119
    auto write_vram_char = [&](uint8_t value) {
        if (value < 10) {
            snes->ram[0x2118] = value | 0x80; // ora #$80
        } else {
            snes->ram[0x2118] = (uint8_t)(value + 0x38); // adc #$38
        }
        snes->ram[0x2119] = 0x20;
    };

    // --- Draw X Position ---
    snes->ram[0x2115] = 0x80;
    snes->ram[0x2116] = 0x82; // low byte of $2882 (actually write16 is needed for 2116)
    snes->ram[0x2117] = 0x28; // stx $2116 (X is #$2882)
    
    uint8_t posX = ram[ADDR_POS_X];
    write_vram_char((posX >> 4) & 0x0F); // lsr4 / cmp / bcc...
    write_vram_char(posX & 0x0F);        // and #$0f / cmp / bcc...
    
    // The asm has stz $2118 / stz $2119 here, effectively clearing the last write
    snes->ram[0x2118] = 0;
    snes->ram[0x2119] = 0;

    // --- Draw Y Position ---
    uint8_t posY = ram[ADDR_POS_Y];
    write_vram_char((posY >> 4) & 0x0F);
    write_vram_char(posY & 0x0F);

    // --- Draw Map ID ---
    snes->ram[0x2116] = 0xC2; // low byte of $28C2
    snes->ram[0x2117] = 0x28; // high byte
    
    uint8_t mapId = ram[ADDR_MAP_ID];
    write_vram_char((mapId >> 4) & 0x0F);
    write_vram_char(mapId & 0x0F);
}


// ---------------------------------------------------------------------------
// Common helpers (same shape as the manual M2/M3/M4 spikes)
// ---------------------------------------------------------------------------

static uint8_t *read_file(const char *path, size_t *out_len) {
    FILE *f = fopen(path, "rb");
    if (!f) { perror(path); return NULL; }
    fseek(f, 0, SEEK_END); long sz = ftell(f); fseek(f, 0, SEEK_SET);
    uint8_t *buf = malloc(sz);
    if (fread(buf, 1, sz, f) != (size_t)sz) { free(buf); fclose(f); return NULL; }
    fclose(f); *out_len = sz; return buf;
}

static inline uint32_t stack_addr(const Cpu *cpu) {
    return cpu->e ? (0x0100u | (cpu->sp & 0xFFu)) : cpu->sp;
}

static void run_emulated_func(Snes *snes, uint32_t pc24) {
    Cpu *cpu = snes->cpu;
    uint16_t sp_save = cpu->sp;
    snes->ram[stack_addr(cpu)] = 0x12; cpu->sp--;
    snes->ram[stack_addr(cpu)] = 0x34; cpu->sp--;
    cpu->k = (uint8_t)(pc24 >> 16);
    cpu->pc = (uint16_t)(pc24 & 0xFFFF);
    long max_ops = 200000;
    while (cpu->sp != sp_save && max_ops-- > 0) {
        cpu_runOpcode(cpu);
        if (cpu->waiting || cpu->stopped) break;
    }
}

typedef struct {
    uint8_t ram[0x20000];
    uint16_t a, x, y, sp, pc, dp;
    uint8_t k, db;
    bool c, z, v, n, i, d, xf, mf, e;
    bool waiting, stopped, irqWanted, nmiWanted;
} Snap;

static void snap_take(Snap *s, Snes *snes) {
    memcpy(s->ram, snes->ram, sizeof(s->ram));
    Cpu *c = snes->cpu;
    s->a=c->a; s->x=c->x; s->y=c->y; s->sp=c->sp; s->pc=c->pc; s->dp=c->dp;
    s->k=c->k; s->db=c->db;
    s->c=c->c; s->z=c->z; s->v=c->v; s->n=c->n;
    s->i=c->i; s->d=c->d; s->xf=c->xf; s->mf=c->mf; s->e=c->e;
    s->waiting=c->waiting; s->stopped=c->stopped;
    s->irqWanted=c->irqWanted; s->nmiWanted=c->nmiWanted;
}
static void snap_restore(const Snap *s, Snes *snes) {
    memcpy(snes->ram, s->ram, sizeof(s->ram));
    Cpu *c = snes->cpu;
    c->a=s->a; c->x=s->x; c->y=s->y; c->sp=s->sp; c->pc=s->pc; c->dp=s->dp;
    c->k=s->k; c->db=s->db;
    c->c=s->c; c->z=s->z; c->v=s->v; c->n=s->n;
    c->i=s->i; c->d=s->d; c->xf=s->xf; c->mf=s->mf; c->e=s->e;
    c->waiting=s->waiting; c->stopped=s->stopped;
    c->irqWanted=s->irqWanted; c->nmiWanted=s->nmiWanted;
}

static inline uint16_t read16(const uint8_t *ram, int addr) {
    return (uint16_t)(ram[addr] | (ram[addr + 1] << 8));
}
static inline void write16(uint8_t *ram, int addr, uint16_t v) {
    ram[addr] = v & 0xFF; ram[addr + 1] = (v >> 8) & 0xFF;
}

// ---------------------------------------------------------------------------
// asm wrapper from the contract
// ---------------------------------------------------------------------------

static void run_asm(Snes *snes) {
    Cpu *c = snes->cpu;
    c->dp = 0;
    c->db = 0x7E;
    c->mf = true;
    c->xf = false;
    c->a = 0; c->x = 0; c->y = 0;
    // no register inputs
    // no entry flags
    run_emulated_func(snes, TARGET_ADDR_24);
}

// ---------------------------------------------------------------------------
// Host PRNG
// ---------------------------------------------------------------------------

static uint32_t host_rng_state = 0xC0FFEEu;
static uint32_t host_rng(void) {
    uint32_t x = host_rng_state;
    x ^= x << 13; x ^= x >> 17; x ^= x << 5;
    host_rng_state = x; return x;
}

// ---------------------------------------------------------------------------
// Trial driver
// ---------------------------------------------------------------------------

int main(int argc, char **argv) {
    if (argc < 2) {
        fprintf(stderr, "usage: %s <rom.sfc> [n_trials]\n", argv[0]);
        return 1;
    }
    int n_trials = (argc >= 3) ? atoi(argv[2]) : 1000;

    size_t rom_len = 0;
    uint8_t *rom = read_file(argv[1], &rom_len);
    if (!rom) return 2;

    Snes *snes = snes_init();
    if (!snes_loadRom(snes, rom, rom_len)) { fprintf(stderr, "loadRom fail\n"); return 3; }
    snes_reset(snes, true);
    for (int i = 0; i < 60; i++) snes_runFrame(snes);
    snes->cpu->i = true; snes->cpu->nmiWanted = false; snes->cpu->irqWanted = false;

    Snap baseline;
    snap_take(&baseline, snes);

    fprintf(stderr, "DrawPos asm vs C : %d trials\n", n_trials);

    int fails = 0;
    for (int trial = 0; trial < n_trials; trial++) {
        snap_restore(&baseline, snes);

        // Randomise inputs.
        snes->ram[0x0086] = (uint8_t)host_rng();
        snes->ram[0x0087] = (uint8_t)host_rng();
        snes->ram[0x0088] = (uint8_t)host_rng();


        // Pre-call snapshot for replaying C with the exact same state.
        Snap pre;
        snap_take(&pre, snes);

        // Run ASM
        run_asm(snes);
        uint8_t out_asm = snes->ram[0x2118];

        // Restore and run C
        snap_restore(&pre, snes);
        DrawPos_c(snes);
        uint8_t out_c = snes->ram[0x2118];

        bool ok = (out_asm == out_c);
        if (!ok) {
            printf("trial %4d : asm=%u c=%u  FAIL\n", trial, out_asm, out_c);
            fails++;
        }
    }

    printf("\n=== summary === trials: %d, fails: %d\n", n_trials, fails);
    free(rom);
    return fails == 0 ? 0 : 1;
}
