// AUTO-GENERATED parity spike for field::_15b866 @ $00:B866.
// Generated by translator/generate_spike.py from port/field/_15b866.c.
// DO NOT EDIT BY HAND — regenerate via:
//   python translator/generate_spike.py port/field/_15b866.c

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdint.h>
#include <stdbool.h>

#include "snes.h"
#include "cpu.h"

#define TARGET_ADDR_24 0x00B866u

// Forward declarations for helpers defined later in this TU but used by the
// inlined LLM translation below.
static void run_emulated_func(Snes *snes, uint32_t pc24);
static inline uint16_t read16(const uint8_t *ram, int addr);
static inline void write16(uint8_t *ram, int addr, uint16_t v);

// ---------------------------------------------------------------------------
// Auto-emitted *_emu delegation helpers (one per stub referenced by the
// translation but not defined in port/field/_15b866.c).
// ---------------------------------------------------------------------------

// (no auto-emitted helpers)

// ---------------------------------------------------------------------------
// LLM-translated C function (verbatim copy from port/field/_15b866.c)
// ---------------------------------------------------------------------------

#include "snes/snes.h"

// Logic: 
// This routine calculates a value based on input A and the game state (animation frame, 
// and flags at $c8, $a1). It then writes a series of values to WRAM $04C0-$04C7, 
// using a table at f:_15b8c9 indexed by X.
//
// Entry mode: A 8-bit (mf=1), X 16-bit (xf=0), DB=$7E, DP=0
// Note: DP=0 is used as the routine accesses $06, $7a, $a1, etc. via direct page.
static void _15b866_c(Snes *snes) {
    uint8_t *ram = snes->ram;
    uint8_t a = snes->cpu->a;
    uint16_t x = snes->cpu->x;

    // cmp #$10 / bcc @b86c
    if (a >= 0x10) {
        a = 0x10; // lda #$10
    }

    a &= 0xFC;    // and #$fc
    uint8_t x_idx = a; // tax (A is 8-bit, X becomes the value)
    
    // Note: the asm does 'tax' then 'cmp #$10'. 
    // Since 'and #$fc' was performed, and we clamped a to 0x10, 
    // 'cmp #$10' tests if (a & 0xFC) == 0x10.
    if ((a & 0xFC) != 0x10) {
        // lda $7a / and #$01 / bne @b8c8
        if ((ram[0x7A] & 0x01) != 0) {
            return; // bne @b8c8
        }
    }

    // @b879: lda $c8 / bne @b8c8
    if (ram[0xC8] != 0) {
        return; // bne @b8c8
    }

    // lda $a1 / and #$08 / bne @b889
    if ((ram[0xA1] & 0x08) != 0) {
        ram[0x06] = 0xFE; // lda #$fe / jmp @b890
    } else if ((ram[0xA1] & 0x04) != 0) {
        ram[0x06] = 0x00; // lda #$00 / @b88e
    } else {
        // Fallthrough to @b88e (implicitly if not 0x08 and not 0x04)
        // Wait, the asm logic is:
        // if (a1 & 0x08) -> 0xFE
        // else if (a1 & 0x04) -> 0x00
        // else -> wait, the asm has a jump @b889 if 0x08 is set.
        // If 0x08 is NOT set, it checks 0x04.
        // If 0x04 is NOT set, it falls through to @b889 (which is lda #$fe).
        // Correction:
        // lda $a1 / and #$08 / bne @b889  => if set, go to 0xFE
        // lda $a1 / and #$04 / bne @b88e  => if set, go to 0x00
        // fallthrough to @b889 => 0xFE
        ram[0x06] = 0xFE; 
        // But if (a1 & 0x04) was true, it would have jumped to @b88e.
        // Let's re-trace:
        // if (a1 & 0x08) { a = 0xFE; goto 890; }
        // if (a1 & 0x04) { a = 0x00; goto 890; }
        // { a = 0xFE; goto 890; }
        // This means 0x00 is only written if (a1 & 0x04) is true AND (a1 & 0x08) is false.
    }

    // Re-evaluating the a1 logic based on the asm:
    uint8_t val_06;
    if ((ram[0xA1] & 0x08) != 0) {
        val_06 = 0xFE;
    } else if ((ram[0xA1] & 0x04) != 0) {
        val_06 = 0x00;
    } else {
        val_06 = 0xFE;
    }
    ram[0x06] = val_06;

    // sta $04c0 ... etc
    ram[0x04C0] = 0x70;
    ram[0x04C1] = (uint8_t)(0x78 + ram[0x06]); // adc $06
    
    // Table lookup: f:_15b8c9 is an external array (ROM)
    // Since we are in C and the prompt mentions f:_15b8c9, 
    // we treat it as a pointer to the ROM region.
    extern uint8_t _15b8c9_table[]; 
    ram[0x04C2] = _15b8c9_table[x_idx];
    ram[0x04C3] = _15b8c9_table[x_idx + 1];
    
    ram[0x04C4] = 0x78;
    ram[0x04C5] = (uint8_t)(0x78 + ram[0x06]); // adc $06
    ram[0x04C6] = _15b8c9_table[x_idx + 2];
    ram[0x04C7] = _15b8c9_table[x_idx + 3];
}


// ---------------------------------------------------------------------------
// Common helpers (same shape as the manual M2/M3/M4 spikes)
// ---------------------------------------------------------------------------

static uint8_t *read_file(const char *path, size_t *out_len) {
    FILE *f = fopen(path, "rb");
    if (!f) { perror(path); return NULL; }
    fseek(f, 0, SEEK_END); long sz = ftell(f); fseek(f, 0, SEEK_SET);
    uint8_t *buf = malloc(sz);
    if (fread(buf, 1, sz, f) != (size_t)sz) { free(buf); fclose(f); return NULL; }
    fclose(f); *out_len = sz; return buf;
}

static inline uint32_t stack_addr(const Cpu *cpu) {
    return cpu->e ? (0x0100u | (cpu->sp & 0xFFu)) : cpu->sp;
}

static void run_emulated_func(Snes *snes, uint32_t pc24) {
    Cpu *cpu = snes->cpu;
    uint16_t sp_save = cpu->sp;
    snes->ram[stack_addr(cpu)] = 0x12; cpu->sp--;
    snes->ram[stack_addr(cpu)] = 0x34; cpu->sp--;
    cpu->k = (uint8_t)(pc24 >> 16);
    cpu->pc = (uint16_t)(pc24 & 0xFFFF);
    long max_ops = 200000;
    while (cpu->sp != sp_save && max_ops-- > 0) {
        cpu_runOpcode(cpu);
        if (cpu->waiting || cpu->stopped) break;
    }
}

typedef struct {
    uint8_t ram[0x20000];
    uint16_t a, x, y, sp, pc, dp;
    uint8_t k, db;
    bool c, z, v, n, i, d, xf, mf, e;
    bool waiting, stopped, irqWanted, nmiWanted;
} Snap;

static void snap_take(Snap *s, Snes *snes) {
    memcpy(s->ram, snes->ram, sizeof(s->ram));
    Cpu *c = snes->cpu;
    s->a=c->a; s->x=c->x; s->y=c->y; s->sp=c->sp; s->pc=c->pc; s->dp=c->dp;
    s->k=c->k; s->db=c->db;
    s->c=c->c; s->z=c->z; s->v=c->v; s->n=c->n;
    s->i=c->i; s->d=c->d; s->xf=c->xf; s->mf=c->mf; s->e=c->e;
    s->waiting=c->waiting; s->stopped=c->stopped;
    s->irqWanted=c->irqWanted; s->nmiWanted=c->nmiWanted;
}
static void snap_restore(const Snap *s, Snes *snes) {
    memcpy(snes->ram, s->ram, sizeof(s->ram));
    Cpu *c = snes->cpu;
    c->a=s->a; c->x=s->x; c->y=s->y; c->sp=s->sp; c->pc=s->pc; c->dp=s->dp;
    c->k=s->k; c->db=s->db;
    c->c=s->c; c->z=s->z; c->v=s->v; c->n=s->n;
    c->i=s->i; c->d=s->d; c->xf=s->xf; c->mf=s->mf; c->e=s->e;
    c->waiting=s->waiting; c->stopped=s->stopped;
    c->irqWanted=s->irqWanted; c->nmiWanted=s->nmiWanted;
}

static inline uint16_t read16(const uint8_t *ram, int addr) {
    return (uint16_t)(ram[addr] | (ram[addr + 1] << 8));
}
static inline void write16(uint8_t *ram, int addr, uint16_t v) {
    ram[addr] = v & 0xFF; ram[addr + 1] = (v >> 8) & 0xFF;
}

// ---------------------------------------------------------------------------
// asm wrapper from the contract
// ---------------------------------------------------------------------------

static void run_asm(Snes *snes, uint8_t arg_a, uint16_t arg_x) {
    Cpu *c = snes->cpu;
    c->dp = 0;
    c->db = 0x7E;
    c->mf = true;
    c->xf = false;
    c->a = 0; c->x = 0; c->y = 0;
    c->a = arg_a;
    c->x = arg_x;
    c->z = (arg_a == 0);
    c->n = ((arg_a & 0x80) != 0);
    run_emulated_func(snes, TARGET_ADDR_24);
}

// ---------------------------------------------------------------------------
// Host PRNG
// ---------------------------------------------------------------------------

static uint32_t host_rng_state = 0xC0FFEEu;
static uint32_t host_rng(void) {
    uint32_t x = host_rng_state;
    x ^= x << 13; x ^= x >> 17; x ^= x << 5;
    host_rng_state = x; return x;
}

// ---------------------------------------------------------------------------
// Trial driver
// ---------------------------------------------------------------------------

int main(int argc, char **argv) {
    if (argc < 2) {
        fprintf(stderr, "usage: %s <rom.sfc> [n_trials]\n", argv[0]);
        return 1;
    }
    int n_trials = (argc >= 3) ? atoi(argv[2]) : 1000;

    size_t rom_len = 0;
    uint8_t *rom = read_file(argv[1], &rom_len);
    if (!rom) return 2;

    Snes *snes = snes_init();
    if (!snes_loadRom(snes, rom, rom_len)) { fprintf(stderr, "loadRom fail\n"); return 3; }
    snes_reset(snes, true);
    for (int i = 0; i < 60; i++) snes_runFrame(snes);
    snes->cpu->i = true; snes->cpu->nmiWanted = false; snes->cpu->irqWanted = false;

    Snap baseline;
    snap_take(&baseline, snes);

    fprintf(stderr, "_15b866 asm vs C : %d trials\n", n_trials);

    int fails = 0;
    for (int trial = 0; trial < n_trials; trial++) {
        snap_restore(&baseline, snes);

        // Randomise inputs.
        snes->ram[0x0006] = (uint8_t)host_rng();
        snes->ram[0x007A] = (uint8_t)host_rng();
        snes->ram[0x00A1] = (uint8_t)host_rng();
        snes->ram[0x00C8] = (uint8_t)host_rng();
        uint8_t arg_a = (uint8_t)host_rng();
        uint16_t arg_x = (uint16_t)host_rng();

        // Pre-call snapshot for replaying C with the exact same state.
        Snap pre;
        snap_take(&pre, snes);

        // Run ASM
        run_asm(snes, arg_a, arg_x);
        uint8_t out_asm = snes->ram[0x04C0];

        // Restore and run C
        snap_restore(&pre, snes);
        _15b866_c(snes, arg_a, arg_x);
        uint8_t out_c = snes->ram[0x04C0];

        bool ok = (out_asm == out_c);
        if (!ok) {
            printf("trial %4d : asm=%u c=%u  FAIL\n", trial, out_asm, out_c);
            fails++;
        }
    }

    printf("\n=== summary === trials: %d, fails: %d\n", n_trials, fails);
    free(rom);
    return fails == 0 ? 0 : 1;
}
