// AUTO-GENERATED parity spike for field::_00bfe3 @ $00:BFE3.
// Generated by translator/generate_spike.py from port/field/_00bfe3.c.
// DO NOT EDIT BY HAND — regenerate via:
//   python translator/generate_spike.py port/field/_00bfe3.c

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdint.h>
#include <stdbool.h>

#include "snes.h"
#include "cpu.h"

#define TARGET_ADDR_24 0x00BFE3u

// Forward declarations for helpers defined later in this TU but used by the
// inlined LLM translation below.
static void run_emulated_func(Snes *snes, uint32_t pc24);
static inline uint16_t read16(const uint8_t *ram, int addr);
static inline void write16(uint8_t *ram, int addr, uint16_t v);

// ---------------------------------------------------------------------------
// Auto-emitted *_emu delegation helpers (one per stub referenced by the
// translation but not defined in port/field/_00bfe3.c).
// ---------------------------------------------------------------------------

// (no auto-emitted helpers)

// ---------------------------------------------------------------------------
// LLM-translated C function (verbatim copy from port/field/_00bfe3.c)
// ---------------------------------------------------------------------------

#include "snes/snes.h"

// field::_00bfe3 ($BF:E3)
// Reads two signed bytes from $0C and $0E. If either is negative, returns 0.
// Otherwise, uses them as a 16-bit index (low=$0C, high=$0E) into a table at
// $7F:5C71, shifts the fetched byte left by 1 (16-bit), then uses the low
// byte of the shifted result as an index into a table at $7E:0EDB, ANDs the
// fetched byte with 0x83, and returns that value.
//
// Entry mode: A 8-bit (mf=1), X/Y 16-bit (xf=0), DP=0, DB=$7E.
// The routine preserves X (phx/plx) — we leave snes->cpu->x untouched.
static uint8_t _00bfe3(Snes *snes) {
    uint8_t *ram = snes->ram;

    uint8_t val0c = ram[0x0C];
    if (val0c & 0x80) {          // bmi @c008 — negative → return 0
        return 0;
    }
    uint8_t val0e = ram[0x0E];
    if (val0e & 0x80) {          // bmi @c008
        return 0;
    }

    // Both non-negative: store to $3D/$3E (temporary workspace)
    ram[0x3D] = val0c;
    ram[0x3E] = val0e;

    // ldx $3D (16-bit) → index = (val0e << 8) | val0c
    uint16_t index1 = ((uint16_t)val0e << 8) | val0c;

    // lda $7F5C71,x — bank $7F is at ram[0x10000 + addr]
    uint8_t table_byte = ram[0x15C71 + index1];   // 0x7F5C71

    ram[0x3D] = table_byte;
    ram[0x3E] = 0;               // stz $3E

    // asl $3D / rol $3E — 16-bit shift left of (high=$3E, low=$3D)
    uint8_t low  = ram[0x3D];
    uint8_t high = ram[0x3E];    // 0
    bool carry = (low & 0x80) != 0;
    low  = (uint8_t)(low << 1);
    high = (uint8_t)((high << 1) | (carry ? 1 : 0));
    ram[0x3D] = low;
    ram[0x3E] = high;

    // ldx $3D (16-bit) → index2 = (high << 8) | low
    uint16_t index2 = ((uint16_t)high << 8) | low;

    // lda $0EDB,x (DB=$7E) → ram[0x0EDB + index2]
    uint8_t result = ram[0x0EDB + index2];
    result &= 0x83;              // and #$83
    return result;               // jmp @c00a → plx / rts
}


// ---------------------------------------------------------------------------
// Common helpers (same shape as the manual M2/M3/M4 spikes)
// ---------------------------------------------------------------------------

static uint8_t *read_file(const char *path, size_t *out_len) {
    FILE *f = fopen(path, "rb");
    if (!f) { perror(path); return NULL; }
    fseek(f, 0, SEEK_END); long sz = ftell(f); fseek(f, 0, SEEK_SET);
    uint8_t *buf = malloc(sz);
    if (fread(buf, 1, sz, f) != (size_t)sz) { free(buf); fclose(f); return NULL; }
    fclose(f); *out_len = sz; return buf;
}

static inline uint32_t stack_addr(const Cpu *cpu) {
    return cpu->e ? (0x0100u | (cpu->sp & 0xFFu)) : cpu->sp;
}

static void run_emulated_func(Snes *snes, uint32_t pc24) {
    Cpu *cpu = snes->cpu;
    uint16_t sp_save = cpu->sp;
    snes->ram[stack_addr(cpu)] = 0x12; cpu->sp--;
    snes->ram[stack_addr(cpu)] = 0x34; cpu->sp--;
    cpu->k = (uint8_t)(pc24 >> 16);
    cpu->pc = (uint16_t)(pc24 & 0xFFFF);
    long max_ops = 200000;
    while (cpu->sp != sp_save && max_ops-- > 0) {
        cpu_runOpcode(cpu);
        if (cpu->waiting || cpu->stopped) break;
    }
}

typedef struct {
    uint8_t ram[0x20000];
    uint16_t a, x, y, sp, pc, dp;
    uint8_t k, db;
    bool c, z, v, n, i, d, xf, mf, e;
    bool waiting, stopped, irqWanted, nmiWanted;
} Snap;

static void snap_take(Snap *s, Snes *snes) {
    memcpy(s->ram, snes->ram, sizeof(s->ram));
    Cpu *c = snes->cpu;
    s->a=c->a; s->x=c->x; s->y=c->y; s->sp=c->sp; s->pc=c->pc; s->dp=c->dp;
    s->k=c->k; s->db=c->db;
    s->c=c->c; s->z=c->z; s->v=c->v; s->n=c->n;
    s->i=c->i; s->d=c->d; s->xf=c->xf; s->mf=c->mf; s->e=c->e;
    s->waiting=c->waiting; s->stopped=c->stopped;
    s->irqWanted=c->irqWanted; s->nmiWanted=c->nmiWanted;
}
static void snap_restore(const Snap *s, Snes *snes) {
    memcpy(snes->ram, s->ram, sizeof(s->ram));
    Cpu *c = snes->cpu;
    c->a=s->a; c->x=s->x; c->y=s->y; c->sp=s->sp; c->pc=s->pc; c->dp=s->dp;
    c->k=s->k; c->db=s->db;
    c->c=s->c; c->z=s->z; c->v=s->v; c->n=s->n;
    c->i=s->i; c->d=s->d; c->xf=s->xf; c->mf=s->mf; c->e=s->e;
    c->waiting=s->waiting; c->stopped=s->stopped;
    c->irqWanted=s->irqWanted; c->nmiWanted=s->nmiWanted;
}

static inline uint16_t read16(const uint8_t *ram, int addr) {
    return (uint16_t)(ram[addr] | (ram[addr + 1] << 8));
}
static inline void write16(uint8_t *ram, int addr, uint16_t v) {
    ram[addr] = v & 0xFF; ram[addr + 1] = (v >> 8) & 0xFF;
}

// ---------------------------------------------------------------------------
// asm wrapper from the contract
// ---------------------------------------------------------------------------

static void run_asm(Snes *snes) {
    Cpu *c = snes->cpu;
    c->dp = 0;
    c->db = 0x7E;
    c->mf = true;
    c->xf = false;
    c->a = 0; c->x = 0; c->y = 0;
    // no register inputs
    // no entry flags
    run_emulated_func(snes, TARGET_ADDR_24);
}

// ---------------------------------------------------------------------------
// Host PRNG
// ---------------------------------------------------------------------------

static uint32_t host_rng_state = 0xC0FFEEu;
static uint32_t host_rng(void) {
    uint32_t x = host_rng_state;
    x ^= x << 13; x ^= x >> 17; x ^= x << 5;
    host_rng_state = x; return x;
}

// ---------------------------------------------------------------------------
// Trial driver
// ---------------------------------------------------------------------------

int main(int argc, char **argv) {
    if (argc < 2) {
        fprintf(stderr, "usage: %s <rom.sfc> [n_trials]\n", argv[0]);
        return 1;
    }
    int n_trials = (argc >= 3) ? atoi(argv[2]) : 1000;

    size_t rom_len = 0;
    uint8_t *rom = read_file(argv[1], &rom_len);
    if (!rom) return 2;

    Snes *snes = snes_init();
    if (!snes_loadRom(snes, rom, rom_len)) { fprintf(stderr, "loadRom fail\n"); return 3; }
    snes_reset(snes, true);
    for (int i = 0; i < 60; i++) snes_runFrame(snes);
    snes->cpu->i = true; snes->cpu->nmiWanted = false; snes->cpu->irqWanted = false;

    Snap baseline;
    snap_take(&baseline, snes);

    fprintf(stderr, "_00bfe3 asm vs C : %d trials\n", n_trials);

    int fails = 0;
    for (int trial = 0; trial < n_trials; trial++) {
        snap_restore(&baseline, snes);

        // Randomise inputs.
        snes->ram[0x000C] = (uint8_t)host_rng();
        snes->ram[0x000E] = (uint8_t)host_rng();


        // Pre-call snapshot for replaying C with the exact same state.
        Snap pre;
        snap_take(&pre, snes);

        // Run ASM
        run_asm(snes);
        uint16_t out_asm = 0; (void)snes;

        // Restore and run C
        snap_restore(&pre, snes);
        _00bfe3_c(snes);
        uint16_t out_c = 0;

        bool ok = (out_asm == out_c);
        if (!ok) {
            printf("trial %4d : asm=%u c=%u  FAIL\n", trial, out_asm, out_c);
            fails++;
        }
    }

    printf("\n=== summary === trials: %d, fails: %d\n", n_trials, fails);
    free(rom);
    return fails == 0 ? 0 : 1;
}
