// AUTO-GENERATED parity spike for battle::CheckMonsterFlash @ $03:D354.
// Generated by translator/generate_spike.py from port/battle/CheckMonsterFlash.c.
// DO NOT EDIT BY HAND — regenerate via:
//   python translator/generate_spike.py port/battle/CheckMonsterFlash.c

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdint.h>
#include <stdbool.h>

#include "snes.h"
#include "cpu.h"

#define TARGET_ADDR_24 0x03D354u

// Forward declarations for helpers defined later in this TU but used by the
// inlined LLM translation below.
static void run_emulated_func(Snes *snes, uint32_t pc24);
static inline uint16_t read16(const uint8_t *ram, int addr);
static inline void write16(uint8_t *ram, int addr, uint16_t v);

// ---------------------------------------------------------------------------
// Auto-emitted *_emu delegation helpers (one per stub referenced by the
// translation but not defined in port/battle/CheckMonsterFlash.c).
// ---------------------------------------------------------------------------

// (no auto-emitted helpers)

// ---------------------------------------------------------------------------
// LLM-translated C function (verbatim copy from port/battle/CheckMonsterFlash.c)
// ---------------------------------------------------------------------------

// Entry mode: A 8-bit (mf=1), X/Y 16-bit (xf=0), DB=$D3, DP=0
// Logic:
//   1. Extract bits 0-2 of the input A into ram[$a9] via a series of LSR/ROR.
//   2. Shift the extracted value right by 5 using Lsr_5_emu.
//   3. Use the original extracted 3-bit value (in X) as an index into NoMonsterFlashTbl.
//   4. Iteratively shift the table value left (ASL) and decrement Y (the shifted index)
//      until the high bit is set (BPL loop).
//   5. If a bit was shifted into carry, return the value ROR'd; otherwise return 0.
static void CheckMonsterFlash_c(Snes *snes) {
    uint8_t *ram = snes->ram;
    uint8_t a = (uint8_t)snes->cpu->a;

    // stz $a9
    ram[0xA9] = 0;

    // Extract bits 0, 1, 2 of A into $a9 (effectively: ram[0xA9] = (a & 7) << 5)
    // Sequence: lsr A / ror $a9 (x3)
    for (int i = 0; i < 3; i++) {
        bool carry = (a & 1);
        a >>= 1; // Pitfall 7: 8-bit shift
        uint8_t val_a9 = ram[0xA9];
        bool carry_a9 = (val_a9 & 1);
        ram[0xA9] = (uint8_t)((val_a9 >> 1) | (carry << 7));
        // Note: ROR on memory in 65816 pushes the low bit of target into C, 
        // and C into the high bit of target.
    }

    uint8_t x_idx = ram[0xA9]; // tax
    snes->cpu->a = ram[0xA9];  // lda $a9
    
    Lsr_5_emu(snes);           // jsr Lsr_5
    
    uint8_t shifted_idx = (uint8_t)snes->cpu->a;
    ram[0xA9] = shifted_idx;   // sta $a9
    
    uint8_t y_val = shifted_idx; // lda $a9 / tay
    
    // Table lookup: f:NoMonsterFlashTbl (Bank $F)
    // The index used is x_idx (the bits extracted before Lsr_5)
    uint8_t mask = snes->rom[0xF0000 + x_idx]; // ROM Bank F mapping
    
    uint8_t current_mask = mask;
    bool carry = false;

    // @d36e: asl / dey / bpl loop
    // This loop shifts the mask left until the 7th bit is set or Y hits 0.
    do {
        carry = (current_mask & 0x80) != 0;
        current_mask = (uint8_t)(current_mask << 1); // Pitfall 7
        if (y_val == 0) break;
        y_val--;
    } while ((current_mask & 0x80) == 0); // bpl checks N flag (bit 7 == 0)

    if (carry) {
        // bcc @d376 not taken: carry is set
        // ror A: Rotate Carry into bit 7, shift bits right
        snes->cpu->a = (uint8_t)((current_mask >> 1) | (carry << 7));
    } else {
        // bcc @d376 taken
        snes->cpu->a = 0; // clr_a (tdc where DP=0)
    }
}


// ---------------------------------------------------------------------------
// Common helpers (same shape as the manual M2/M3/M4 spikes)
// ---------------------------------------------------------------------------

static uint8_t *read_file(const char *path, size_t *out_len) {
    FILE *f = fopen(path, "rb");
    if (!f) { perror(path); return NULL; }
    fseek(f, 0, SEEK_END); long sz = ftell(f); fseek(f, 0, SEEK_SET);
    uint8_t *buf = malloc(sz);
    if (fread(buf, 1, sz, f) != (size_t)sz) { free(buf); fclose(f); return NULL; }
    fclose(f); *out_len = sz; return buf;
}

static inline uint32_t stack_addr(const Cpu *cpu) {
    return cpu->e ? (0x0100u | (cpu->sp & 0xFFu)) : cpu->sp;
}

static void run_emulated_func(Snes *snes, uint32_t pc24) {
    Cpu *cpu = snes->cpu;
    uint16_t sp_save = cpu->sp;
    snes->ram[stack_addr(cpu)] = 0x12; cpu->sp--;
    snes->ram[stack_addr(cpu)] = 0x34; cpu->sp--;
    cpu->k = (uint8_t)(pc24 >> 16);
    cpu->pc = (uint16_t)(pc24 & 0xFFFF);
    long max_ops = 200000;
    while (cpu->sp != sp_save && max_ops-- > 0) {
        cpu_runOpcode(cpu);
        if (cpu->waiting || cpu->stopped) break;
    }
}

typedef struct {
    uint8_t ram[0x20000];
    uint16_t a, x, y, sp, pc, dp;
    uint8_t k, db;
    bool c, z, v, n, i, d, xf, mf, e;
    bool waiting, stopped, irqWanted, nmiWanted;
} Snap;

static void snap_take(Snap *s, Snes *snes) {
    memcpy(s->ram, snes->ram, sizeof(s->ram));
    Cpu *c = snes->cpu;
    s->a=c->a; s->x=c->x; s->y=c->y; s->sp=c->sp; s->pc=c->pc; s->dp=c->dp;
    s->k=c->k; s->db=c->db;
    s->c=c->c; s->z=c->z; s->v=c->v; s->n=c->n;
    s->i=c->i; s->d=c->d; s->xf=c->xf; s->mf=c->mf; s->e=c->e;
    s->waiting=c->waiting; s->stopped=c->stopped;
    s->irqWanted=c->irqWanted; s->nmiWanted=c->nmiWanted;
}
static void snap_restore(const Snap *s, Snes *snes) {
    memcpy(snes->ram, s->ram, sizeof(s->ram));
    Cpu *c = snes->cpu;
    c->a=s->a; c->x=s->x; c->y=s->y; c->sp=s->sp; c->pc=s->pc; c->dp=s->dp;
    c->k=s->k; c->db=s->db;
    c->c=s->c; c->z=s->z; c->v=s->v; c->n=s->n;
    c->i=s->i; c->d=s->d; c->xf=s->xf; c->mf=s->mf; c->e=s->e;
    c->waiting=s->waiting; c->stopped=s->stopped;
    c->irqWanted=s->irqWanted; c->nmiWanted=s->nmiWanted;
}

static inline uint16_t read16(const uint8_t *ram, int addr) {
    return (uint16_t)(ram[addr] | (ram[addr + 1] << 8));
}
static inline void write16(uint8_t *ram, int addr, uint16_t v) {
    ram[addr] = v & 0xFF; ram[addr + 1] = (v >> 8) & 0xFF;
}

// ---------------------------------------------------------------------------
// asm wrapper from the contract
// ---------------------------------------------------------------------------

static void run_asm(Snes *snes, uint8_t arg_a) {
    Cpu *c = snes->cpu;
    c->dp = 0;
    c->db = 0x7E;
    c->mf = true;
    c->xf = false;
    c->a = 0; c->x = 0; c->y = 0;
    c->a = arg_a;
    c->z = (arg_a == 0);
    c->n = ((arg_a & 0x80) != 0);
    run_emulated_func(snes, TARGET_ADDR_24);
}

// ---------------------------------------------------------------------------
// Host PRNG
// ---------------------------------------------------------------------------

static uint32_t host_rng_state = 0xC0FFEEu;
static uint32_t host_rng(void) {
    uint32_t x = host_rng_state;
    x ^= x << 13; x ^= x >> 17; x ^= x << 5;
    host_rng_state = x; return x;
}

// ---------------------------------------------------------------------------
// Trial driver
// ---------------------------------------------------------------------------

int main(int argc, char **argv) {
    if (argc < 2) {
        fprintf(stderr, "usage: %s <rom.sfc> [n_trials]\n", argv[0]);
        return 1;
    }
    int n_trials = (argc >= 3) ? atoi(argv[2]) : 1000;

    size_t rom_len = 0;
    uint8_t *rom = read_file(argv[1], &rom_len);
    if (!rom) return 2;

    Snes *snes = snes_init();
    if (!snes_loadRom(snes, rom, rom_len)) { fprintf(stderr, "loadRom fail\n"); return 3; }
    snes_reset(snes, true);
    for (int i = 0; i < 60; i++) snes_runFrame(snes);
    snes->cpu->i = true; snes->cpu->nmiWanted = false; snes->cpu->irqWanted = false;

    Snap baseline;
    snap_take(&baseline, snes);

    fprintf(stderr, "CheckMonsterFlash asm vs C : %d trials\n", n_trials);

    int fails = 0;
    for (int trial = 0; trial < n_trials; trial++) {
        snap_restore(&baseline, snes);

        // Randomise inputs.
        // no RAM inputs
        uint8_t arg_a = (uint8_t)host_rng();

        // Pre-call snapshot for replaying C with the exact same state.
        Snap pre;
        snap_take(&pre, snes);

        // Run ASM
        run_asm(snes, arg_a);
        uint8_t out_asm = snes->ram[0x00A9];

        // Restore and run C
        snap_restore(&pre, snes);
        CheckMonsterFlash_c(snes, arg_a);
        uint8_t out_c = snes->ram[0x00A9];

        bool ok = (out_asm == out_c);
        if (!ok) {
            printf("trial %4d : asm=%u c=%u  FAIL\n", trial, out_asm, out_c);
            fails++;
        }
    }

    printf("\n=== summary === trials: %d, fails: %d\n", n_trials, fails);
    free(rom);
    return fails == 0 ? 0 : 1;
}
