// AUTO-GENERATED parity spike for field::CheckPlayerMoveWorld @ $00:AB84.
// Generated by translator/generate_spike.py from port/field/CheckPlayerMoveWorld.c.
// DO NOT EDIT BY HAND — regenerate via:
//   python translator/generate_spike.py port/field/CheckPlayerMoveWorld.c

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdint.h>
#include <stdbool.h>

#include "snes.h"
#include "cpu.h"

#define TARGET_ADDR_24 0x00AB84u

// Forward declarations for helpers defined later in this TU but used by the
// inlined LLM translation below.
static void run_emulated_func(Snes *snes, uint32_t pc24);
static inline uint16_t read16(const uint8_t *ram, int addr);
static inline void write16(uint8_t *ram, int addr, uint16_t v);

// ---------------------------------------------------------------------------
// Auto-emitted *_emu delegation helpers (one per stub referenced by the
// translation but not defined in port/field/CheckPlayerMoveWorld.c).
// ---------------------------------------------------------------------------

// Auto-emitted delegation wrapper for UpdateLocalTiles @ $009F6C (referenced as update_local_tiles_emu)
static uint16_t update_local_tiles_emu(Snes *snes) {
    Cpu *c = snes->cpu;
    uint16_t saved_a=c->a, saved_x=c->x, saved_y=c->y, saved_sp=c->sp;
    uint16_t saved_pc=c->pc, saved_dp=c->dp;
    uint8_t saved_k=c->k, saved_db=c->db;
    bool saved_mf=c->mf, saved_xf=c->xf;
    c->dp = 0; c->db = 0x7E;
    c->mf = true; c->xf = false;
    run_emulated_func(snes, 0x009F6Cu);
    uint16_t result = c->a;
    c->x=saved_x; c->y=saved_y;
    c->sp=saved_sp; c->pc=saved_pc; c->dp=saved_dp;
    c->k=saved_k; c->db=saved_db;
    c->mf=saved_mf; c->xf=saved_xf;
    c->a = saved_a;
    return result;
}

// Auto-emitted delegation wrapper for ChangeVehicle @ $009E3B (referenced as change_vehicle_emu)
static uint16_t change_vehicle_emu(Snes *snes) {
    Cpu *c = snes->cpu;
    uint16_t saved_a=c->a, saved_x=c->x, saved_y=c->y, saved_sp=c->sp;
    uint16_t saved_pc=c->pc, saved_dp=c->dp;
    uint8_t saved_k=c->k, saved_db=c->db;
    bool saved_mf=c->mf, saved_xf=c->xf;
    c->dp = 0; c->db = 0x7E;
    c->mf = true; c->xf = false;
    run_emulated_func(snes, 0x009E3Bu);
    uint16_t result = c->a;
    c->x=saved_x; c->y=saved_y;
    c->sp=saved_sp; c->pc=saved_pc; c->dp=saved_dp;
    c->k=saved_k; c->db=saved_db;
    c->mf=saved_mf; c->xf=saved_xf;
    c->a = saved_a;
    return result;
}

// Auto-emitted delegation wrapper for CheckVehicleBlock @ $00AC7D (referenced as check_vehicle_block_emu)
static uint16_t check_vehicle_block_emu(Snes *snes) {
    Cpu *c = snes->cpu;
    uint16_t saved_a=c->a, saved_x=c->x, saved_y=c->y, saved_sp=c->sp;
    uint16_t saved_pc=c->pc, saved_dp=c->dp;
    uint8_t saved_k=c->k, saved_db=c->db;
    bool saved_mf=c->mf, saved_xf=c->xf;
    c->dp = 0; c->db = 0x7E;
    c->mf = true; c->xf = false;
    run_emulated_func(snes, 0x00AC7Du);
    uint16_t result = c->a;
    c->x=saved_x; c->y=saved_y;
    c->sp=saved_sp; c->pc=saved_pc; c->dp=saved_dp;
    c->k=saved_k; c->db=saved_db;
    c->mf=saved_mf; c->xf=saved_xf;
    c->a = saved_a;
    return result;
}

// Auto-emitted delegation wrapper for DoPoisonDmg @ $0097B3 (referenced as do_poison_dmg_emu)
static uint16_t do_poison_dmg_emu(Snes *snes) {
    Cpu *c = snes->cpu;
    uint16_t saved_a=c->a, saved_x=c->x, saved_y=c->y, saved_sp=c->sp;
    uint16_t saved_pc=c->pc, saved_dp=c->dp;
    uint8_t saved_k=c->k, saved_db=c->db;
    bool saved_mf=c->mf, saved_xf=c->xf;
    c->dp = 0; c->db = 0x7E;
    c->mf = true; c->xf = false;
    run_emulated_func(snes, 0x0097B3u);
    uint16_t result = c->a;
    c->x=saved_x; c->y=saved_y;
    c->sp=saved_sp; c->pc=saved_pc; c->dp=saved_dp;
    c->k=saved_k; c->db=saved_db;
    c->mf=saved_mf; c->xf=saved_xf;
    c->a = saved_a;
    return result;
}

// Auto-emitted delegation wrapper for DecodeWorldTilemap @ $00FD20 (referenced as decode_world_tilemap_emu)
static uint16_t decode_world_tilemap_emu(Snes *snes) {
    Cpu *c = snes->cpu;
    uint16_t saved_a=c->a, saved_x=c->x, saved_y=c->y, saved_sp=c->sp;
    uint16_t saved_pc=c->pc, saved_dp=c->dp;
    uint8_t saved_k=c->k, saved_db=c->db;
    bool saved_mf=c->mf, saved_xf=c->xf;
    c->dp = 0; c->db = 0x7E;
    c->mf = true; c->xf = false;
    run_emulated_func(snes, 0x00FD20u);
    uint16_t result = c->a;
    c->x=saved_x; c->y=saved_y;
    c->sp=saved_sp; c->pc=saved_pc; c->dp=saved_dp;
    c->k=saved_k; c->db=saved_db;
    c->mf=saved_mf; c->xf=saved_xf;
    c->a = saved_a;
    return result;
}

// Auto-emitted delegation wrapper for UpdateScrollWorld @ $00F633 (referenced as update_scroll_world_emu)
static uint16_t update_scroll_world_emu(Snes *snes) {
    Cpu *c = snes->cpu;
    uint16_t saved_a=c->a, saved_x=c->x, saved_y=c->y, saved_sp=c->sp;
    uint16_t saved_pc=c->pc, saved_dp=c->dp;
    uint8_t saved_k=c->k, saved_db=c->db;
    bool saved_mf=c->mf, saved_xf=c->xf;
    c->dp = 0; c->db = 0x7E;
    c->mf = true; c->xf = false;
    run_emulated_func(snes, 0x00F633u);
    uint16_t result = c->a;
    c->x=saved_x; c->y=saved_y;
    c->sp=saved_sp; c->pc=saved_pc; c->dp=saved_dp;
    c->k=saved_k; c->db=saved_db;
    c->mf=saved_mf; c->xf=saved_xf;
    c->a = saved_a;
    return result;
}


// ---------------------------------------------------------------------------
// LLM-translated C function (verbatim copy from port/field/CheckPlayerMoveWorld.c)
// ---------------------------------------------------------------------------

#include "snes/snes.h"

// Entry mode: A 8-bit (mf=1), X 16-bit (xf=0), DB=0, DP=0
// Logic: Handles player movement input, coordinate diffing, vehicle passability, 
// and updates world scrolling.
void CheckPlayerMoveWorld_c(Snes *snes) {
    uint8_t *ram = snes->ram;

    // @ab84: lda $d5 / bne @ab89
    // If ram[0xd5] == 0, we return.
    if (ram[0xD5] == 0) return;

    update_local_tiles_emu(snes);

    // @ab8f: lda $b1 / beq @ab98
    if (ram[0xB1] != 0) {
        ram[0x02] = ram[0x04];
        ram[0x03] = ram[0x05];
    }

    // @ab98: lda $a1 / and #$41 / sta $d2
    ram[0xD2] = ram[0xA1] & 0x41;

    uint8_t move_dir = 0;
    bool dir_set = false;

    // @ab9c: lda $1715 / cmp #$02 / bne @abe5
    if (ram[0x1715] == 0x02) {
        // @aba0: lda $1706 / sbc $1716
        int8_t dx = (int8_t)ram[0x1706] - (int8_t)ram[0x1716];
        if (dx != 0) {
            move_dir = (dx < 0) ? 0x01 : 0x03; // @abb9: bpl @abb9 / lda #$01 vs #$03
            dir_set = true;
        } else {
            // @abc2: lda $1707 / sbc $1717
            int8_t dy = (int8_t)ram[0x1707] - (int8_t)ram[0x1717];
            if (dy != 0) {
                move_dir = (dy < 0) ? 0x02 : 0x00; // @abd6: bpl @abd6 / lda #$02 vs #$00
                dir_set = true;
            } else {
                // @abdf: lda #$80 / sta $02 / stz $54
                ram[0x02] = 0x80;
                ram[0x54] = 0;
            }
        }
    }

    // @abe5: jsr ChangeVehicle
    change_vehicle_emu(snes);

    // If move_dir wasn't set by coordinate diff, check joystick input
    if (!dir_set) {
        uint8_t input = ram[0x03];
        if ((input & 0x0F) != 0) {
            if (input & 0x08) { // JOY_RIGHT
                move_dir = 0x01;
            } else if (input & 0x04) { // JOY_LEFT
                move_dir = 0x03;
            } else if (input & 0x02) { // JOY_DOWN
                move_dir = 0x02;
            } else {
                move_dir = 0x00;
            }
        } else {
            move_dir = 0x00;
        }
    }

    // @ac0f: sta $1705 / inc / sta $0709
    uint8_t dir_val = (uint8_t)(move_dir + 1);
    ram[0x1705] = dir_val;
    ram[0x0709] = dir_val;

    // @ac12: asl / tax
    uint8_t x_idx = (uint8_t)(dir_val << 1);
    
    bool passable = false;
    // @ac15: lda $b1 / bne @ac68
    if (ram[0xB1] != 0) {
        passable = true; 
    } else {
        // @ac18: lda $1700 / cmp #$01 / bne @ac46
        if (ram[0x1700] == 0x01) {
            // @ac1b: lda $1704 / cmp #$05
            if (ram[0x1704] == 0x05 && (ram[0x1287] & 0x02)) {
                passable = (ram[0xA1 + x_idx] & 0x02) != 0; // VehiclePassBit = 0x02
            } else if (ram[0x1704] == 0x04 && (ram[0x1281] & 0x04)) {
                passable = (ram[0xA1 + x_idx] & 0x02) != 0;
            } else {
                // @ac46: lda $1704 / beq @ac56
                if (ram[0x1704] == 0) {
                    passable = (ram[0xA1 + x_idx] & 0x41 & ram[0xD2]) != 0;
                }
            }
        } else {
            // @ac46: lda $1704 / beq @ac56
            if (ram[0x1704] == 0) {
                passable = (ram[0xA1 + x_idx] & 0x41 & ram[0xD2]) != 0;
            }
        }
    }

    // Final block check
    if (passable) {
        check_vehicle_block_emu(snes);
        if (ram[0x0A] == 0) {
            // Not blocked: proceed to @ac68
            ram[0xAB] = ram[0x0709];
            do_poison_dmg_emu(snes);
            ram[0x070A] = ram[0x1707];
            decode_world_tilemap_emu(snes);
            update_scroll_world_emu(snes);
            return;
        }
    }

    // @ac65: stz $ab / rts
    ram[0xAB] = 0;
}


// ---------------------------------------------------------------------------
// Common helpers (same shape as the manual M2/M3/M4 spikes)
// ---------------------------------------------------------------------------

static uint8_t *read_file(const char *path, size_t *out_len) {
    FILE *f = fopen(path, "rb");
    if (!f) { perror(path); return NULL; }
    fseek(f, 0, SEEK_END); long sz = ftell(f); fseek(f, 0, SEEK_SET);
    uint8_t *buf = malloc(sz);
    if (fread(buf, 1, sz, f) != (size_t)sz) { free(buf); fclose(f); return NULL; }
    fclose(f); *out_len = sz; return buf;
}

static inline uint32_t stack_addr(const Cpu *cpu) {
    return cpu->e ? (0x0100u | (cpu->sp & 0xFFu)) : cpu->sp;
}

static void run_emulated_func(Snes *snes, uint32_t pc24) {
    Cpu *cpu = snes->cpu;
    uint16_t sp_save = cpu->sp;
    snes->ram[stack_addr(cpu)] = 0x12; cpu->sp--;
    snes->ram[stack_addr(cpu)] = 0x34; cpu->sp--;
    cpu->k = (uint8_t)(pc24 >> 16);
    cpu->pc = (uint16_t)(pc24 & 0xFFFF);
    long max_ops = 200000;
    while (cpu->sp != sp_save && max_ops-- > 0) {
        cpu_runOpcode(cpu);
        if (cpu->waiting || cpu->stopped) break;
    }
}

typedef struct {
    uint8_t ram[0x20000];
    uint16_t a, x, y, sp, pc, dp;
    uint8_t k, db;
    bool c, z, v, n, i, d, xf, mf, e;
    bool waiting, stopped, irqWanted, nmiWanted;
} Snap;

static void snap_take(Snap *s, Snes *snes) {
    memcpy(s->ram, snes->ram, sizeof(s->ram));
    Cpu *c = snes->cpu;
    s->a=c->a; s->x=c->x; s->y=c->y; s->sp=c->sp; s->pc=c->pc; s->dp=c->dp;
    s->k=c->k; s->db=c->db;
    s->c=c->c; s->z=c->z; s->v=c->v; s->n=c->n;
    s->i=c->i; s->d=c->d; s->xf=c->xf; s->mf=c->mf; s->e=c->e;
    s->waiting=c->waiting; s->stopped=c->stopped;
    s->irqWanted=c->irqWanted; s->nmiWanted=c->nmiWanted;
}
static void snap_restore(const Snap *s, Snes *snes) {
    memcpy(snes->ram, s->ram, sizeof(s->ram));
    Cpu *c = snes->cpu;
    c->a=s->a; c->x=s->x; c->y=s->y; c->sp=s->sp; c->pc=s->pc; c->dp=s->dp;
    c->k=s->k; c->db=s->db;
    c->c=s->c; c->z=s->z; c->v=s->v; c->n=s->n;
    c->i=s->i; c->d=s->d; c->xf=s->xf; c->mf=s->mf; c->e=s->e;
    c->waiting=s->waiting; c->stopped=s->stopped;
    c->irqWanted=s->irqWanted; c->nmiWanted=s->nmiWanted;
}

static inline uint16_t read16(const uint8_t *ram, int addr) {
    return (uint16_t)(ram[addr] | (ram[addr + 1] << 8));
}
static inline void write16(uint8_t *ram, int addr, uint16_t v) {
    ram[addr] = v & 0xFF; ram[addr + 1] = (v >> 8) & 0xFF;
}

// ---------------------------------------------------------------------------
// asm wrapper from the contract
// ---------------------------------------------------------------------------

static void run_asm(Snes *snes) {
    Cpu *c = snes->cpu;
    c->dp = 0;
    c->db = 0x7E;
    c->mf = true;
    c->xf = false;
    c->a = 0; c->x = 0; c->y = 0;
    // no register inputs
    // no entry flags
    run_emulated_func(snes, TARGET_ADDR_24);
}

// ---------------------------------------------------------------------------
// Host PRNG
// ---------------------------------------------------------------------------

static uint32_t host_rng_state = 0xC0FFEEu;
static uint32_t host_rng(void) {
    uint32_t x = host_rng_state;
    x ^= x << 13; x ^= x >> 17; x ^= x << 5;
    host_rng_state = x; return x;
}

// ---------------------------------------------------------------------------
// Trial driver
// ---------------------------------------------------------------------------

int main(int argc, char **argv) {
    if (argc < 2) {
        fprintf(stderr, "usage: %s <rom.sfc> [n_trials]\n", argv[0]);
        return 1;
    }
    int n_trials = (argc >= 3) ? atoi(argv[2]) : 1000;

    size_t rom_len = 0;
    uint8_t *rom = read_file(argv[1], &rom_len);
    if (!rom) return 2;

    Snes *snes = snes_init();
    if (!snes_loadRom(snes, rom, rom_len)) { fprintf(stderr, "loadRom fail\n"); return 3; }
    snes_reset(snes, true);
    for (int i = 0; i < 60; i++) snes_runFrame(snes);
    snes->cpu->i = true; snes->cpu->nmiWanted = false; snes->cpu->irqWanted = false;

    Snap baseline;
    snap_take(&baseline, snes);

    fprintf(stderr, "CheckPlayerMoveWorld asm vs C : %d trials\n", n_trials);

    int fails = 0;
    for (int trial = 0; trial < n_trials; trial++) {
        snap_restore(&baseline, snes);

        // Randomise inputs.
        snes->ram[0x00D5] = (uint8_t)host_rng();
        snes->ram[0x00B1] = (uint8_t)host_rng();
        snes->ram[0x00A1] = (uint8_t)host_rng();
        snes->ram[0x1715] = (uint8_t)host_rng();
        snes->ram[0x1706] = (uint8_t)host_rng();
        snes->ram[0x1716] = (uint8_t)host_rng();
        snes->ram[0x1707] = (uint8_t)host_rng();
        snes->ram[0x1717] = (uint8_t)host_rng();


        // Pre-call snapshot for replaying C with the exact same state.
        Snap pre;
        snap_take(&pre, snes);

        // Run ASM
        run_asm(snes);
        uint8_t out_asm = snes->ram[0x00AB];

        // Restore and run C
        snap_restore(&pre, snes);
        CheckPlayerMoveWorld_c(snes);
        uint8_t out_c = snes->ram[0x00AB];

        bool ok = (out_asm == out_c);
        if (!ok) {
            printf("trial %4d : asm=%u c=%u  FAIL\n", trial, out_asm, out_c);
            fails++;
        }
    }

    printf("\n=== summary === trials: %d, fails: %d\n", n_trials, fails);
    free(rom);
    return fails == 0 ? 0 : 1;
}
