// AUTO-GENERATED parity spike for battle::AICond_00 @ $03:BCE8.
// Generated by translator/generate_spike.py from port/battle/AICond_00.c.
// DO NOT EDIT BY HAND — regenerate via:
//   python translator/generate_spike.py port/battle/AICond_00.c

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdint.h>
#include <stdbool.h>

#include "snes.h"
#include "cpu.h"

#define TARGET_ADDR_24 0x03BCE8u

// Forward declarations for helpers defined later in this TU but used by the
// inlined LLM translation below.
static void run_emulated_func(Snes *snes, uint32_t pc24);
static inline uint16_t read16(const uint8_t *ram, int addr);
static inline void write16(uint8_t *ram, int addr, uint16_t v);

// ---------------------------------------------------------------------------
// Auto-emitted *_emu delegation helpers (one per stub referenced by the
// translation but not defined in port/battle/AICond_00.c).
// ---------------------------------------------------------------------------

// Auto-emitted delegation wrapper for GetAICondTarget @ $03BF0F (referenced as GetAICondTarget_emu)
static uint16_t GetAICondTarget_emu(Snes *snes) {
    Cpu *c = snes->cpu;
    uint16_t saved_a=c->a, saved_x=c->x, saved_y=c->y, saved_sp=c->sp;
    uint16_t saved_pc=c->pc, saved_dp=c->dp;
    uint8_t saved_k=c->k, saved_db=c->db;
    bool saved_mf=c->mf, saved_xf=c->xf;
    c->dp = 0; c->db = 0x7E;
    c->mf = true; c->xf = false;
    run_emulated_func(snes, 0x03BF0Fu);
    uint16_t result = c->a;
    c->x=saved_x; c->y=saved_y;
    c->sp=saved_sp; c->pc=saved_pc; c->dp=saved_dp;
    c->k=saved_k; c->db=saved_db;
    c->mf=saved_mf; c->xf=saved_xf;
    c->a = saved_a;
    return result;
}


// ---------------------------------------------------------------------------
// LLM-translated C function (verbatim copy from port/battle/AICond_00.c)
// ---------------------------------------------------------------------------

// Entry mode: A 8-bit (mf=1), X 16-bit (xf=0), DB=$BC, DP=0
// Purpose: Iterates through AI conditions in a table at $35D0. 
// Validates targets against a mask defined in WRAM and determines if 
// specific AI flags ($289D) trigger a a result in $DE.
static void AICond_00_c(Snes *snes) {
    uint8_t *ram = snes->ram;
    Cpu *cpu = snes->cpu;

    GetAICondTarget_emu(snes);

    if (ram[0xDD] == 0) return; // beq @bd3c

    // Construct indirect pointer at $80/$81
    // clc / lda #$03 / adc $289e / sta $80
    uint16_t sum = 0x03 + ram[0x289E];
    ram[0x80] = (uint8_t)sum;
    
    // lda #$20 / adc #$00 / sta $81
    // Carry from previous ADC is propagated to $20
    uint8_t carry = (sum > 0xFF) ? 1 : 0;
    ram[0x81] = (uint8_t)(0x20 + carry);

    // clr_ax: A = X = D (DP=0)
    cpu->a = 0;
    cpu->x = 0;

    do {
        // lda $35d0,x / sta $a9
        // lda $35d1,x / sta $aa
        ram[0xA9] = ram[0x35D0 + cpu->x];
        ram[0xAA] = ram[0x35D1 + cpu->x];

        // ldy $a9 / cpy #$ffff
        // Y is 16-bit, loading 8-bit $a9 results in 0x00XX. 
        // 0x00XX can never equal 0xFFFF.
        uint16_t y = ram[0xA9]; 
        if (y == 0xFFFF) { // beq @bd28
            goto loop_continue;
        }

        // lda ($80) / and $289f / bne @bd1f
        uint16_t ptr_addr = read16(ram, 0x80);
        uint8_t val = ram[ptr_addr];
        if ((val & ram[0x289F]) != 0) {
            // @bd1f: lda #$01 / sta $de
            ram[0xDE] = 0x01;
            // lda $289d / bpl @bd3c
            if ((int8_t)ram[0x289D] >= 0) return;
        } else {
            // lda $289d / bpl @bd28
            if ((int8_t)ram[0x289D] < 0) {
                // stz $de / rts
                ram[0xDE] = 0;
                return;
            }
        }

    loop_continue:
        // @bd28: longa / clc / lda $80 / adc #$0080 / sta $80
        // Increments the indirect pointer by 0x80
        uint16_t ptr = read16(ram, 0x80);
        ptr += 0x0080;
        write16(ram, 0x80, ptr);

        // shorta0 / inx2 / cpx #$001a
        cpu->x += 2;
        if (cpu->x == 0x001A) break; // bne @bcff (loop if NOT 0x1A)

    } while (1);
}


// ---------------------------------------------------------------------------
// Common helpers (same shape as the manual M2/M3/M4 spikes)
// ---------------------------------------------------------------------------

static uint8_t *read_file(const char *path, size_t *out_len) {
    FILE *f = fopen(path, "rb");
    if (!f) { perror(path); return NULL; }
    fseek(f, 0, SEEK_END); long sz = ftell(f); fseek(f, 0, SEEK_SET);
    uint8_t *buf = malloc(sz);
    if (fread(buf, 1, sz, f) != (size_t)sz) { free(buf); fclose(f); return NULL; }
    fclose(f); *out_len = sz; return buf;
}

static inline uint32_t stack_addr(const Cpu *cpu) {
    return cpu->e ? (0x0100u | (cpu->sp & 0xFFu)) : cpu->sp;
}

static void run_emulated_func(Snes *snes, uint32_t pc24) {
    Cpu *cpu = snes->cpu;
    uint16_t sp_save = cpu->sp;
    snes->ram[stack_addr(cpu)] = 0x12; cpu->sp--;
    snes->ram[stack_addr(cpu)] = 0x34; cpu->sp--;
    cpu->k = (uint8_t)(pc24 >> 16);
    cpu->pc = (uint16_t)(pc24 & 0xFFFF);
    long max_ops = 200000;
    while (cpu->sp != sp_save && max_ops-- > 0) {
        cpu_runOpcode(cpu);
        if (cpu->waiting || cpu->stopped) break;
    }
}

typedef struct {
    uint8_t ram[0x20000];
    uint16_t a, x, y, sp, pc, dp;
    uint8_t k, db;
    bool c, z, v, n, i, d, xf, mf, e;
    bool waiting, stopped, irqWanted, nmiWanted;
} Snap;

static void snap_take(Snap *s, Snes *snes) {
    memcpy(s->ram, snes->ram, sizeof(s->ram));
    Cpu *c = snes->cpu;
    s->a=c->a; s->x=c->x; s->y=c->y; s->sp=c->sp; s->pc=c->pc; s->dp=c->dp;
    s->k=c->k; s->db=c->db;
    s->c=c->c; s->z=c->z; s->v=c->v; s->n=c->n;
    s->i=c->i; s->d=c->d; s->xf=c->xf; s->mf=c->mf; s->e=c->e;
    s->waiting=c->waiting; s->stopped=c->stopped;
    s->irqWanted=c->irqWanted; s->nmiWanted=c->nmiWanted;
}
static void snap_restore(const Snap *s, Snes *snes) {
    memcpy(snes->ram, s->ram, sizeof(s->ram));
    Cpu *c = snes->cpu;
    c->a=s->a; c->x=s->x; c->y=s->y; c->sp=s->sp; c->pc=s->pc; c->dp=s->dp;
    c->k=s->k; c->db=s->db;
    c->c=s->c; c->z=s->z; c->v=s->v; c->n=s->n;
    c->i=s->i; c->d=s->d; c->xf=s->xf; c->mf=s->mf; c->e=s->e;
    c->waiting=s->waiting; c->stopped=s->stopped;
    c->irqWanted=s->irqWanted; c->nmiWanted=s->nmiWanted;
}

static inline uint16_t read16(const uint8_t *ram, int addr) {
    return (uint16_t)(ram[addr] | (ram[addr + 1] << 8));
}
static inline void write16(uint8_t *ram, int addr, uint16_t v) {
    ram[addr] = v & 0xFF; ram[addr + 1] = (v >> 8) & 0xFF;
}

// ---------------------------------------------------------------------------
// asm wrapper from the contract
// ---------------------------------------------------------------------------

static void run_asm(Snes *snes) {
    Cpu *c = snes->cpu;
    c->dp = 0;
    c->db = 0x7E;
    c->mf = true;
    c->xf = false;
    c->a = 0; c->x = 0; c->y = 0;
    // no register inputs
    // no entry flags
    run_emulated_func(snes, TARGET_ADDR_24);
}

// ---------------------------------------------------------------------------
// Host PRNG
// ---------------------------------------------------------------------------

static uint32_t host_rng_state = 0xC0FFEEu;
static uint32_t host_rng(void) {
    uint32_t x = host_rng_state;
    x ^= x << 13; x ^= x >> 17; x ^= x << 5;
    host_rng_state = x; return x;
}

// ---------------------------------------------------------------------------
// Trial driver
// ---------------------------------------------------------------------------

int main(int argc, char **argv) {
    if (argc < 2) {
        fprintf(stderr, "usage: %s <rom.sfc> [n_trials]\n", argv[0]);
        return 1;
    }
    int n_trials = (argc >= 3) ? atoi(argv[2]) : 1000;

    size_t rom_len = 0;
    uint8_t *rom = read_file(argv[1], &rom_len);
    if (!rom) return 2;

    Snes *snes = snes_init();
    if (!snes_loadRom(snes, rom, rom_len)) { fprintf(stderr, "loadRom fail\n"); return 3; }
    snes_reset(snes, true);
    for (int i = 0; i < 60; i++) snes_runFrame(snes);
    snes->cpu->i = true; snes->cpu->nmiWanted = false; snes->cpu->irqWanted = false;

    Snap baseline;
    snap_take(&baseline, snes);

    fprintf(stderr, "AICond_00 asm vs C : %d trials\n", n_trials);

    int fails = 0;
    for (int trial = 0; trial < n_trials; trial++) {
        snap_restore(&baseline, snes);

        // Randomise inputs.
        snes->ram[0x00DD] = (uint8_t)host_rng();
        snes->ram[0x289E] = (uint8_t)host_rng();
        snes->ram[0x289F] = (uint8_t)host_rng();
        snes->ram[0x289D] = (uint8_t)host_rng();
        snes->ram[0x35D0] = (uint8_t)host_rng();


        // Pre-call snapshot for replaying C with the exact same state.
        Snap pre;
        snap_take(&pre, snes);

        // Run ASM
        run_asm(snes);
        uint8_t out_asm = snes->ram[0x00DE];

        // Restore and run C
        snap_restore(&pre, snes);
        AICond_00_c(snes);
        uint8_t out_c = snes->ram[0x00DE];

        bool ok = (out_asm == out_c);
        if (!ok) {
            printf("trial %4d : asm=%u c=%u  FAIL\n", trial, out_asm, out_c);
            fails++;
        }
    }

    printf("\n=== summary === trials: %d, fails: %d\n", n_trials, fails);
    free(rom);
    return fails == 0 ? 0 : 1;
}
