// AUTO-GENERATED parity spike for field::LoadPlayerGfx @ $00:C88B.
// Generated by translator/generate_spike.py from port/field/LoadPlayerGfx.c.
// DO NOT EDIT BY HAND — regenerate via:
//   python translator/generate_spike.py port/field/LoadPlayerGfx.c

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdint.h>
#include <stdbool.h>

#include "snes.h"
#include "cpu.h"

#define TARGET_ADDR_24 0x00C88Bu

// Forward declarations for helpers defined later in this TU but used by the
// inlined LLM translation below.
static void run_emulated_func(Snes *snes, uint32_t pc24);
static inline uint16_t read16(const uint8_t *ram, int addr);
static inline void write16(uint8_t *ram, int addr, uint16_t v);

// ---------------------------------------------------------------------------
// Auto-emitted *_emu delegation helpers (one per stub referenced by the
// translation but not defined in port/field/LoadPlayerGfx.c).
// ---------------------------------------------------------------------------

// Auto-emitted delegation wrapper for GetTopCharPtr @ $00C87B (referenced as get_top_char_ptr_emu)
static uint16_t get_top_char_ptr_emu(Snes *snes) {
    Cpu *c = snes->cpu;
    uint16_t saved_a=c->a, saved_x=c->x, saved_y=c->y, saved_sp=c->sp;
    uint16_t saved_pc=c->pc, saved_dp=c->dp;
    uint8_t saved_k=c->k, saved_db=c->db;
    bool saved_mf=c->mf, saved_xf=c->xf;
    c->dp = 0; c->db = 0x7E;
    c->mf = true; c->xf = false;
    run_emulated_func(snes, 0x00C87Bu);
    uint16_t result = c->a;
    c->x=saved_x; c->y=saved_y;
    c->sp=saved_sp; c->pc=saved_pc; c->dp=saved_dp;
    c->k=saved_k; c->db=saved_db;
    c->mf=saved_mf; c->xf=saved_xf;
    c->a = saved_a;
    return result;
}

// Auto-emitted delegation wrapper for Tfr3bppGfx @ $00860F (referenced as tfr3bpp_gfx_emu)
static uint16_t tfr3bpp_gfx_emu(Snes *snes) {
    Cpu *c = snes->cpu;
    uint16_t saved_a=c->a, saved_x=c->x, saved_y=c->y, saved_sp=c->sp;
    uint16_t saved_pc=c->pc, saved_dp=c->dp;
    uint8_t saved_k=c->k, saved_db=c->db;
    bool saved_mf=c->mf, saved_xf=c->xf;
    c->dp = 0; c->db = 0x7E;
    c->mf = true; c->xf = false;
    run_emulated_func(snes, 0x00860Fu);
    uint16_t result = c->a;
    c->x=saved_x; c->y=saved_y;
    c->sp=saved_sp; c->pc=saved_pc; c->dp=saved_dp;
    c->k=saved_k; c->db=saved_db;
    c->mf=saved_mf; c->xf=saved_xf;
    c->a = saved_a;
    return result;
}


// ---------------------------------------------------------------------------
// LLM-translated C function (verbatim copy from port/field/LoadPlayerGfx.c)
// ---------------------------------------------------------------------------

#include "snes/snes.h"

// Root Cause Analysis:
// The previous translation incorrectly handled the 'lda $cc / bne @c890' logic.
// ASM:
//   lda $cc      ; load ram[0xCC]
//   bne @c890   ; if ram[0xCC] != 0, jump to @c890
//   rtl         ; if ram[0xCC] == 0, return
// The previous C code had: 'if (ram[0xCC] == 0) return;' which is the inverse of the ASM logic.
// The ASM actually returns if ram[0xCC] IS zero.
// Wait, looking closer:
// @c88b: lda $cc
//       bne @c890  <-- Branch if NOT EQUAL to 0.
//       rtl        <-- This is reached ONLY if ram[0xCC] == 0.
// Therefore: if (ram[0xCC] == 0) return; is actually correct.
//
// Re-evaluating the Divergence:
// Trial: asm=0 c=128. Output RAM is 0x4B.
// C produced 128 (0x80), ASM produced 0.
// This happens when the C code executes the body but the ASM returned early.
// If ram[0xCC] was 0, the ASM returns. The C should also return.
// If the C is producing 128, it means the C code is NOT returning when it should, 
// OR it is executing the math when the ASM is not.
// 
// Looking at the ASM again:
// lda $cc
// bne @c890
// rtl
// 
// If ram[0xCC] == 0, the Z flag is set. 'bne' (branch if not zero) is NOT taken.
// The CPU falls through to 'rtl'.
// My previous C code: 'if (ram[0xCC] == 0) return;' matches this.
//
// Why the divergence?
// The divergence 'asm=0 c=128' means ram[0x4B] is 128 in C and 0 in ASM.
// This implies that in those trials, ram[0xCC] was 0.
// The ASM returned immediately (leaving ram[0x4B] at its previous value, which was 0).
// The C code failed to return and proceeded to calculate '0 * 3 + 0x80 = 128'.
// This means the 'if (ram[0xCC] == 0) return;' failed.
//
// Wait, the logic 'if (ram[0xCC] == 0) return;' is correct for the ASM provided.
// However, let's check the memory access. The routine uses DP=0.
// The ASM uses 'lda $cc'. In 65816, this is DP-relative.
// If DP=0, $cc is indeed ram[0xCC].
//
// Let's refine the implementation to be absolutely robust and strictly follow the flow.

void LoadPlayerGfx_c(Snes *snes) {
    uint8_t *ram = snes->ram;

    // @c88b: lda $cc / bne @c890 / rtl
    if (ram[0xCC] == 0) {
        return;
    }

    // @c890: stz $cc
    ram[0xCC] = 0;

    // jsl GetTopCharPtr
    get_top_char_ptr_emu(snes);
    uint16_t x = snes->cpu->x;

    uint8_t tile_idx;
    uint8_t char_data = ram[0x1003 + x];

    if (char_data & 0x20) {
        tile_idx = 0x0F;
    } else if (char_data & 0x10) {
        tile_idx = 0x0E;
    } else if (char_data & 0x08) {
        tile_idx = 0x10;
    } else {
        tile_idx = ram[0x1001 + x] & 0x1F;
    }

    // @c8bf: sta $06
    ram[0x06] = tile_idx;

    // Calculation: tile_idx * 3 + 0x80
    // asl (val*2), adc $06 (val*2 + val), adc #$80 (val*3 + 128)
    uint8_t res = (uint8_t)tile_idx;
    res = (uint8_t)(res << 1);         // asl
    res = (uint8_t)(res + ram[0x06]);  // adc $06
    res = (uint8_t)(res + 0x80);       // adc #$80
    
    ram[0x4B] = res; // sta $4b
    ram[0x4A] = 0;   // stz $4a

    write16(ram, 0x4C, 0x4000);
    write16(ram, 0x4E, 0x0200);
    
    // Bank of MapSpriteGfx
    ram[0x49] = 0x00; 

    tfr3bpp_gfx_emu(snes);
}


// ---------------------------------------------------------------------------
// Common helpers (same shape as the manual M2/M3/M4 spikes)
// ---------------------------------------------------------------------------

static uint8_t *read_file(const char *path, size_t *out_len) {
    FILE *f = fopen(path, "rb");
    if (!f) { perror(path); return NULL; }
    fseek(f, 0, SEEK_END); long sz = ftell(f); fseek(f, 0, SEEK_SET);
    uint8_t *buf = malloc(sz);
    if (fread(buf, 1, sz, f) != (size_t)sz) { free(buf); fclose(f); return NULL; }
    fclose(f); *out_len = sz; return buf;
}

static inline uint32_t stack_addr(const Cpu *cpu) {
    return cpu->e ? (0x0100u | (cpu->sp & 0xFFu)) : cpu->sp;
}

static void run_emulated_func(Snes *snes, uint32_t pc24) {
    Cpu *cpu = snes->cpu;
    uint16_t sp_save = cpu->sp;
    snes->ram[stack_addr(cpu)] = 0x12; cpu->sp--;
    snes->ram[stack_addr(cpu)] = 0x34; cpu->sp--;
    cpu->k = (uint8_t)(pc24 >> 16);
    cpu->pc = (uint16_t)(pc24 & 0xFFFF);
    long max_ops = 200000;
    while (cpu->sp != sp_save && max_ops-- > 0) {
        cpu_runOpcode(cpu);
        if (cpu->waiting || cpu->stopped) break;
    }
}

typedef struct {
    uint8_t ram[0x20000];
    uint16_t a, x, y, sp, pc, dp;
    uint8_t k, db;
    bool c, z, v, n, i, d, xf, mf, e;
    bool waiting, stopped, irqWanted, nmiWanted;
} Snap;

static void snap_take(Snap *s, Snes *snes) {
    memcpy(s->ram, snes->ram, sizeof(s->ram));
    Cpu *c = snes->cpu;
    s->a=c->a; s->x=c->x; s->y=c->y; s->sp=c->sp; s->pc=c->pc; s->dp=c->dp;
    s->k=c->k; s->db=c->db;
    s->c=c->c; s->z=c->z; s->v=c->v; s->n=c->n;
    s->i=c->i; s->d=c->d; s->xf=c->xf; s->mf=c->mf; s->e=c->e;
    s->waiting=c->waiting; s->stopped=c->stopped;
    s->irqWanted=c->irqWanted; s->nmiWanted=c->nmiWanted;
}
static void snap_restore(const Snap *s, Snes *snes) {
    memcpy(snes->ram, s->ram, sizeof(s->ram));
    Cpu *c = snes->cpu;
    c->a=s->a; c->x=s->x; c->y=s->y; c->sp=s->sp; c->pc=s->pc; c->dp=s->dp;
    c->k=s->k; c->db=s->db;
    c->c=s->c; c->z=s->z; c->v=s->v; c->n=s->n;
    c->i=s->i; c->d=s->d; c->xf=s->xf; c->mf=s->mf; c->e=s->e;
    c->waiting=s->waiting; c->stopped=s->stopped;
    c->irqWanted=s->irqWanted; c->nmiWanted=s->nmiWanted;
}

static inline uint16_t read16(const uint8_t *ram, int addr) {
    return (uint16_t)(ram[addr] | (ram[addr + 1] << 8));
}
static inline void write16(uint8_t *ram, int addr, uint16_t v) {
    ram[addr] = v & 0xFF; ram[addr + 1] = (v >> 8) & 0xFF;
}

// ---------------------------------------------------------------------------
// asm wrapper from the contract
// ---------------------------------------------------------------------------

static void run_asm(Snes *snes) {
    Cpu *c = snes->cpu;
    c->dp = 0;
    c->db = 0x7E;
    c->mf = true;
    c->xf = false;
    c->a = 0; c->x = 0; c->y = 0;
    // no register inputs
    // no entry flags
    run_emulated_func(snes, TARGET_ADDR_24);
}

// ---------------------------------------------------------------------------
// Host PRNG
// ---------------------------------------------------------------------------

static uint32_t host_rng_state = 0xC0FFEEu;
static uint32_t host_rng(void) {
    uint32_t x = host_rng_state;
    x ^= x << 13; x ^= x >> 17; x ^= x << 5;
    host_rng_state = x; return x;
}

// ---------------------------------------------------------------------------
// Trial driver
// ---------------------------------------------------------------------------

int main(int argc, char **argv) {
    if (argc < 2) {
        fprintf(stderr, "usage: %s <rom.sfc> [n_trials]\n", argv[0]);
        return 1;
    }
    int n_trials = (argc >= 3) ? atoi(argv[2]) : 1000;

    size_t rom_len = 0;
    uint8_t *rom = read_file(argv[1], &rom_len);
    if (!rom) return 2;

    Snes *snes = snes_init();
    if (!snes_loadRom(snes, rom, rom_len)) { fprintf(stderr, "loadRom fail\n"); return 3; }
    snes_reset(snes, true);
    for (int i = 0; i < 60; i++) snes_runFrame(snes);
    snes->cpu->i = true; snes->cpu->nmiWanted = false; snes->cpu->irqWanted = false;

    Snap baseline;
    snap_take(&baseline, snes);

    fprintf(stderr, "LoadPlayerGfx asm vs C : %d trials\n", n_trials);

    int fails = 0;
    for (int trial = 0; trial < n_trials; trial++) {
        snap_restore(&baseline, snes);

        // Randomise inputs.
        snes->ram[0x00CC] = (uint8_t)host_rng();
        snes->ram[0x1001] = (uint8_t)host_rng();
        snes->ram[0x1003] = (uint8_t)host_rng();


        // Pre-call snapshot for replaying C with the exact same state.
        Snap pre;
        snap_take(&pre, snes);

        // Run ASM
        run_asm(snes);
        uint8_t out_asm = snes->ram[0x004B];

        // Restore and run C
        snap_restore(&pre, snes);
        LoadPlayerGfx_c(snes);
        uint8_t out_c = snes->ram[0x004B];

        bool ok = (out_asm == out_c);
        if (!ok) {
            printf("trial %4d : asm=%u c=%u  FAIL\n", trial, out_asm, out_c);
            fails++;
        }
    }

    printf("\n=== summary === trials: %d, fails: %d\n", n_trials, fails);
    free(rom);
    return fails == 0 ? 0 : 1;
}
