// AUTO-GENERATED parity spike for field::UpdateBG2Scroll @ $00:F533.
// Generated by translator/generate_spike.py from port/field/UpdateBG2Scroll.c.
// DO NOT EDIT BY HAND — regenerate via:
//   python translator/generate_spike.py port/field/UpdateBG2Scroll.c

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdint.h>
#include <stdbool.h>

#include "snes.h"
#include "cpu.h"

#define TARGET_ADDR_24 0x00F533u

// Forward declarations for helpers defined later in this TU but used by the
// inlined LLM translation below.
static void run_emulated_func(Snes *snes, uint32_t pc24);
static inline uint16_t read16(const uint8_t *ram, int addr);
static inline void write16(uint8_t *ram, int addr, uint16_t v);

// ---------------------------------------------------------------------------
// Auto-emitted *_emu delegation helpers (one per stub referenced by the
// translation but not defined in port/field/UpdateBG2Scroll.c).
// ---------------------------------------------------------------------------

// (no auto-emitted helpers)

// ---------------------------------------------------------------------------
// LLM-translated C function (verbatim copy from port/field/UpdateBG2Scroll.c)
// ---------------------------------------------------------------------------

#include "snes/snes.h"

// Entry mode: A 8-bit (mf=1), X/Y 16-bit (xf=0), DB=0, DP=0
// Logic: Updates BG2 scroll values ($5E, $60) based on movement flags and rates.
// Handles two modes: "continuous scroll" (additive) and "parallax scroll" (multiplier).
void UpdateBG2Scroll_c(Snes *snes) {
    uint8_t *ram = snes->ram;

    if (ram[0xC9] == 0) return;             // lda $c9 / bne @f545
    if (ram[0x1700] != 0x03) return;       // lda $1700 / cmp #$03 / bne @f545
    if ((ram[0x0FE4] & 0xC0) == 0) return; // lda $0fe4 / and #$c0 / bne @f546

    uint8_t flags = ram[0x0FE4];
    if ((flags & 0x06) != 0) {             // and #$06 / bne @f593
        // --- Parallax Scroll ---
        if ((flags & 0x04) != 0) {         // and #$04 / beq @f5c7
            uint16_t val = read16(ram, 0x5A);
            write16(ram, 0x5E, val);      // ldx $5a / stx $5e

            uint8_t dir = flags & 0xC0;
            if (dir == 0x80) {            // cmp #$80 / beq @f5b6
                // No shift
            } else if (dir == 0x40) {    // cmp #$40 / beq @f5b2
                uint16_t v = read16(ram, 0x5E);
                v = (uint16_t)((v >> 1) | ((v & 1) << 15)); // lsr $5f / ror $5e (Note: $5E is LE)
                // Correct 65816 16-bit LSR/ROR on $5E-$5F:
                uint16_t low = ram[0x5E];
                uint16_t high = ram[0x5F];
                uint16_t combined = low | (high << 8);
                combined = (combined >> 1); // Simplified for logic; actually modifies memory
                write16(ram, 0x5E, combined);
            } else {
                uint16_t v = read16(ram, 0x5E);
                v = (uint16_t)((v << 1)); // asl $5e / rol $5f
                write16(ram, 0x5E, v);
            }
            
            if ((flags & 0x06) == 0x04) {  // cmp #$04 / bne @f5c7
                write16(ram, 0x60, 0);     // ldx #$0000 / stx $60
            }
        }

        if ((flags & 0x02) != 0) {         // and #$02 / beq @f5f8
            uint16_t val = read16(ram, 0x5C);
            write16(ram, 0x60, val);      // ldx $5c / stx $60

            uint8_t dir = flags & 0xC0;
            if (dir == 0x80) {
                // No shift
            } else if (dir == 0x40) {
                uint16_t v = read16(ram, 0x60);
                v = (v >> 1); // lsr $61 / ror $60
                write16(ram, 0x60, v);
            } else {
                uint16_t v = read16(ram, 0x60);
                v = (v << 1); // asl $60 / rol $61
                write16(ram, 0x60, v);
            }

            if ((flags & 0x06) == 0x02) {  // cmp #$02 / bne @f5f8
                write16(ram, 0x5E, 0);     // ldx #$0000 / stx $5e
            }
        }
        return;
    }

    // --- Continuous Scroll ---
    uint8_t scroll_rate_idx = (flags & 0xC0) >> 6; // lsr6 / tay
    // Note: BG2ScrollRateTbl is usually a table of masks or values. 
    // Assuming it's a byte table at a known address (need to check bridge for actual addr)
    // For this translation, I will use the table name directly as a variable/array.
    extern const uint8_t BG2ScrollRateTbl[]; 
    if ((ram[0x7A] & BG2ScrollRateTbl[scroll_rate_idx]) != 0) { 
        goto continuous_calc_done; // bne @f57b
    }

    uint8_t move_rate_idx = (flags & 0x30) >> 3; // lsr3 / tay
    extern const uint16_t HorzMoveRateTbl[]; 
    extern const uint16_t VertMoveRateTbl[];

    uint16_t h_move = read16(ram, 0x66);
    h_move += HorzMoveRateTbl[move_rate_idx]; // adc
    write16(ram, 0x66, h_move);

    uint16_t v_move = read16(ram, 0x68);
    v_move += VertMoveRateTbl[move_rate_idx]; // adc
    write16(ram, 0x68, v_move);

continuous_calc_done:
    uint16_t base_x = read16(ram, 0x5A);
    uint16_t add_x = read16(ram, 0x66);
    write16(ram, 0x5E, base_x + add_x); // adc / sta $5e

    uint16_t base_y = read16(ram, 0x5C);
    uint16_t add_y = read16(ram, 0x68);
    write16(ram, 0x60, base_y + add_y); // adc / sta $60
}


// ---------------------------------------------------------------------------
// Common helpers (same shape as the manual M2/M3/M4 spikes)
// ---------------------------------------------------------------------------

static uint8_t *read_file(const char *path, size_t *out_len) {
    FILE *f = fopen(path, "rb");
    if (!f) { perror(path); return NULL; }
    fseek(f, 0, SEEK_END); long sz = ftell(f); fseek(f, 0, SEEK_SET);
    uint8_t *buf = malloc(sz);
    if (fread(buf, 1, sz, f) != (size_t)sz) { free(buf); fclose(f); return NULL; }
    fclose(f); *out_len = sz; return buf;
}

static inline uint32_t stack_addr(const Cpu *cpu) {
    return cpu->e ? (0x0100u | (cpu->sp & 0xFFu)) : cpu->sp;
}

static void run_emulated_func(Snes *snes, uint32_t pc24) {
    Cpu *cpu = snes->cpu;
    uint16_t sp_save = cpu->sp;
    snes->ram[stack_addr(cpu)] = 0x12; cpu->sp--;
    snes->ram[stack_addr(cpu)] = 0x34; cpu->sp--;
    cpu->k = (uint8_t)(pc24 >> 16);
    cpu->pc = (uint16_t)(pc24 & 0xFFFF);
    long max_ops = 200000;
    while (cpu->sp != sp_save && max_ops-- > 0) {
        cpu_runOpcode(cpu);
        if (cpu->waiting || cpu->stopped) break;
    }
}

typedef struct {
    uint8_t ram[0x20000];
    uint16_t a, x, y, sp, pc, dp;
    uint8_t k, db;
    bool c, z, v, n, i, d, xf, mf, e;
    bool waiting, stopped, irqWanted, nmiWanted;
} Snap;

static void snap_take(Snap *s, Snes *snes) {
    memcpy(s->ram, snes->ram, sizeof(s->ram));
    Cpu *c = snes->cpu;
    s->a=c->a; s->x=c->x; s->y=c->y; s->sp=c->sp; s->pc=c->pc; s->dp=c->dp;
    s->k=c->k; s->db=c->db;
    s->c=c->c; s->z=c->z; s->v=c->v; s->n=c->n;
    s->i=c->i; s->d=c->d; s->xf=c->xf; s->mf=c->mf; s->e=c->e;
    s->waiting=c->waiting; s->stopped=c->stopped;
    s->irqWanted=c->irqWanted; s->nmiWanted=c->nmiWanted;
}
static void snap_restore(const Snap *s, Snes *snes) {
    memcpy(snes->ram, s->ram, sizeof(s->ram));
    Cpu *c = snes->cpu;
    c->a=s->a; c->x=s->x; c->y=s->y; c->sp=s->sp; c->pc=s->pc; c->dp=s->dp;
    c->k=s->k; c->db=s->db;
    c->c=s->c; c->z=s->z; c->v=s->v; c->n=s->n;
    c->i=s->i; c->d=s->d; c->xf=s->xf; c->mf=s->mf; c->e=s->e;
    c->waiting=s->waiting; c->stopped=s->stopped;
    c->irqWanted=s->irqWanted; c->nmiWanted=s->nmiWanted;
}

static inline uint16_t read16(const uint8_t *ram, int addr) {
    return (uint16_t)(ram[addr] | (ram[addr + 1] << 8));
}
static inline void write16(uint8_t *ram, int addr, uint16_t v) {
    ram[addr] = v & 0xFF; ram[addr + 1] = (v >> 8) & 0xFF;
}

// ---------------------------------------------------------------------------
// asm wrapper from the contract
// ---------------------------------------------------------------------------

static void run_asm(Snes *snes) {
    Cpu *c = snes->cpu;
    c->dp = 0;
    c->db = 0x7E;
    c->mf = true;
    c->xf = false;
    c->a = 0; c->x = 0; c->y = 0;
    // no register inputs
    // no entry flags
    run_emulated_func(snes, TARGET_ADDR_24);
}

// ---------------------------------------------------------------------------
// Host PRNG
// ---------------------------------------------------------------------------

static uint32_t host_rng_state = 0xC0FFEEu;
static uint32_t host_rng(void) {
    uint32_t x = host_rng_state;
    x ^= x << 13; x ^= x >> 17; x ^= x << 5;
    host_rng_state = x; return x;
}

// ---------------------------------------------------------------------------
// Trial driver
// ---------------------------------------------------------------------------

int main(int argc, char **argv) {
    if (argc < 2) {
        fprintf(stderr, "usage: %s <rom.sfc> [n_trials]\n", argv[0]);
        return 1;
    }
    int n_trials = (argc >= 3) ? atoi(argv[2]) : 1000;

    size_t rom_len = 0;
    uint8_t *rom = read_file(argv[1], &rom_len);
    if (!rom) return 2;

    Snes *snes = snes_init();
    if (!snes_loadRom(snes, rom, rom_len)) { fprintf(stderr, "loadRom fail\n"); return 3; }
    snes_reset(snes, true);
    for (int i = 0; i < 60; i++) snes_runFrame(snes);
    snes->cpu->i = true; snes->cpu->nmiWanted = false; snes->cpu->irqWanted = false;

    Snap baseline;
    snap_take(&baseline, snes);

    fprintf(stderr, "UpdateBG2Scroll asm vs C : %d trials\n", n_trials);

    int fails = 0;
    for (int trial = 0; trial < n_trials; trial++) {
        snap_restore(&baseline, snes);

        // Randomise inputs.
        snes->ram[0x00C9] = (uint8_t)host_rng();
        snes->ram[0x1700] = (uint8_t)host_rng();
        snes->ram[0x0FE4] = (uint8_t)host_rng();
        snes->ram[0x007A] = (uint8_t)host_rng();
        write16(snes->ram, 0x005A, (uint16_t)host_rng());
        write16(snes->ram, 0x0066, (uint16_t)host_rng());
        write16(snes->ram, 0x005C, (uint16_t)host_rng());
        write16(snes->ram, 0x0068, (uint16_t)host_rng());


        // Pre-call snapshot for replaying C with the exact same state.
        Snap pre;
        snap_take(&pre, snes);

        // Run ASM
        run_asm(snes);
        uint16_t out_asm = read16(snes->ram, 0x005E);

        // Restore and run C
        snap_restore(&pre, snes);
        UpdateBG2Scroll_c(snes);
        uint16_t out_c = read16(snes->ram, 0x005E);

        bool ok = (out_asm == out_c);
        if (!ok) {
            printf("trial %4d : asm=%u c=%u  FAIL\n", trial, out_asm, out_c);
            fails++;
        }
    }

    printf("\n=== summary === trials: %d, fails: %d\n", n_trials, fails);
    free(rom);
    return fails == 0 ? 0 : 1;
}
