// AUTO-GENERATED parity spike for field::UpdateZoomHDMA @ $00:C163.
// Generated by translator/generate_spike.py from port/field/UpdateZoomHDMA.c.
// DO NOT EDIT BY HAND — regenerate via:
//   python translator/generate_spike.py port/field/UpdateZoomHDMA.c

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdint.h>
#include <stdbool.h>

#include "snes.h"
#include "cpu.h"

#define TARGET_ADDR_24 0x00C163u

// Forward declarations for helpers defined later in this TU but used by the
// inlined LLM translation below.
static void run_emulated_func(Snes *snes, uint32_t pc24);
static inline uint16_t read16(const uint8_t *ram, int addr);
static inline void write16(uint8_t *ram, int addr, uint16_t v);

// ---------------------------------------------------------------------------
// Auto-emitted *_emu delegation helpers (one per stub referenced by the
// translation but not defined in port/field/UpdateZoomHDMA.c).
// ---------------------------------------------------------------------------

// (no auto-emitted helpers)

// ---------------------------------------------------------------------------
// LLM-translated C function (verbatim copy from port/field/UpdateZoomHDMA.c)
// ---------------------------------------------------------------------------

#include "snes/snes.h"

// Entry mode: A 8-bit (mf=1), X 16-bit (xf=0), DB=$C1, DP=0
// Logic:
//   1. If ram[0x1700] == 3 (World Map), exit immediately.
//   2. Clear matrix elements hM7B/hM7C.
//   3. Setup Zoom HDMA data in RAM ($7F5A00 range).
//   4. Calculate offset based on ram[0xAD] (zoom level), 
//      diverging if ram[0x1704] == 0x06 (Big Whale event).
//   5. Trigger HDMA via registers $4340-$4357.
static void UpdateZoomHDMA_c(Snes *snes) {
    uint8_t *ram = snes->ram;

    // Check if on world map
    if (ram[0x1700] == 3) { // lda $1700 / cmp #3 / bne @c16b (taken if != 3)
        return;
    }

    // The ASM has a bug or quirk: it branches to @c16b if A != 3.
    // If A == 3, it hits 'rtl'. If A != 3, it proceeds to HDMA setup.
    // Wait: the ASM says: bne @c16b ; return if not on world map.
    // This is a contradiction in the ASM comment. 
    // "bne @c16b" means "if A != 3, go to @c16b".
    // If A == 3, it falls through to 'rtl'.
    // Therefore: if (ram[0x1700] == 3) return;
    
    // Clear off-diagonal matrix elements (hM7B, hM7C are offsets/labels)
    // Assuming these are defined in the mapping, using placeholders for labels
    // based on the stz sequence.
    ram[0x211A] = 0; // hM7B lo
    ram[0x211B] = 0; // hM7B hi
    ram[0x211B] = 0; // hM7C lo (overlap/sequential)
    ram[0x211C] = 0; // hM7C hi
    // Note: Since labels aren't provided, I map them to typical HDMA matrix locations
    // but strictly follow the 'stz' count.

    ram[0x7F5A00] = 0xF0; // 224 scanlines
    ram[0x7F5A03] = 0xF0;

    if (ram[0x1704] == 0x06) { // Big Whale
        uint8_t val = ram[0xAD];
        val = (uint8_t)(val - 0x10); // sec / sbc #$10
        val &= 0xFE;                // and #$fe
        val = (uint8_t)(val + 0x22); // clc / adc #$22
        
        ram[0x7F5A02] = val;
        ram[0x7F5A05] = val;
    } else { // Not Big Whale
        uint8_t val = ram[0xAD];
        val = (uint8_t)(val - 0x10); // sec / sbc #$10
        val = (uint8_t)(val << 1);   // asl (Pitfall 7: truncate to 8-bit)
        val = (uint8_t)(val + 0x00); // clc / adc #$00
        
        ram[0x7F5A02] = val;
        ram[0x7F5A05] = val;
    }

    ram[0x7F5A01] = 0x00;
    ram[0x7F5A04] = 0xE0;
    ram[0x7F5A06] = 0x80; // HDMA terminator

    // HDMA Control Registers (Standard SNES HW registers mapped into RAM space for this project)
    // hHDMAEN is typically a bitmask in RAM or HW
    ram[0x2100] = 0; // Placeholder for hHDMAEN stz

    ram[0x4340] = 0x42;
    ram[0x4350] = 0x42;
    
    // hM7A low byte
    ram[0x4341] = 0x1B; // <hM7A ($211B)
    ram[0x4351] = 0x1E; // <hM7D ($211E)
    
    ram[0x4342] = 0x00; // low byte of $5A00
    ram[0x4343] = 0x5A; // high byte of $5A00 (stx $4342 implies 16-bit X)
    ram[0x4352] = 0x00;
    ram[0x4353] = 0x5A;

    ram[0x4344] = 0x7F;
    ram[0x4354] = 0x7F;
    ram[0x4347] = 0x7F;
    ram[0x4357] = 0x7F;
}


// ---------------------------------------------------------------------------
// Common helpers (same shape as the manual M2/M3/M4 spikes)
// ---------------------------------------------------------------------------

static uint8_t *read_file(const char *path, size_t *out_len) {
    FILE *f = fopen(path, "rb");
    if (!f) { perror(path); return NULL; }
    fseek(f, 0, SEEK_END); long sz = ftell(f); fseek(f, 0, SEEK_SET);
    uint8_t *buf = malloc(sz);
    if (fread(buf, 1, sz, f) != (size_t)sz) { free(buf); fclose(f); return NULL; }
    fclose(f); *out_len = sz; return buf;
}

static inline uint32_t stack_addr(const Cpu *cpu) {
    return cpu->e ? (0x0100u | (cpu->sp & 0xFFu)) : cpu->sp;
}

static void run_emulated_func(Snes *snes, uint32_t pc24) {
    Cpu *cpu = snes->cpu;
    uint16_t sp_save = cpu->sp;
    snes->ram[stack_addr(cpu)] = 0x12; cpu->sp--;
    snes->ram[stack_addr(cpu)] = 0x34; cpu->sp--;
    cpu->k = (uint8_t)(pc24 >> 16);
    cpu->pc = (uint16_t)(pc24 & 0xFFFF);
    long max_ops = 200000;
    while (cpu->sp != sp_save && max_ops-- > 0) {
        cpu_runOpcode(cpu);
        if (cpu->waiting || cpu->stopped) break;
    }
}

typedef struct {
    uint8_t ram[0x20000];
    uint16_t a, x, y, sp, pc, dp;
    uint8_t k, db;
    bool c, z, v, n, i, d, xf, mf, e;
    bool waiting, stopped, irqWanted, nmiWanted;
} Snap;

static void snap_take(Snap *s, Snes *snes) {
    memcpy(s->ram, snes->ram, sizeof(s->ram));
    Cpu *c = snes->cpu;
    s->a=c->a; s->x=c->x; s->y=c->y; s->sp=c->sp; s->pc=c->pc; s->dp=c->dp;
    s->k=c->k; s->db=c->db;
    s->c=c->c; s->z=c->z; s->v=c->v; s->n=c->n;
    s->i=c->i; s->d=c->d; s->xf=c->xf; s->mf=c->mf; s->e=c->e;
    s->waiting=c->waiting; s->stopped=c->stopped;
    s->irqWanted=c->irqWanted; s->nmiWanted=c->nmiWanted;
}
static void snap_restore(const Snap *s, Snes *snes) {
    memcpy(snes->ram, s->ram, sizeof(s->ram));
    Cpu *c = snes->cpu;
    c->a=s->a; c->x=s->x; c->y=s->y; c->sp=s->sp; c->pc=s->pc; c->dp=s->dp;
    c->k=s->k; c->db=s->db;
    c->c=s->c; c->z=s->z; c->v=s->v; c->n=s->n;
    c->i=s->i; c->d=s->d; c->xf=s->xf; c->mf=s->mf; c->e=s->e;
    c->waiting=s->waiting; c->stopped=s->stopped;
    c->irqWanted=s->irqWanted; c->nmiWanted=s->nmiWanted;
}

static inline uint16_t read16(const uint8_t *ram, int addr) {
    return (uint16_t)(ram[addr] | (ram[addr + 1] << 8));
}
static inline void write16(uint8_t *ram, int addr, uint16_t v) {
    ram[addr] = v & 0xFF; ram[addr + 1] = (v >> 8) & 0xFF;
}

// ---------------------------------------------------------------------------
// asm wrapper from the contract
// ---------------------------------------------------------------------------

static void run_asm(Snes *snes) {
    Cpu *c = snes->cpu;
    c->dp = 0;
    c->db = 0x7E;
    c->mf = true;
    c->xf = false;
    c->a = 0; c->x = 0; c->y = 0;
    // no register inputs
    // no entry flags
    run_emulated_func(snes, TARGET_ADDR_24);
}

// ---------------------------------------------------------------------------
// Host PRNG
// ---------------------------------------------------------------------------

static uint32_t host_rng_state = 0xC0FFEEu;
static uint32_t host_rng(void) {
    uint32_t x = host_rng_state;
    x ^= x << 13; x ^= x >> 17; x ^= x << 5;
    host_rng_state = x; return x;
}

// ---------------------------------------------------------------------------
// Trial driver
// ---------------------------------------------------------------------------

int main(int argc, char **argv) {
    if (argc < 2) {
        fprintf(stderr, "usage: %s <rom.sfc> [n_trials]\n", argv[0]);
        return 1;
    }
    int n_trials = (argc >= 3) ? atoi(argv[2]) : 1000;

    size_t rom_len = 0;
    uint8_t *rom = read_file(argv[1], &rom_len);
    if (!rom) return 2;

    Snes *snes = snes_init();
    if (!snes_loadRom(snes, rom, rom_len)) { fprintf(stderr, "loadRom fail\n"); return 3; }
    snes_reset(snes, true);
    for (int i = 0; i < 60; i++) snes_runFrame(snes);
    snes->cpu->i = true; snes->cpu->nmiWanted = false; snes->cpu->irqWanted = false;

    Snap baseline;
    snap_take(&baseline, snes);

    fprintf(stderr, "UpdateZoomHDMA asm vs C : %d trials\n", n_trials);

    int fails = 0;
    for (int trial = 0; trial < n_trials; trial++) {
        snap_restore(&baseline, snes);

        // Randomise inputs.
        snes->ram[0x1700] = (uint8_t)host_rng();
        snes->ram[0x1704] = (uint8_t)host_rng();
        snes->ram[0x00AD] = (uint8_t)host_rng();


        // Pre-call snapshot for replaying C with the exact same state.
        Snap pre;
        snap_take(&pre, snes);

        // Run ASM
        run_asm(snes);
        uint8_t out_asm = snes->ram[0x7F5A00];

        // Restore and run C
        snap_restore(&pre, snes);
        UpdateZoomHDMA_c(snes);
        uint8_t out_c = snes->ram[0x7F5A00];

        bool ok = (out_asm == out_c);
        if (!ok) {
            printf("trial %4d : asm=%u c=%u  FAIL\n", trial, out_asm, out_c);
            fails++;
        }
    }

    printf("\n=== summary === trials: %d, fails: %d\n", n_trials, fails);
    free(rom);
    return fails == 0 ? 0 : 1;
}
