// AUTO-GENERATED parity spike for field::CheckMenu @ $00:81F4.
// Generated by translator/generate_spike.py from port/field/CheckMenu.c.
// DO NOT EDIT BY HAND — regenerate via:
//   python translator/generate_spike.py port/field/CheckMenu.c

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdint.h>
#include <stdbool.h>

#include "snes.h"
#include "cpu.h"

#define TARGET_ADDR_24 0x0081F4u

// Forward declarations for helpers defined later in this TU but used by the
// inlined LLM translation below.
static void run_emulated_func(Snes *snes, uint32_t pc24);
static inline uint16_t read16(const uint8_t *ram, int addr);
static inline void write16(uint8_t *ram, int addr, uint16_t v);

// ---------------------------------------------------------------------------
// Auto-emitted *_emu delegation helpers (one per stub referenced by the
// translation but not defined in port/field/CheckMenu.c).
// ---------------------------------------------------------------------------

// Auto-emitted delegation wrapper for FadeOutMenu @ $008A08 (referenced as fade_out_menu_emu)
static uint16_t fade_out_menu_emu(Snes *snes) {
    Cpu *c = snes->cpu;
    uint16_t saved_a=c->a, saved_x=c->x, saved_y=c->y, saved_sp=c->sp;
    uint16_t saved_pc=c->pc, saved_dp=c->dp;
    uint8_t saved_k=c->k, saved_db=c->db;
    bool saved_mf=c->mf, saved_xf=c->xf;
    c->dp = 0; c->db = 0x7E;
    c->mf = true; c->xf = false;
    run_emulated_func(snes, 0x008A08u);
    uint16_t result = c->a;
    c->x=saved_x; c->y=saved_y;
    c->sp=saved_sp; c->pc=saved_pc; c->dp=saved_dp;
    c->k=saved_k; c->db=saved_db;
    c->mf=saved_mf; c->xf=saved_xf;
    c->a = saved_a;
    return result;
}

// Auto-emitted delegation wrapper for FadeInMenu @ $008A11 (referenced as fade_in_menu_emu)
static uint16_t fade_in_menu_emu(Snes *snes) {
    Cpu *c = snes->cpu;
    uint16_t saved_a=c->a, saved_x=c->x, saved_y=c->y, saved_sp=c->sp;
    uint16_t saved_pc=c->pc, saved_dp=c->dp;
    uint8_t saved_k=c->k, saved_db=c->db;
    bool saved_mf=c->mf, saved_xf=c->xf;
    c->dp = 0; c->db = 0x7E;
    c->mf = true; c->xf = false;
    run_emulated_func(snes, 0x008A11u);
    uint16_t result = c->a;
    c->x=saved_x; c->y=saved_y;
    c->sp=saved_sp; c->pc=saved_pc; c->dp=saved_dp;
    c->k=saved_k; c->db=saved_db;
    c->mf=saved_mf; c->xf=saved_xf;
    c->a = saved_a;
    return result;
}

// Auto-emitted delegation wrapper for PlayMapSong @ $008D5D (referenced as play_map_song_emu)
static uint16_t play_map_song_emu(Snes *snes) {
    Cpu *c = snes->cpu;
    uint16_t saved_a=c->a, saved_x=c->x, saved_y=c->y, saved_sp=c->sp;
    uint16_t saved_pc=c->pc, saved_dp=c->dp;
    uint8_t saved_k=c->k, saved_db=c->db;
    bool saved_mf=c->mf, saved_xf=c->xf;
    c->dp = 0; c->db = 0x7E;
    c->mf = true; c->xf = false;
    run_emulated_func(snes, 0x008D5Du);
    uint16_t result = c->a;
    c->x=saved_x; c->y=saved_y;
    c->sp=saved_sp; c->pc=saved_pc; c->dp=saved_dp;
    c->k=saved_k; c->db=saved_db;
    c->mf=saved_mf; c->xf=saved_xf;
    c->a = saved_a;
    return result;
}

// Auto-emitted delegation wrapper for ExecEvent @ $00E1EB (referenced as exec_event_emu)
static uint16_t exec_event_emu(Snes *snes) {
    Cpu *c = snes->cpu;
    uint16_t saved_a=c->a, saved_x=c->x, saved_y=c->y, saved_sp=c->sp;
    uint16_t saved_pc=c->pc, saved_dp=c->dp;
    uint8_t saved_k=c->k, saved_db=c->db;
    bool saved_mf=c->mf, saved_xf=c->xf;
    c->dp = 0; c->db = 0x7E;
    c->mf = true; c->xf = false;
    run_emulated_func(snes, 0x00E1EBu);
    uint16_t result = c->a;
    c->x=saved_x; c->y=saved_y;
    c->sp=saved_sp; c->pc=saved_pc; c->dp=saved_dp;
    c->k=saved_k; c->db=saved_db;
    c->mf=saved_mf; c->xf=saved_xf;
    c->a = saved_a;
    return result;
}


// ---------------------------------------------------------------------------
// LLM-translated C function (verbatim copy from port/field/CheckMenu.c)
// ---------------------------------------------------------------------------

#include "snes/snes.h"

// Entry mode: A 8-bit (mf=1), X 16-bit (xf=0), DB=$81, DP=0
// This routine checks for the X button press to trigger the menu.
// It handles menu state transitions, specific map-based menu behaviors (tent/cabin),
// and triggers the corresponding menu events.
void CheckMenu_c(Snes *snes) {
    uint8_t *ram = snes->ram;

    if (ram[0xD5] == 0) {                   // lda $d5 / bne @81f9 (inverted)
        return;
    }

    if (ram[0x50] != 0) {                  // lda $50 / beq @8200
        return;
    }

    // Check if X button is pressed (JOY_X is usually 0x40 or 0x80, checked via AND)
    // ASM: lda $02 / and #JOY_X / bne @8209
    if ((ram[0x02] & 0x40) == 0) {         // Assuming JOY_X = 0x40 based on common SNES layouts
        return;
    }

    ram[0x50] = 0x01;                      // sta $50 (Mark X processed)
    
    uint8_t menu_type = ram[0x1700];
    uint8_t target_val;
    if (menu_type == 0x03) {              // cmp #$03 / bne @821e
        target_val = (ram[0x0FDB] & 0x30) | 0x80;
    } else {
        if (ram[0x1704] != 0) {            // lda $1704 / bne @8228
            target_val = ram[0x1704];      // (Wait, ASM says lda $1704 / bne @8228 / lda #$40)
            // Correction based on ASM: 
            // @821e: lda $1704 / bne @8228 / lda #$40 / jmp @822a
            // @8228: lda #$00
            // This means if $1704 is 0, target is 0x40. If $1704 != 0, target is 0x00.
            target_val = 0x00; 
        } else {
            target_val = 0x40;
        }
    }
    ram[0x1A04] = target_val;             // sta $1a04

    fade_out_menu_emu(snes);               // jsr FadeOutMenu
    main_menu_ext_emu(snes);              // jsl MainMenu_ext

    if (ram[0x1700] == 0x03) {            // lda $1700 / cmp #$03 / bne @8241
        write16(ram, 0x0CDD, read16(ram, 0x16AA)); // ldx $16aa / stx $0cdd
    }

    fade_in_menu_emu(snes);                // jsr FadeInMenu

    uint8_t event = ram[0x1A03];
    if (event == 0) {                     // lda $1a03 / beq @828f
        return;
    }

    ram[0xB1] = 0x01;                      // sta $b1
    ram[0xAB] = 0;                         // stz $ab
    
    uint8_t exec_val;
    if (event < 0x03) {                   // cmp #$03 / bcs @825f (inverted)
        exec_val = (uint8_t)(event + 0x76); // clc / adc #$76 (Pitfall 7)
    } else if (event == 0x03) {
        exec_val = 0x87;
    } else if (event == 0x04) {
        exec_val = 0x86;
    } else if (event == 0x05) {
        exec_val = 0xFB;
    } else if (event == 0x06) {
        ram[0xC0] = 0x01;                  // sta $c0
        exec_val = 0x01;                  // This is actually a jump to @828a if event=0x06? 
                                          // No, ASM: lda #$01 / sta $c0 / jmp @828a
                                          // If event == 0x06, it skips ExecEvent.
        ram[0xB1] = 0;                     // stz $b1 (from @828a)
        play_map_song_emu(snes);          // jsr PlayMapSong
        return;
    } else {
        exec_val = 0xDB;
    }

    ram[0xB1] = exec_val;                 // (The ASM uses A to pass to ExecEvent via ram[$b1])
    // Actually, the ASM sequence is: lda #val / jmp @8287 / jsr ExecEvent
    // ExecEvent likely reads its operand from A or a specific RAM location.
    // Based on the logic, A is the value passed.
    
    // To faithfully emulate the JSR, we set the register and call the emu.
    snes->cpu->a = exec_val;
    exec_event_emu(snes);                  // jsr ExecEvent

    ram[0xB1] = 0;                         // stz $b1
    play_map_song_emu(snes);               // jsr PlayMapSong
}


// ---------------------------------------------------------------------------
// Common helpers (same shape as the manual M2/M3/M4 spikes)
// ---------------------------------------------------------------------------

static uint8_t *read_file(const char *path, size_t *out_len) {
    FILE *f = fopen(path, "rb");
    if (!f) { perror(path); return NULL; }
    fseek(f, 0, SEEK_END); long sz = ftell(f); fseek(f, 0, SEEK_SET);
    uint8_t *buf = malloc(sz);
    if (fread(buf, 1, sz, f) != (size_t)sz) { free(buf); fclose(f); return NULL; }
    fclose(f); *out_len = sz; return buf;
}

static inline uint32_t stack_addr(const Cpu *cpu) {
    return cpu->e ? (0x0100u | (cpu->sp & 0xFFu)) : cpu->sp;
}

static void run_emulated_func(Snes *snes, uint32_t pc24) {
    Cpu *cpu = snes->cpu;
    uint16_t sp_save = cpu->sp;
    snes->ram[stack_addr(cpu)] = 0x12; cpu->sp--;
    snes->ram[stack_addr(cpu)] = 0x34; cpu->sp--;
    cpu->k = (uint8_t)(pc24 >> 16);
    cpu->pc = (uint16_t)(pc24 & 0xFFFF);
    long max_ops = 200000;
    while (cpu->sp != sp_save && max_ops-- > 0) {
        cpu_runOpcode(cpu);
        if (cpu->waiting || cpu->stopped) break;
    }
}

typedef struct {
    uint8_t ram[0x20000];
    uint16_t a, x, y, sp, pc, dp;
    uint8_t k, db;
    bool c, z, v, n, i, d, xf, mf, e;
    bool waiting, stopped, irqWanted, nmiWanted;
} Snap;

static void snap_take(Snap *s, Snes *snes) {
    memcpy(s->ram, snes->ram, sizeof(s->ram));
    Cpu *c = snes->cpu;
    s->a=c->a; s->x=c->x; s->y=c->y; s->sp=c->sp; s->pc=c->pc; s->dp=c->dp;
    s->k=c->k; s->db=c->db;
    s->c=c->c; s->z=c->z; s->v=c->v; s->n=c->n;
    s->i=c->i; s->d=c->d; s->xf=c->xf; s->mf=c->mf; s->e=c->e;
    s->waiting=c->waiting; s->stopped=c->stopped;
    s->irqWanted=c->irqWanted; s->nmiWanted=c->nmiWanted;
}
static void snap_restore(const Snap *s, Snes *snes) {
    memcpy(snes->ram, s->ram, sizeof(s->ram));
    Cpu *c = snes->cpu;
    c->a=s->a; c->x=s->x; c->y=s->y; c->sp=s->sp; c->pc=s->pc; c->dp=s->dp;
    c->k=s->k; c->db=s->db;
    c->c=s->c; c->z=s->z; c->v=s->v; c->n=s->n;
    c->i=s->i; c->d=s->d; c->xf=s->xf; c->mf=s->mf; c->e=s->e;
    c->waiting=s->waiting; c->stopped=s->stopped;
    c->irqWanted=s->irqWanted; c->nmiWanted=s->nmiWanted;
}

static inline uint16_t read16(const uint8_t *ram, int addr) {
    return (uint16_t)(ram[addr] | (ram[addr + 1] << 8));
}
static inline void write16(uint8_t *ram, int addr, uint16_t v) {
    ram[addr] = v & 0xFF; ram[addr + 1] = (v >> 8) & 0xFF;
}

// ---------------------------------------------------------------------------
// asm wrapper from the contract
// ---------------------------------------------------------------------------

static void run_asm(Snes *snes) {
    Cpu *c = snes->cpu;
    c->dp = 0;
    c->db = 0x7E;
    c->mf = true;
    c->xf = false;
    c->a = 0; c->x = 0; c->y = 0;
    // no register inputs
    // no entry flags
    run_emulated_func(snes, TARGET_ADDR_24);
}

// ---------------------------------------------------------------------------
// Host PRNG
// ---------------------------------------------------------------------------

static uint32_t host_rng_state = 0xC0FFEEu;
static uint32_t host_rng(void) {
    uint32_t x = host_rng_state;
    x ^= x << 13; x ^= x >> 17; x ^= x << 5;
    host_rng_state = x; return x;
}

// ---------------------------------------------------------------------------
// Trial driver
// ---------------------------------------------------------------------------

int main(int argc, char **argv) {
    if (argc < 2) {
        fprintf(stderr, "usage: %s <rom.sfc> [n_trials]\n", argv[0]);
        return 1;
    }
    int n_trials = (argc >= 3) ? atoi(argv[2]) : 1000;

    size_t rom_len = 0;
    uint8_t *rom = read_file(argv[1], &rom_len);
    if (!rom) return 2;

    Snes *snes = snes_init();
    if (!snes_loadRom(snes, rom, rom_len)) { fprintf(stderr, "loadRom fail\n"); return 3; }
    snes_reset(snes, true);
    for (int i = 0; i < 60; i++) snes_runFrame(snes);
    snes->cpu->i = true; snes->cpu->nmiWanted = false; snes->cpu->irqWanted = false;

    Snap baseline;
    snap_take(&baseline, snes);

    fprintf(stderr, "CheckMenu asm vs C : %d trials\n", n_trials);

    int fails = 0;
    for (int trial = 0; trial < n_trials; trial++) {
        snap_restore(&baseline, snes);

        // Randomise inputs.
        snes->ram[0x00D5] = (uint8_t)host_rng();
        snes->ram[0x0050] = (uint8_t)host_rng();
        snes->ram[0x0002] = (uint8_t)host_rng();
        snes->ram[0x1700] = (uint8_t)host_rng();
        snes->ram[0x1704] = (uint8_t)host_rng();
        snes->ram[0x0FDB] = (uint8_t)host_rng();
        snes->ram[0x1A03] = (uint8_t)host_rng();
        write16(snes->ram, 0x16AA, (uint16_t)host_rng());


        // Pre-call snapshot for replaying C with the exact same state.
        Snap pre;
        snap_take(&pre, snes);

        // Run ASM
        run_asm(snes);
        uint8_t out_asm = snes->ram[0x1A04];

        // Restore and run C
        snap_restore(&pre, snes);
        CheckMenu_c(snes);
        uint8_t out_c = snes->ram[0x1A04];

        bool ok = (out_asm == out_c);
        if (!ok) {
            printf("trial %4d : asm=%u c=%u  FAIL\n", trial, out_asm, out_c);
            fails++;
        }
    }

    printf("\n=== summary === trials: %d, fails: %d\n", n_trials, fails);
    free(rom);
    return fails == 0 ? 0 : 1;
}
