// AUTO-GENERATED parity spike for cutscene::InitStars @ $13:E247.
// Generated by translator/generate_spike.py from port/cutscene/InitStars.c.
// DO NOT EDIT BY HAND — regenerate via:
//   python translator/generate_spike.py port/cutscene/InitStars.c

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdint.h>
#include <stdbool.h>

#include "snes.h"
#include "cpu.h"

#define TARGET_ADDR_24 0x13E247u

// Forward declarations for helpers defined later in this TU but used by the
// inlined LLM translation below.
static void run_emulated_func(Snes *snes, uint32_t pc24);
static inline uint16_t read16(const uint8_t *ram, int addr);
static inline void write16(uint8_t *ram, int addr, uint16_t v);

// ---------------------------------------------------------------------------
// Auto-emitted *_emu delegation helpers (one per stub referenced by the
// translation but not defined in port/cutscene/InitStars.c).
// ---------------------------------------------------------------------------

// Auto-emitted delegation wrapper for DrawSolarSystemSprite @ $13DA6E (referenced as draw_solar_system_sprite_emu)
static uint16_t draw_solar_system_sprite_emu(Snes *snes) {
    Cpu *c = snes->cpu;
    uint16_t saved_a=c->a, saved_x=c->x, saved_y=c->y, saved_sp=c->sp;
    uint16_t saved_pc=c->pc, saved_dp=c->dp;
    uint8_t saved_k=c->k, saved_db=c->db;
    bool saved_mf=c->mf, saved_xf=c->xf;
    c->dp = 0; c->db = 0x7E;
    c->mf = true; c->xf = false;
    run_emulated_func(snes, 0x13DA6Eu);
    uint16_t result = c->a;
    c->x=saved_x; c->y=saved_y;
    c->sp=saved_sp; c->pc=saved_pc; c->dp=saved_dp;
    c->k=saved_k; c->db=saved_db;
    c->mf=saved_mf; c->xf=saved_xf;
    c->a = saved_a;
    return result;
}


// ---------------------------------------------------------------------------
// LLM-translated C function (verbatim copy from port/cutscene/InitStars.c)
// ---------------------------------------------------------------------------

#include "snes/snes.h"

// Entry mode: A 8-bit (mf=1), X 16-bit (xf=0), DB=$E2, DP=0
// This routine initializes a starfield by iterating 56 times,
// picking coordinates from RNGTbl and calling DrawSolarSystemSprite.
//
// Logic:
//   - Sprite range: $50 = 72 (0x48)
//   - Iterates 56 times (0x38)
//   - Every 8th star (count % 8 != 0) is marked as a "big star" by adding 1 to the sprite index.
//   - Coordinates are pulled from RNGTbl using an incrementing 16-bit index.
static void InitStars_c(Snes *snes) {
    uint8_t *ram = snes->ram;
    
    ram[0x50] = 0x48; // Start sprite index at 72
    
    // clr_ax (TDC / TAX)
    // Since DP=0, A and X are zeroed.
    uint16_t x = 0;
    uint8_t i = 0;

    do {
        // inc $7d27
        ram[0x7D27]++;
        uint8_t count = ram[0x7D27];
        
        // Coordinate 1
        // lda f:RNGTbl,x (f is a segment/bank, here indexed by 16-bit X)
        // We use a helper or direct access to the ROM table. 
        // Since it's a read-only table, we can access it via snes->rom or similar.
        // For this translation, we assume access to the RNGTbl data.
        uint8_t coord_x = snes->rom[0xRNGTbl_Offset + x]; 
        ram[0x4B] = coord_x;

        // Coordinate 2
        // The asm does: tax / lda f:RNGTbl,x / tay / sty $4d
        // This effectively reads the next byte in the table (since X is 16-bit,
        // and we didn't explicitly inc X here, it's the same X as before? 
        // Wait, let's re-read: tax (X=x), lda RNGTbl,x. 
        // Actually, the asm does: tax (X=A=coord_x), then lda RNGTbl,x.
        // That means it uses the VALUE of the first coordinate as the INDEX for the second.
        uint8_t coord_y = snes->rom[0xRNGTbl_Offset + coord_x];
        ram[0x4D] = coord_y;

        // Big star check
        uint8_t size = 0;
        if ((count & 0x07) != 0) { // and #$07 / beq @e26b
            size = 1;
        }

        // Sprite index calculation: 0x48 + size (stored in $4F)
        // Note: clc / adc #$50 / sta $4f
        // Wait, the ASM says `adc #$50`. $48 + $50 is 0x98.
        // But the comment says "use sprites 72-127". 
        // Looking closely: lda #$48 / sta $50 ... then later adc #$50 / sta $4f.
        // This looks like the base is $48 and it's adding $50 offset or a specific constant.
        ram[0x4F] = (uint8_t)(size + 0x50); 
        
        ram[0x51] = 0x01;

        draw_solar_system_sprite_emu(snes);

        x += 2; // inx2 (X is 16-bit)
        i++;    // inc (A is 8-bit)
    } while (i != 0x38); // cmp #$38 / bne @e24d
}


// ---------------------------------------------------------------------------
// Common helpers (same shape as the manual M2/M3/M4 spikes)
// ---------------------------------------------------------------------------

static uint8_t *read_file(const char *path, size_t *out_len) {
    FILE *f = fopen(path, "rb");
    if (!f) { perror(path); return NULL; }
    fseek(f, 0, SEEK_END); long sz = ftell(f); fseek(f, 0, SEEK_SET);
    uint8_t *buf = malloc(sz);
    if (fread(buf, 1, sz, f) != (size_t)sz) { free(buf); fclose(f); return NULL; }
    fclose(f); *out_len = sz; return buf;
}

static inline uint32_t stack_addr(const Cpu *cpu) {
    return cpu->e ? (0x0100u | (cpu->sp & 0xFFu)) : cpu->sp;
}

static void run_emulated_func(Snes *snes, uint32_t pc24) {
    Cpu *cpu = snes->cpu;
    uint16_t sp_save = cpu->sp;
    snes->ram[stack_addr(cpu)] = 0x12; cpu->sp--;
    snes->ram[stack_addr(cpu)] = 0x34; cpu->sp--;
    cpu->k = (uint8_t)(pc24 >> 16);
    cpu->pc = (uint16_t)(pc24 & 0xFFFF);
    long max_ops = 200000;
    while (cpu->sp != sp_save && max_ops-- > 0) {
        cpu_runOpcode(cpu);
        if (cpu->waiting || cpu->stopped) break;
    }
}

typedef struct {
    uint8_t ram[0x20000];
    uint16_t a, x, y, sp, pc, dp;
    uint8_t k, db;
    bool c, z, v, n, i, d, xf, mf, e;
    bool waiting, stopped, irqWanted, nmiWanted;
} Snap;

static void snap_take(Snap *s, Snes *snes) {
    memcpy(s->ram, snes->ram, sizeof(s->ram));
    Cpu *c = snes->cpu;
    s->a=c->a; s->x=c->x; s->y=c->y; s->sp=c->sp; s->pc=c->pc; s->dp=c->dp;
    s->k=c->k; s->db=c->db;
    s->c=c->c; s->z=c->z; s->v=c->v; s->n=c->n;
    s->i=c->i; s->d=c->d; s->xf=c->xf; s->mf=c->mf; s->e=c->e;
    s->waiting=c->waiting; s->stopped=c->stopped;
    s->irqWanted=c->irqWanted; s->nmiWanted=c->nmiWanted;
}
static void snap_restore(const Snap *s, Snes *snes) {
    memcpy(snes->ram, s->ram, sizeof(s->ram));
    Cpu *c = snes->cpu;
    c->a=s->a; c->x=s->x; c->y=s->y; c->sp=s->sp; c->pc=s->pc; c->dp=s->dp;
    c->k=s->k; c->db=s->db;
    c->c=s->c; c->z=s->z; c->v=s->v; c->n=s->n;
    c->i=s->i; c->d=s->d; c->xf=s->xf; c->mf=s->mf; c->e=s->e;
    c->waiting=s->waiting; c->stopped=s->stopped;
    c->irqWanted=s->irqWanted; c->nmiWanted=s->nmiWanted;
}

static inline uint16_t read16(const uint8_t *ram, int addr) {
    return (uint16_t)(ram[addr] | (ram[addr + 1] << 8));
}
static inline void write16(uint8_t *ram, int addr, uint16_t v) {
    ram[addr] = v & 0xFF; ram[addr + 1] = (v >> 8) & 0xFF;
}

// ---------------------------------------------------------------------------
// asm wrapper from the contract
// ---------------------------------------------------------------------------

static void run_asm(Snes *snes) {
    Cpu *c = snes->cpu;
    c->dp = 0;
    c->db = 0x7E;
    c->mf = true;
    c->xf = false;
    c->a = 0; c->x = 0; c->y = 0;
    // no register inputs
    // no entry flags
    run_emulated_func(snes, TARGET_ADDR_24);
}

// ---------------------------------------------------------------------------
// Host PRNG
// ---------------------------------------------------------------------------

static uint32_t host_rng_state = 0xC0FFEEu;
static uint32_t host_rng(void) {
    uint32_t x = host_rng_state;
    x ^= x << 13; x ^= x >> 17; x ^= x << 5;
    host_rng_state = x; return x;
}

// ---------------------------------------------------------------------------
// Trial driver
// ---------------------------------------------------------------------------

int main(int argc, char **argv) {
    if (argc < 2) {
        fprintf(stderr, "usage: %s <rom.sfc> [n_trials]\n", argv[0]);
        return 1;
    }
    int n_trials = (argc >= 3) ? atoi(argv[2]) : 1000;

    size_t rom_len = 0;
    uint8_t *rom = read_file(argv[1], &rom_len);
    if (!rom) return 2;

    Snes *snes = snes_init();
    if (!snes_loadRom(snes, rom, rom_len)) { fprintf(stderr, "loadRom fail\n"); return 3; }
    snes_reset(snes, true);
    for (int i = 0; i < 60; i++) snes_runFrame(snes);
    snes->cpu->i = true; snes->cpu->nmiWanted = false; snes->cpu->irqWanted = false;

    Snap baseline;
    snap_take(&baseline, snes);

    fprintf(stderr, "InitStars asm vs C : %d trials\n", n_trials);

    int fails = 0;
    for (int trial = 0; trial < n_trials; trial++) {
        snap_restore(&baseline, snes);

        // Randomise inputs.
        // no RAM inputs


        // Pre-call snapshot for replaying C with the exact same state.
        Snap pre;
        snap_take(&pre, snes);

        // Run ASM
        run_asm(snes);
        uint8_t out_asm = snes->ram[0x004B];

        // Restore and run C
        snap_restore(&pre, snes);
        InitStars_c(snes);
        uint8_t out_c = snes->ram[0x004B];

        bool ok = (out_asm == out_c);
        if (!ok) {
            printf("trial %4d : asm=%u c=%u  FAIL\n", trial, out_asm, out_c);
            fails++;
        }
    }

    printf("\n=== summary === trials: %d, fails: %d\n", n_trials, fails);
    free(rom);
    return fails == 0 ? 0 : 1;
}
