// AUTO-GENERATED parity spike for field::LoadSpriteGfx @ $00:C38B.
// Generated by translator/generate_spike.py from port/field/LoadSpriteGfx.c.
// DO NOT EDIT BY HAND — regenerate via:
//   python translator/generate_spike.py port/field/LoadSpriteGfx.c

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdint.h>
#include <stdbool.h>

#include "snes.h"
#include "cpu.h"

#define TARGET_ADDR_24 0x00C38Bu

// Forward declarations for helpers defined later in this TU but used by the
// inlined LLM translation below.
static void run_emulated_func(Snes *snes, uint32_t pc24);
static inline uint16_t read16(const uint8_t *ram, int addr);
static inline void write16(uint8_t *ram, int addr, uint16_t v);

// ---------------------------------------------------------------------------
// Auto-emitted *_emu delegation helpers (one per stub referenced by the
// translation but not defined in port/field/LoadSpriteGfx.c).
// ---------------------------------------------------------------------------

// (no auto-emitted helpers)

// ---------------------------------------------------------------------------
// LLM-translated C function (verbatim copy from port/field/LoadSpriteGfx.c)
// ---------------------------------------------------------------------------

#include "snes/snes.h"

// Entry mode: A 8-bit (mf=1), X 16-bit (xf=0), DB=$C3, DP=0
// This function determines the source address and size of sprite graphics
// based on an input index in A, then calls Tfr3bppGfx to perform the transfer.
//
// Logic:
// 1. Determine 'x' (source offset) and 'a' (scale/index) based on ranges:
//    - A < 0x11: x=0, scale=A << 3
//    - A < 0x30: x=0x3300, scale=(A-0x11) << 2
//    - A < 0x46: x=0x6180, scale=(A-0x30) << 1
//    - A >= 0x46: x=0x7200, scale=(A-0x46)
// 2. Compute a complex 16-bit address shift:
//    - tmp = (scale >> 2)
//    - tmp = tmp + (tmp >> 1)  // effectively scale * 0.75
//    - final_offset = x + tmp + 0x8000
// 3. Set transfer parameters in RAM and call Tfr3bppGfx.
static void LoadSpriteGfx_c(Snes *snes) {
    uint8_t *ram = snes->ram;
    uint8_t a = (uint8_t)snes->cpu->a;
    uint32_t x_val = 0;
    uint16_t scale = 0;

    if (a < 0x11) {                      // cmp #$11 / bcs @c398
        scale = (uint16_t)(a << 3);      // asl3
        x_val = 0;                      // ldx #0
    } else if (a < 0x30) {              // cmp #$30 / bcs @c3a7
        scale = (uint16_t)((a - 0x11) << 2); // sbc #$11 / asl2
        x_val = 0x3300;                 // ldx #$3300
    } else if (a < 0x46) {              // cmp #$46 / bcs @c3b5
        scale = (uint16_t)((a - 0x30) << 1); // sbc #$30 / asl
        x_val = 0x6180;                 // ldx #$6180
    } else {                            // sec / sbc #$46
        scale = (uint16_t)(a - 0x46);
        x_val = 0x7200;                 // ldx #$7200
    }

    // --- 16-bit math block (longa) ---
    // xba / lsr2 / sta $4a / lsr / adc $4a / sta $4a
    // This calculates: tmp = (scale >> 2); tmp = tmp + (tmp >> 1)
    uint16_t tmp = (uint16_t)(scale >> 2); 
    tmp = (uint8_t)(tmp >> 1);           // lsr (8-bit truncation happens here due to sta $4a)
    uint8_t ram4a = (uint8_t)tmp;       // sta $4a
    
    // The ASM uses $4a as a scratchpad for these 8-bit operations
    uint8_t scratch = (uint8_t)(scale >> 2); // lsr2 / sta $4a
    uint8_t s_shift = (uint8_t)(scratch >> 1); // lsr
    scratch = (uint8_t)(s_shift + scratch); // adc $4a / sta $4a
    
    // final calc: txa / clc / adc $4a / clc / adc #$8000 / sta $4a
    // Note: xba puts scale into A, then it adds the 8-bit scratch and 0x8000
    uint16_t final_addr_low = (uint16_t)scale + scratch + 0x8000;
    ram[0x4A] = (uint8_t)final_addr_low; // sta $4a (only low byte stored)

    // --- 8-bit mode (shorta) ---
    uint8_t ae = ram[0xAE];
    ram[0x4D] = (uint8_t)((ae << 1) + 0x42); // lda $ae / asl / adc #$42 / sta $4d
    ram[0x4C] = 0;                          // stz $4c
    write16(ram, 0x4E, 0x0200);             // ldx #$0200 / stx $4e
    
    // MapSpriteGfx bank byte (assumed handled by the project's bank map)
    ram[0x49] = 0x03; // .bankbyte(MapSpriteGfx) - Adjusted to typical value or helper

    tfr3bppgfx_emu(snes); // jsl Tfr3bppGfx
}


// ---------------------------------------------------------------------------
// Common helpers (same shape as the manual M2/M3/M4 spikes)
// ---------------------------------------------------------------------------

static uint8_t *read_file(const char *path, size_t *out_len) {
    FILE *f = fopen(path, "rb");
    if (!f) { perror(path); return NULL; }
    fseek(f, 0, SEEK_END); long sz = ftell(f); fseek(f, 0, SEEK_SET);
    uint8_t *buf = malloc(sz);
    if (fread(buf, 1, sz, f) != (size_t)sz) { free(buf); fclose(f); return NULL; }
    fclose(f); *out_len = sz; return buf;
}

static inline uint32_t stack_addr(const Cpu *cpu) {
    return cpu->e ? (0x0100u | (cpu->sp & 0xFFu)) : cpu->sp;
}

static void run_emulated_func(Snes *snes, uint32_t pc24) {
    Cpu *cpu = snes->cpu;
    uint16_t sp_save = cpu->sp;
    snes->ram[stack_addr(cpu)] = 0x12; cpu->sp--;
    snes->ram[stack_addr(cpu)] = 0x34; cpu->sp--;
    cpu->k = (uint8_t)(pc24 >> 16);
    cpu->pc = (uint16_t)(pc24 & 0xFFFF);
    long max_ops = 200000;
    while (cpu->sp != sp_save && max_ops-- > 0) {
        cpu_runOpcode(cpu);
        if (cpu->waiting || cpu->stopped) break;
    }
}

typedef struct {
    uint8_t ram[0x20000];
    uint16_t a, x, y, sp, pc, dp;
    uint8_t k, db;
    bool c, z, v, n, i, d, xf, mf, e;
    bool waiting, stopped, irqWanted, nmiWanted;
} Snap;

static void snap_take(Snap *s, Snes *snes) {
    memcpy(s->ram, snes->ram, sizeof(s->ram));
    Cpu *c = snes->cpu;
    s->a=c->a; s->x=c->x; s->y=c->y; s->sp=c->sp; s->pc=c->pc; s->dp=c->dp;
    s->k=c->k; s->db=c->db;
    s->c=c->c; s->z=c->z; s->v=c->v; s->n=c->n;
    s->i=c->i; s->d=c->d; s->xf=c->xf; s->mf=c->mf; s->e=c->e;
    s->waiting=c->waiting; s->stopped=c->stopped;
    s->irqWanted=c->irqWanted; s->nmiWanted=c->nmiWanted;
}
static void snap_restore(const Snap *s, Snes *snes) {
    memcpy(snes->ram, s->ram, sizeof(s->ram));
    Cpu *c = snes->cpu;
    c->a=s->a; c->x=s->x; c->y=s->y; c->sp=s->sp; c->pc=s->pc; c->dp=s->dp;
    c->k=s->k; c->db=s->db;
    c->c=s->c; c->z=s->z; c->v=s->v; c->n=s->n;
    c->i=s->i; c->d=s->d; c->xf=s->xf; c->mf=s->mf; c->e=s->e;
    c->waiting=s->waiting; c->stopped=s->stopped;
    c->irqWanted=s->irqWanted; c->nmiWanted=s->nmiWanted;
}

static inline uint16_t read16(const uint8_t *ram, int addr) {
    return (uint16_t)(ram[addr] | (ram[addr + 1] << 8));
}
static inline void write16(uint8_t *ram, int addr, uint16_t v) {
    ram[addr] = v & 0xFF; ram[addr + 1] = (v >> 8) & 0xFF;
}

// ---------------------------------------------------------------------------
// asm wrapper from the contract
// ---------------------------------------------------------------------------

static void run_asm(Snes *snes, uint8_t arg_a) {
    Cpu *c = snes->cpu;
    c->dp = 0;
    c->db = 0x7E;
    c->mf = true;
    c->xf = false;
    c->a = 0; c->x = 0; c->y = 0;
    c->a = arg_a;
    c->z = (arg_a == 0);
    c->n = ((arg_a & 0x80) != 0);
    run_emulated_func(snes, TARGET_ADDR_24);
}

// ---------------------------------------------------------------------------
// Host PRNG
// ---------------------------------------------------------------------------

static uint32_t host_rng_state = 0xC0FFEEu;
static uint32_t host_rng(void) {
    uint32_t x = host_rng_state;
    x ^= x << 13; x ^= x >> 17; x ^= x << 5;
    host_rng_state = x; return x;
}

// ---------------------------------------------------------------------------
// Trial driver
// ---------------------------------------------------------------------------

int main(int argc, char **argv) {
    if (argc < 2) {
        fprintf(stderr, "usage: %s <rom.sfc> [n_trials]\n", argv[0]);
        return 1;
    }
    int n_trials = (argc >= 3) ? atoi(argv[2]) : 1000;

    size_t rom_len = 0;
    uint8_t *rom = read_file(argv[1], &rom_len);
    if (!rom) return 2;

    Snes *snes = snes_init();
    if (!snes_loadRom(snes, rom, rom_len)) { fprintf(stderr, "loadRom fail\n"); return 3; }
    snes_reset(snes, true);
    for (int i = 0; i < 60; i++) snes_runFrame(snes);
    snes->cpu->i = true; snes->cpu->nmiWanted = false; snes->cpu->irqWanted = false;

    Snap baseline;
    snap_take(&baseline, snes);

    fprintf(stderr, "LoadSpriteGfx asm vs C : %d trials\n", n_trials);

    int fails = 0;
    for (int trial = 0; trial < n_trials; trial++) {
        snap_restore(&baseline, snes);

        // Randomise inputs.
        snes->ram[0x00AE] = (uint8_t)host_rng();
        uint8_t arg_a = (uint8_t)host_rng();

        // Pre-call snapshot for replaying C with the exact same state.
        Snap pre;
        snap_take(&pre, snes);

        // Run ASM
        run_asm(snes, arg_a);
        uint8_t out_asm = snes->ram[0x004A];

        // Restore and run C
        snap_restore(&pre, snes);
        LoadSpriteGfx_c(snes, arg_a);
        uint8_t out_c = snes->ram[0x004A];

        bool ok = (out_asm == out_c);
        if (!ok) {
            printf("trial %4d : asm=%u c=%u  FAIL\n", trial, out_asm, out_c);
            fails++;
        }
    }

    printf("\n=== summary === trials: %d, fails: %d\n", n_trials, fails);
    free(rom);
    return fails == 0 ? 0 : 1;
}
