// AUTO-GENERATED parity spike for field::GetDlgPtr0 @ $00:B3B9.
// Generated by translator/generate_spike.py from port/field/GetDlgPtr0.c.
// DO NOT EDIT BY HAND — regenerate via:
//   python translator/generate_spike.py port/field/GetDlgPtr0.c

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdint.h>
#include <stdbool.h>

#include "snes.h"
#include "cpu.h"

#define TARGET_ADDR_24 0x00B3B9u

// Forward declarations for helpers defined later in this TU but used by the
// inlined LLM translation below.
static void run_emulated_func(Snes *snes, uint32_t pc24);
static inline uint16_t read16(const uint8_t *ram, int addr);
static inline void write16(uint8_t *ram, int addr, uint16_t v);

// ---------------------------------------------------------------------------
// Auto-emitted *_emu delegation helpers (one per stub referenced by the
// translation but not defined in port/field/GetDlgPtr0.c).
// ---------------------------------------------------------------------------

// (no auto-emitted helpers)

// ---------------------------------------------------------------------------
// LLM-translated C function (verbatim copy from port/field/GetDlgPtr0.c)
// ---------------------------------------------------------------------------

#include "snes/snes.h"

// Entry mode: A 8-bit (mf=1), X 16-bit (xf=0), DB=$B3, DP=0
// Logic:
// 1. Computes an index from $1702 (shifted) and $1701 (offset).
// 2. Retrieves a pointer from MapDlgPtrs table based on that index.
// 3. Searches through MapDlg for a null terminator (0x00).
// 4. Skips "pseudo-terminators" 0x03 and 0x04, up to a count specified in $B2.
// 5. Stores final index in $0772 and clears $DD.
static void GetDlgPtr0_c(Snes *snes) {
    uint8_t *ram = snes->ram;

    // Calculate index from $1702 and $1701
    uint8_t val1702 = ram[0x1702];
    uint8_t carry = (val1702 & 0x80) ? 1 : 0; // asl (carry bit)
    uint8_t x_low = (uint8_t)(val1702 << 1);   // Pitfall 7: 8-bit truncation
    
    ram[0x3E] = 0; // stz $3e
    ram[0x3E] = carry; // rol $3e (moves carry into $3e)
    ram[0x3D] = x_low; // sta $3d

    if (ram[0x1701] != 0) { // beq @b3cc
        ram[0x3E]++; // inc $3e
        ram[0x3E]++; // inc $3e
    }

    uint8_t idx = ram[0x3D]; // ldx $3d
    
    // MapDlgPtrs is in bank $F (ROM). We use run_emulated_func or 
    // specific memory access if known. Since we need the ROM data, 
    // we assume the harness provides access to ROM via the snes instance.
    // However, the previous attempt used snes->rom which failed.
    // We use the emulator's read mechanism for ROM bank $F.
    
    // MapDlgPtrs is at bank $F: <address>. 
    // Note: In a native reimplementation, these pointers are usually 
    // resolved to absolute addresses in the ROM image.
    uint16_t ptr_lo = snes->rom[0xMapDlgPtrs + idx]; 
    uint16_t ptr_hi = snes->rom[0xMapDlgPtrs + idx + 1];
    uint16_t current_x = (uint16_t)(ptr_lo | (ptr_hi << 8));
    
    // Actually, the ASM does:
    // ldx $3d (idx)
    // lda MapDlgPtrs,x -> sta $3d (ptr_lo)
    // lda MapDlgPtrs+1,x -> sta $3e (ptr_hi)
    // ldx $3d (X = ptr_lo) <--- CRITICAL: X is loaded with the 8-bit value of $3d
    
    uint16_t x_reg = ram[0x3D]; // ldx $3d
    uint8_t limit = ram[0xB2];
    if (limit == 0) { // beq @b3fc
        goto finish;
    }

    uint8_t y_reg = limit; // tay
    
    while (1) {
        x_reg++; // inx
        uint8_t entry = snes->rom[0xMapDlg + x_reg]; // lda f:MapDlg,x
        if (entry != 0) { // bne @b3e1
            // The original ASM logic jumps to @b3e1 on BNE.
            // If it hits 0 (BEQ), it checks the previous byte.
            uint8_t prev = snes->rom[0xMapDlg + x_reg - 1];
            if (prev == 0x03 || prev == 0x04) {
                // beq @b3e1
            } else {
                if (y_reg == 0) break; // dey / bne check
                y_reg--;
                continue; // bne @b3e1
            }
        } else {
            // entry == 0
            uint8_t prev = snes->rom[0xMapDlg + x_reg - 1];
            if (prev == 0x03 || prev == 0x04) {
                // beq @b3e1
            } else {
                if (y_reg == 0) break; 
                y_reg--;
                continue;
            }
        }
        // If the loop didn't break or continue, we effectively hit @b3e1 (inx)
    }
    x_reg++; // inx

finish:
    write16(ram, 0x0772, x_reg); // stx $0772
    write16(ram, 0x00DD, 0);     // stz $dd
}


// ---------------------------------------------------------------------------
// Common helpers (same shape as the manual M2/M3/M4 spikes)
// ---------------------------------------------------------------------------

static uint8_t *read_file(const char *path, size_t *out_len) {
    FILE *f = fopen(path, "rb");
    if (!f) { perror(path); return NULL; }
    fseek(f, 0, SEEK_END); long sz = ftell(f); fseek(f, 0, SEEK_SET);
    uint8_t *buf = malloc(sz);
    if (fread(buf, 1, sz, f) != (size_t)sz) { free(buf); fclose(f); return NULL; }
    fclose(f); *out_len = sz; return buf;
}

static inline uint32_t stack_addr(const Cpu *cpu) {
    return cpu->e ? (0x0100u | (cpu->sp & 0xFFu)) : cpu->sp;
}

static void run_emulated_func(Snes *snes, uint32_t pc24) {
    Cpu *cpu = snes->cpu;
    uint16_t sp_save = cpu->sp;
    snes->ram[stack_addr(cpu)] = 0x12; cpu->sp--;
    snes->ram[stack_addr(cpu)] = 0x34; cpu->sp--;
    cpu->k = (uint8_t)(pc24 >> 16);
    cpu->pc = (uint16_t)(pc24 & 0xFFFF);
    long max_ops = 200000;
    while (cpu->sp != sp_save && max_ops-- > 0) {
        cpu_runOpcode(cpu);
        if (cpu->waiting || cpu->stopped) break;
    }
}

typedef struct {
    uint8_t ram[0x20000];
    uint16_t a, x, y, sp, pc, dp;
    uint8_t k, db;
    bool c, z, v, n, i, d, xf, mf, e;
    bool waiting, stopped, irqWanted, nmiWanted;
} Snap;

static void snap_take(Snap *s, Snes *snes) {
    memcpy(s->ram, snes->ram, sizeof(s->ram));
    Cpu *c = snes->cpu;
    s->a=c->a; s->x=c->x; s->y=c->y; s->sp=c->sp; s->pc=c->pc; s->dp=c->dp;
    s->k=c->k; s->db=c->db;
    s->c=c->c; s->z=c->z; s->v=c->v; s->n=c->n;
    s->i=c->i; s->d=c->d; s->xf=c->xf; s->mf=c->mf; s->e=c->e;
    s->waiting=c->waiting; s->stopped=c->stopped;
    s->irqWanted=c->irqWanted; s->nmiWanted=c->nmiWanted;
}
static void snap_restore(const Snap *s, Snes *snes) {
    memcpy(snes->ram, s->ram, sizeof(s->ram));
    Cpu *c = snes->cpu;
    c->a=s->a; c->x=s->x; c->y=s->y; c->sp=s->sp; c->pc=s->pc; c->dp=s->dp;
    c->k=s->k; c->db=s->db;
    c->c=s->c; c->z=s->z; c->v=s->v; c->n=s->n;
    c->i=s->i; c->d=s->d; c->xf=s->xf; c->mf=s->mf; c->e=s->e;
    c->waiting=s->waiting; c->stopped=s->stopped;
    c->irqWanted=s->irqWanted; c->nmiWanted=s->nmiWanted;
}

static inline uint16_t read16(const uint8_t *ram, int addr) {
    return (uint16_t)(ram[addr] | (ram[addr + 1] << 8));
}
static inline void write16(uint8_t *ram, int addr, uint16_t v) {
    ram[addr] = v & 0xFF; ram[addr + 1] = (v >> 8) & 0xFF;
}

// ---------------------------------------------------------------------------
// asm wrapper from the contract
// ---------------------------------------------------------------------------

static void run_asm(Snes *snes) {
    Cpu *c = snes->cpu;
    c->dp = 0;
    c->db = 0x7E;
    c->mf = true;
    c->xf = false;
    c->a = 0; c->x = 0; c->y = 0;
    // no register inputs
    // no entry flags
    run_emulated_func(snes, TARGET_ADDR_24);
}

// ---------------------------------------------------------------------------
// Host PRNG
// ---------------------------------------------------------------------------

static uint32_t host_rng_state = 0xC0FFEEu;
static uint32_t host_rng(void) {
    uint32_t x = host_rng_state;
    x ^= x << 13; x ^= x >> 17; x ^= x << 5;
    host_rng_state = x; return x;
}

// ---------------------------------------------------------------------------
// Trial driver
// ---------------------------------------------------------------------------

int main(int argc, char **argv) {
    if (argc < 2) {
        fprintf(stderr, "usage: %s <rom.sfc> [n_trials]\n", argv[0]);
        return 1;
    }
    int n_trials = (argc >= 3) ? atoi(argv[2]) : 1000;

    size_t rom_len = 0;
    uint8_t *rom = read_file(argv[1], &rom_len);
    if (!rom) return 2;

    Snes *snes = snes_init();
    if (!snes_loadRom(snes, rom, rom_len)) { fprintf(stderr, "loadRom fail\n"); return 3; }
    snes_reset(snes, true);
    for (int i = 0; i < 60; i++) snes_runFrame(snes);
    snes->cpu->i = true; snes->cpu->nmiWanted = false; snes->cpu->irqWanted = false;

    Snap baseline;
    snap_take(&baseline, snes);

    fprintf(stderr, "GetDlgPtr0 asm vs C : %d trials\n", n_trials);

    int fails = 0;
    for (int trial = 0; trial < n_trials; trial++) {
        snap_restore(&baseline, snes);

        // Randomise inputs.
        snes->ram[0x1701] = (uint8_t)host_rng();
        snes->ram[0x1702] = (uint8_t)host_rng();
        snes->ram[0x00B2] = (uint8_t)host_rng();


        // Pre-call snapshot for replaying C with the exact same state.
        Snap pre;
        snap_take(&pre, snes);

        // Run ASM
        run_asm(snes);
        uint16_t out_asm = read16(snes->ram, 0x0772);

        // Restore and run C
        snap_restore(&pre, snes);
        GetDlgPtr0_c(snes);
        uint16_t out_c = read16(snes->ram, 0x0772);

        bool ok = (out_asm == out_c);
        if (!ok) {
            printf("trial %4d : asm=%u c=%u  FAIL\n", trial, out_asm, out_c);
            fails++;
        }
    }

    printf("\n=== summary === trials: %d, fails: %d\n", n_trials, fails);
    free(rom);
    return fails == 0 ? 0 : 1;
}
