// AUTO-GENERATED parity spike for field::CheckNPCBlock @ $00:AA94.
// Generated by translator/generate_spike.py from port/field/CheckNPCBlock.c.
// DO NOT EDIT BY HAND — regenerate via:
//   python translator/generate_spike.py port/field/CheckNPCBlock.c

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdint.h>
#include <stdbool.h>

#include "snes.h"
#include "cpu.h"

#define TARGET_ADDR_24 0x00AA94u

// Forward declarations for helpers defined later in this TU but used by the
// inlined LLM translation below.
static void run_emulated_func(Snes *snes, uint32_t pc24);
static inline uint16_t read16(const uint8_t *ram, int addr);
static inline void write16(uint8_t *ram, int addr, uint16_t v);

// ---------------------------------------------------------------------------
// Auto-emitted *_emu delegation helpers (one per stub referenced by the
// translation but not defined in port/field/CheckNPCBlock.c).
// ---------------------------------------------------------------------------

// (no auto-emitted helpers)

// ---------------------------------------------------------------------------
// LLM-translated C function (verbatim copy from port/field/CheckNPCBlock.c)
// ---------------------------------------------------------------------------

#include "snes/snes.h"

// Entry mode: A 8-bit (mf=1), X/Y 16-bit (xf=0), DB=0xAA (Field ROM bank), DP=0
// Logic: Checks if an NPC's intended movement is blocked by another NPC or terrain.
// 1. Determines direction and checks if it's a "bridge tile" move via table at $a1.
// 2. Checks if the entity is on the lower Z-level ($d2).
// 3. Calculates target X/Y and checks boundary ($20).
// 4. Checks if the tile is empty via GetNPCMapPtr and map data.
// Returns: A = 0 if blocked, A = tile_value (signed/negative) if blocked by specific tile, 
//         or keeps A as is/returns 0 via @aad4 if out of bounds.
static uint16_t CheckNPCBlock_c(Snes *snes) {
    uint8_t *ram = snes->ram;
    uint8_t dir = ram[0x0709]; // moving direction
    uint8_t y = dir;
    uint8_t x_idx = (uint8_t)(y << 1); // asl A / tax

    // Check if moving to bridge tile (Table at $a1 relative to DP=0)
    // Note: $a1 is accessed as an absolute address in DP=0 context
    if (!((ram[0xA1 + x_idx] & 0x04) != 0)) { // beq @aaa9 (if NOT bridge tile)
        goto aaa9;
    }

    // Must be on lower z-level to be blocked by bridge-logic tiles
    if (ram[0xD2] != 0x01) { // cmp #$01 / beq @aaa9
        goto aaa9;
    }

    return 0; // lda #$00 / rts

aaa9:
    // Calculate Target X
    // XMoveTbl is assumed to be in ROM bank $AA. Access via snes->rom or a provided helper.
    // For the sake of parity, we assume access to the ROM tables.
    uint8_t x_pos = ram[0x1706];
    uint8_t offset_x = snes->rom[0xAA00 + 0x0000 + y]; // Simplified XMoveTbl lookup
    uint8_t target_x = (uint8_t)(x_pos + offset_x); // clc / adc
    ram[0x0C] = target_x;
    if (target_x >= 0x20) { // cmp #$20 / bcs @aad4
        goto aad4;
    }

    // Calculate Target Y
    uint8_t y_pos = ram[0x1707];
    uint8_t offset_y = snes->rom[0xAA00 + 0x0000 + y]; // Simplified YMoveTbl lookup (Actual offset differs)
    // Note: In actual asm, YMoveTbl is a different address than XMoveTbl.
    // Correcting for table offsets:
    uint8_t actual_off_x = snes->rom[0xAA00 + 0x/*XMoveTbl_Offset*/ + y]; 
    uint8_t actual_off_y = snes->rom[0xAA00 + 0x/*YMoveTbl_Offset*/ + y];
    
    // Re-calculating with table logic
    target_x = (uint8_t)(ram[0x1706] + actual_off_x);
    ram[0x0C] = target_x;
    if (target_x >= 0x20) goto aad4;

    uint8_t target_y = (uint8_t)(ram[0x1707] + actual_off_y);
    ram[0x0E] = target_y;
    if (target_y >= 0x20) { // cmp #$20 / bcs @aad4
        goto aad4;
    }

    get_npc_map_ptr_emu(snes); // jsr GetNPCMapPtr
    uint8_t ptr_idx = ram[0x3D]; // ldx $3d
    
    // Access map data at $7f4c00 + x. 
    // Since this is a ROM/RAM mirror access, we use the snes->ram offset if mapped.
    uint8_t tile = snes->ram[0x4C00 + ptr_idx]; // lda $7f4c00,x (Simplified mapping)
    
    if ((int8_t)tile >= 0) { // bpl @aad4 (branch if tile is empty/positive)
        goto aad4;
    }

    ram[0xEE] = tile; // sta $ee
    return (uint16_t)tile; // jmp @aad6 -> plx / rts

aad4:
    return 0; // lda #$00
}


// ---------------------------------------------------------------------------
// Common helpers (same shape as the manual M2/M3/M4 spikes)
// ---------------------------------------------------------------------------

static uint8_t *read_file(const char *path, size_t *out_len) {
    FILE *f = fopen(path, "rb");
    if (!f) { perror(path); return NULL; }
    fseek(f, 0, SEEK_END); long sz = ftell(f); fseek(f, 0, SEEK_SET);
    uint8_t *buf = malloc(sz);
    if (fread(buf, 1, sz, f) != (size_t)sz) { free(buf); fclose(f); return NULL; }
    fclose(f); *out_len = sz; return buf;
}

static inline uint32_t stack_addr(const Cpu *cpu) {
    return cpu->e ? (0x0100u | (cpu->sp & 0xFFu)) : cpu->sp;
}

static void run_emulated_func(Snes *snes, uint32_t pc24) {
    Cpu *cpu = snes->cpu;
    uint16_t sp_save = cpu->sp;
    snes->ram[stack_addr(cpu)] = 0x12; cpu->sp--;
    snes->ram[stack_addr(cpu)] = 0x34; cpu->sp--;
    cpu->k = (uint8_t)(pc24 >> 16);
    cpu->pc = (uint16_t)(pc24 & 0xFFFF);
    long max_ops = 200000;
    while (cpu->sp != sp_save && max_ops-- > 0) {
        cpu_runOpcode(cpu);
        if (cpu->waiting || cpu->stopped) break;
    }
}

typedef struct {
    uint8_t ram[0x20000];
    uint16_t a, x, y, sp, pc, dp;
    uint8_t k, db;
    bool c, z, v, n, i, d, xf, mf, e;
    bool waiting, stopped, irqWanted, nmiWanted;
} Snap;

static void snap_take(Snap *s, Snes *snes) {
    memcpy(s->ram, snes->ram, sizeof(s->ram));
    Cpu *c = snes->cpu;
    s->a=c->a; s->x=c->x; s->y=c->y; s->sp=c->sp; s->pc=c->pc; s->dp=c->dp;
    s->k=c->k; s->db=c->db;
    s->c=c->c; s->z=c->z; s->v=c->v; s->n=c->n;
    s->i=c->i; s->d=c->d; s->xf=c->xf; s->mf=c->mf; s->e=c->e;
    s->waiting=c->waiting; s->stopped=c->stopped;
    s->irqWanted=c->irqWanted; s->nmiWanted=c->nmiWanted;
}
static void snap_restore(const Snap *s, Snes *snes) {
    memcpy(snes->ram, s->ram, sizeof(s->ram));
    Cpu *c = snes->cpu;
    c->a=s->a; c->x=s->x; c->y=s->y; c->sp=s->sp; c->pc=s->pc; c->dp=s->dp;
    c->k=s->k; c->db=s->db;
    c->c=s->c; c->z=s->z; c->v=s->v; c->n=s->n;
    c->i=s->i; c->d=s->d; c->xf=s->xf; c->mf=s->mf; c->e=s->e;
    c->waiting=s->waiting; c->stopped=s->stopped;
    c->irqWanted=s->irqWanted; c->nmiWanted=s->nmiWanted;
}

static inline uint16_t read16(const uint8_t *ram, int addr) {
    return (uint16_t)(ram[addr] | (ram[addr + 1] << 8));
}
static inline void write16(uint8_t *ram, int addr, uint16_t v) {
    ram[addr] = v & 0xFF; ram[addr + 1] = (v >> 8) & 0xFF;
}

// ---------------------------------------------------------------------------
// asm wrapper from the contract
// ---------------------------------------------------------------------------

static void run_asm(Snes *snes) {
    Cpu *c = snes->cpu;
    c->dp = 0;
    c->db = 0x7E;
    c->mf = true;
    c->xf = false;
    c->a = 0; c->x = 0; c->y = 0;
    // no register inputs
    // no entry flags
    run_emulated_func(snes, TARGET_ADDR_24);
}

// ---------------------------------------------------------------------------
// Host PRNG
// ---------------------------------------------------------------------------

static uint32_t host_rng_state = 0xC0FFEEu;
static uint32_t host_rng(void) {
    uint32_t x = host_rng_state;
    x ^= x << 13; x ^= x >> 17; x ^= x << 5;
    host_rng_state = x; return x;
}

// ---------------------------------------------------------------------------
// Trial driver
// ---------------------------------------------------------------------------

int main(int argc, char **argv) {
    if (argc < 2) {
        fprintf(stderr, "usage: %s <rom.sfc> [n_trials]\n", argv[0]);
        return 1;
    }
    int n_trials = (argc >= 3) ? atoi(argv[2]) : 1000;

    size_t rom_len = 0;
    uint8_t *rom = read_file(argv[1], &rom_len);
    if (!rom) return 2;

    Snes *snes = snes_init();
    if (!snes_loadRom(snes, rom, rom_len)) { fprintf(stderr, "loadRom fail\n"); return 3; }
    snes_reset(snes, true);
    for (int i = 0; i < 60; i++) snes_runFrame(snes);
    snes->cpu->i = true; snes->cpu->nmiWanted = false; snes->cpu->irqWanted = false;

    Snap baseline;
    snap_take(&baseline, snes);

    fprintf(stderr, "CheckNPCBlock asm vs C : %d trials\n", n_trials);

    int fails = 0;
    for (int trial = 0; trial < n_trials; trial++) {
        snap_restore(&baseline, snes);

        // Randomise inputs.
        snes->ram[0x0709] = (uint8_t)host_rng();
        snes->ram[0x1706] = (uint8_t)host_rng();
        snes->ram[0x1707] = (uint8_t)host_rng();
        snes->ram[0x00A1] = (uint8_t)host_rng();
        snes->ram[0x00D2] = (uint8_t)host_rng();


        // Pre-call snapshot for replaying C with the exact same state.
        Snap pre;
        snap_take(&pre, snes);

        // Run ASM
        run_asm(snes);
        uint8_t out_asm = snes->ram[0x000C];

        // Restore and run C
        snap_restore(&pre, snes);
        CheckNPCBlock_c(snes);
        uint8_t out_c = snes->ram[0x000C];

        bool ok = (out_asm == out_c);
        if (!ok) {
            printf("trial %4d : asm=%u c=%u  FAIL\n", trial, out_asm, out_c);
            fails++;
        }
    }

    printf("\n=== summary === trials: %d, fails: %d\n", n_trials, fails);
    free(rom);
    return fails == 0 ? 0 : 1;
}
