// AUTO-GENERATED parity spike for field::UpdateZoomPal @ $00:C505.
// Generated by translator/generate_spike.py from port/field/UpdateZoomPal.c.
// DO NOT EDIT BY HAND — regenerate via:
//   python translator/generate_spike.py port/field/UpdateZoomPal.c

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdint.h>
#include <stdbool.h>

#include "snes.h"
#include "cpu.h"

#define TARGET_ADDR_24 0x00C505u

// Forward declarations for helpers defined later in this TU but used by the
// inlined LLM translation below.
static void run_emulated_func(Snes *snes, uint32_t pc24);
static inline uint16_t read16(const uint8_t *ram, int addr);
static inline void write16(uint8_t *ram, int addr, uint16_t v);

// ---------------------------------------------------------------------------
// Auto-emitted *_emu delegation helpers (one per stub referenced by the
// translation but not defined in port/field/UpdateZoomPal.c).
// ---------------------------------------------------------------------------

// (no auto-emitted helpers)

// ---------------------------------------------------------------------------
// LLM-translated C function (verbatim copy from port/field/UpdateZoomPal.c)
// ---------------------------------------------------------------------------

#include "snes/snes.h"

// Entry mode: A 8-bit (mf=1), X 16-bit (xf=0), DB=$C5, DP=0
// Purpose: Updates specific palette colors based on the current map type (WRAM $1700)
// and a zoom index (passed in A, masked to even).
// The ZoomPalTbl is a 2D array of colors (18 bytes per zoom level).
void UpdateZoomPal_c(Snes *snes) {
    uint8_t *ram = snes->ram;
    
    // and #$fe / tax
    uint8_t zoom_idx = (uint8_t)(snes->cpu->a & 0xFE);
    uint16_t x = zoom_idx;

    // lda $1700
    uint8_t map_type = ram[0x1700];
    
    // ZoomPalTbl is located in Bank $C5. 
    // Since the routine uses 'longa' to load from the table, it reads 16-bit words,
    // but stores them into 8-bit palette registers. This effectively stores 
    // the low byte of the table entry.
    // Table offset = (zoom_idx / 2) * 18. 
    // Note: the ASM 'x' is the masked value. In 65816, lda table,x with A16 
    // adds x to the address. Because the table is structured as 18-byte blocks,
    // and x is (zoom_idx & 0xFE), the ASM logic is using the index to offset 
    // into the table.
    
    // We need to locate ZoomPalTbl. Since it's in the same bank (f:), 
    // we use the address provided by the bridge/disassembly.
    // Based on the offsets provided (e.g., +18*15), we calculate the base.
    // Since this is a translation for the harness, we assume ZoomPalTbl 
    // is accessible via the snes->ram if mapped or via a ROM read.
    // In the context of this port, we access the ROM data for the table.
    
    // We represent the table access as a helper or direct memory read from ROM.
    // Let's assume a helper `read_rom_byte` or similar. 
    // Actually, for parity, we can simulate the 16-bit load: lda table,x (A16)
    // which loads [table + x] and [table + x + 1]. The 'sta' then saves 
    // the low byte (A_low) to RAM.
    
    #define GET_ZOOM_COLOR(row, idx) snes->rom[0xC50000 + (row * 18) + idx] 
    // Note: 0xC50000 is a placeholder for the bank start. 
    // The actual table address is required for byte-perfect parity.
    // Using the logic: lda f:ZoomPalTbl + offset, x
    
    if (map_type == 0) { // beq @c523 is NOT taken (map_type == 0)
        // Overworld
        ram[0x0D25] = snes->rom[0xC50000 + (15 * 18) + x]; // ZoomPalTbl + 18*15,x
        ram[0x0D29] = snes->rom[0xC50000 + (16 * 18) + x]; // ZoomPalTbl + 18*16,x
        snes->cpu->a = 0; // lda #0
    } else if (map_type == 1) { // @c523: cmp #$01 / bne @c567 is NOT taken
        // Underground
        ram[0x0CF3] = snes->rom[0xC50000 + (7 * 18) + x];  // 18*7
        ram[0x0CF5] = snes->rom[0xC50000 + (8 * 18) + x];  // 18*8
        ram[0x0D1D] = snes->rom[0xC50000 + (9 * 18) + x];  // 18*9
        ram[0x0D1F] = snes->rom[0xC50000 + (10 * 18) + x]; // 18*10
        ram[0x0D21] = snes->rom[0xC50000 + (11 * 18) + x]; // 18*11
        ram[0x0CDF] = snes->rom[0xC50000 + (12 * 18) + x]; // 18*12
        ram[0x0CE5] = snes->rom[0xC50000 + (13 * 18) + x]; // 18*13
        ram[0x0CDD] = snes->rom[0xC50000 + (14 * 18) + x]; // 18*14
        snes->cpu->a = 0; // lda #0
    } else { // @c567: Moon
        ram[0x0CDD] = snes->rom[0xC50000 + (0 * 18) + x];  // ZoomPalTbl,x
        ram[0x0CE5] = snes->rom[0xC50000 + (1 * 18) + x];  // 18*1
        uint8_t col2 = snes->rom[0xC50000 + (2 * 18) + x]; // 18*2
        ram[0x0CF3] = col2;
        ram[0x0D13] = col2;
        ram[0x0CDF] = snes->rom[0xC50000 + (3 * 18) + x];  // 18*3
        ram[0x0D0B] = snes->rom[0xC50000 + (4 * 18) + x];  // 18*4
        ram[0x0D0D] = snes->rom[0xC50000 + (5 * 18) + x];  // 18*5
        ram[0x0D11] = snes->rom[0xC50000 + (6 * 18) + x];  // 18*6
        snes->cpu->a = 0; // lda #0
    }
    
    // shorta: mf = true (already true on entry, but explicitly set by ASM)
    snes->cpu->mf = true;
}


// ---------------------------------------------------------------------------
// Common helpers (same shape as the manual M2/M3/M4 spikes)
// ---------------------------------------------------------------------------

static uint8_t *read_file(const char *path, size_t *out_len) {
    FILE *f = fopen(path, "rb");
    if (!f) { perror(path); return NULL; }
    fseek(f, 0, SEEK_END); long sz = ftell(f); fseek(f, 0, SEEK_SET);
    uint8_t *buf = malloc(sz);
    if (fread(buf, 1, sz, f) != (size_t)sz) { free(buf); fclose(f); return NULL; }
    fclose(f); *out_len = sz; return buf;
}

static inline uint32_t stack_addr(const Cpu *cpu) {
    return cpu->e ? (0x0100u | (cpu->sp & 0xFFu)) : cpu->sp;
}

static void run_emulated_func(Snes *snes, uint32_t pc24) {
    Cpu *cpu = snes->cpu;
    uint16_t sp_save = cpu->sp;
    snes->ram[stack_addr(cpu)] = 0x12; cpu->sp--;
    snes->ram[stack_addr(cpu)] = 0x34; cpu->sp--;
    cpu->k = (uint8_t)(pc24 >> 16);
    cpu->pc = (uint16_t)(pc24 & 0xFFFF);
    long max_ops = 200000;
    while (cpu->sp != sp_save && max_ops-- > 0) {
        cpu_runOpcode(cpu);
        if (cpu->waiting || cpu->stopped) break;
    }
}

typedef struct {
    uint8_t ram[0x20000];
    uint16_t a, x, y, sp, pc, dp;
    uint8_t k, db;
    bool c, z, v, n, i, d, xf, mf, e;
    bool waiting, stopped, irqWanted, nmiWanted;
} Snap;

static void snap_take(Snap *s, Snes *snes) {
    memcpy(s->ram, snes->ram, sizeof(s->ram));
    Cpu *c = snes->cpu;
    s->a=c->a; s->x=c->x; s->y=c->y; s->sp=c->sp; s->pc=c->pc; s->dp=c->dp;
    s->k=c->k; s->db=c->db;
    s->c=c->c; s->z=c->z; s->v=c->v; s->n=c->n;
    s->i=c->i; s->d=c->d; s->xf=c->xf; s->mf=c->mf; s->e=c->e;
    s->waiting=c->waiting; s->stopped=c->stopped;
    s->irqWanted=c->irqWanted; s->nmiWanted=c->nmiWanted;
}
static void snap_restore(const Snap *s, Snes *snes) {
    memcpy(snes->ram, s->ram, sizeof(s->ram));
    Cpu *c = snes->cpu;
    c->a=s->a; c->x=s->x; c->y=s->y; c->sp=s->sp; c->pc=s->pc; c->dp=s->dp;
    c->k=s->k; c->db=s->db;
    c->c=s->c; c->z=s->z; c->v=s->v; c->n=s->n;
    c->i=s->i; c->d=s->d; c->xf=s->xf; c->mf=s->mf; c->e=s->e;
    c->waiting=s->waiting; c->stopped=s->stopped;
    c->irqWanted=s->irqWanted; c->nmiWanted=s->nmiWanted;
}

static inline uint16_t read16(const uint8_t *ram, int addr) {
    return (uint16_t)(ram[addr] | (ram[addr + 1] << 8));
}
static inline void write16(uint8_t *ram, int addr, uint16_t v) {
    ram[addr] = v & 0xFF; ram[addr + 1] = (v >> 8) & 0xFF;
}

// ---------------------------------------------------------------------------
// asm wrapper from the contract
// ---------------------------------------------------------------------------

static void run_asm(Snes *snes, uint8_t arg_a) {
    Cpu *c = snes->cpu;
    c->dp = 0;
    c->db = 0x7E;
    c->mf = true;
    c->xf = false;
    c->a = 0; c->x = 0; c->y = 0;
    c->a = arg_a;
    c->z = (arg_a == 0);
    c->n = ((arg_a & 0x80) != 0);
    run_emulated_func(snes, TARGET_ADDR_24);
}

// ---------------------------------------------------------------------------
// Host PRNG
// ---------------------------------------------------------------------------

static uint32_t host_rng_state = 0xC0FFEEu;
static uint32_t host_rng(void) {
    uint32_t x = host_rng_state;
    x ^= x << 13; x ^= x >> 17; x ^= x << 5;
    host_rng_state = x; return x;
}

// ---------------------------------------------------------------------------
// Trial driver
// ---------------------------------------------------------------------------

int main(int argc, char **argv) {
    if (argc < 2) {
        fprintf(stderr, "usage: %s <rom.sfc> [n_trials]\n", argv[0]);
        return 1;
    }
    int n_trials = (argc >= 3) ? atoi(argv[2]) : 1000;

    size_t rom_len = 0;
    uint8_t *rom = read_file(argv[1], &rom_len);
    if (!rom) return 2;

    Snes *snes = snes_init();
    if (!snes_loadRom(snes, rom, rom_len)) { fprintf(stderr, "loadRom fail\n"); return 3; }
    snes_reset(snes, true);
    for (int i = 0; i < 60; i++) snes_runFrame(snes);
    snes->cpu->i = true; snes->cpu->nmiWanted = false; snes->cpu->irqWanted = false;

    Snap baseline;
    snap_take(&baseline, snes);

    fprintf(stderr, "UpdateZoomPal asm vs C : %d trials\n", n_trials);

    int fails = 0;
    for (int trial = 0; trial < n_trials; trial++) {
        snap_restore(&baseline, snes);

        // Randomise inputs.
        snes->ram[0x1700] = (uint8_t)host_rng();
        uint8_t arg_a = (uint8_t)host_rng();

        // Pre-call snapshot for replaying C with the exact same state.
        Snap pre;
        snap_take(&pre, snes);

        // Run ASM
        run_asm(snes, arg_a);
        uint16_t out_asm = 0; (void)snes;

        // Restore and run C
        snap_restore(&pre, snes);
        UpdateZoomPal_c(snes, arg_a);
        uint16_t out_c = 0;

        bool ok = (out_asm == out_c);
        if (!ok) {
            printf("trial %4d : asm=%u c=%u  FAIL\n", trial, out_asm, out_c);
            fails++;
        }
    }

    printf("\n=== summary === trials: %d, fails: %d\n", n_trials, fails);
    free(rom);
    return fails == 0 ? 0 : 1;
}
