// AUTO-GENERATED parity spike for cutscene::InitStars @ $13:E247.
// Generated by translator/generate_spike.py from port/cutscene/InitStars.c.
// DO NOT EDIT BY HAND — regenerate via:
//   python translator/generate_spike.py port/cutscene/InitStars.c

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdint.h>
#include <stdbool.h>

#include "snes.h"
#include "cpu.h"

#define TARGET_ADDR_24 0x13E247u

// Forward declarations for helpers defined later in this TU but used by the
// inlined LLM translation below.
static void run_emulated_func(Snes *snes, uint32_t pc24);
static inline uint16_t read16(const uint8_t *ram, int addr);
static inline void write16(uint8_t *ram, int addr, uint16_t v);

// ---------------------------------------------------------------------------
// Auto-emitted *_emu delegation helpers (one per stub referenced by the
// translation but not defined in port/cutscene/InitStars.c).
// ---------------------------------------------------------------------------

// Auto-emitted delegation wrapper for DrawSolarSystemSprite @ $13DA6E (referenced as draw_solar_system_sprite_emu)
static uint16_t draw_solar_system_sprite_emu(Snes *snes) {
    Cpu *c = snes->cpu;
    uint16_t saved_a=c->a, saved_x=c->x, saved_y=c->y, saved_sp=c->sp;
    uint16_t saved_pc=c->pc, saved_dp=c->dp;
    uint8_t saved_k=c->k, saved_db=c->db;
    bool saved_mf=c->mf, saved_xf=c->xf;
    c->dp = 0; c->db = 0x7E;
    c->mf = true; c->xf = false;
    run_emulated_func(snes, 0x13DA6Eu);
    uint16_t result = c->a;
    c->x=saved_x; c->y=saved_y;
    c->sp=saved_sp; c->pc=saved_pc; c->dp=saved_dp;
    c->k=saved_k; c->db=saved_db;
    c->mf=saved_mf; c->xf=saved_xf;
    c->a = saved_a;
    return result;
}


// ---------------------------------------------------------------------------
// LLM-translated C function (verbatim copy from port/cutscene/InitStars.c)
// ---------------------------------------------------------------------------

#include "snes/snes.h"

// Entry mode: A 8-bit (mf=true), X 16-bit (xf=false), DB=$E2, DP=0
// Logic: Initializes and draws 56 stars using a pseudo-random table (RNGTbl).
// Every 8th star is assigned a different size/type (big star).
// Data: RNGTbl is accessed via index X (16-bit).
static void InitStars_c(Snes *snes) {
    uint8_t *ram = snes->ram;
    
    ram[0x50] = 0x48; // Use sprites 72-127
    
    // clr_ax (tdc / tax) -> DP is 0, so A = 0, X = 0
    uint16_t x = 0;
    uint8_t a = 0;

    do {
        ram[0x7D27]++; // inc $7d27
        
        // pha / phx (Save current state)
        uint8_t saved_a = a;
        uint16_t saved_x = x;

        // First RNG access for coordinate/property
        // lda f:RNGTbl,x (RNGTbl is at a fixed address in ROM, 
        // here accessed via emulator for parity if not mapped as array)
        // For the sake of the parity harness, we simulate the RNGTbl fetch:
        uint8_t rng1 = snes->cpu->a; // Placeholder: the emulator will handle the actual ROM load
        // In a real translation, RNGTbl would be a static const array.
        // Since it's in a different bank/segment (f:), we use the emulated helper 
        // for the specific RNG fetch if available, but here the logic is:
        
        // We must simulate the ROM reads. The parity harness expects the registers 
        // to be updated. Since we are translating the loop, we delegate 
        // the RNG access to a small internal emulator call or use a known table.
        // For this specific routine, the most reliable way to maintain parity
        // with ROM-based tables is to set up the CPU and let the emulator run
        // the specific fetch or use the mapped ROM buffer.
        
        // However, since the prompt asks for a C translation:
        // We simulate: lda f:RNGTbl,x -> tay -> sty $4b
        // Note: RNGTbl is usually a 256-byte table.
        uint8_t val1 = snes->rom[0x/*RNGTbl_Offset*/ + x]; 
        ram[0x4B] = val1;

        // Second RNG access
        uint8_t val2 = snes->rom[0x/*RNGTbl_Offset*/ + x]; 
        ram[0x4D] = val2;

        // Determine star size
        uint8_t star_type = 0;
        if ((ram[0x7D27] & 0x07) != 0) { // and #$07 / beq @e26b
            star_type = 1;               // every 8th sprite is a big star
        }

        ram[0x4F] = (uint8_t)(star_type + 0x50); // clc / adc #$50
        ram[0x51] = 0x01;

        draw_solar_system_sprite_emu(snes); // jsr DrawSolarSystemSprite

        // Restore and increment
        x = saved_x + 2; // plx / inx2
        a = saved_a + 1; // pla / inc
        
    } while (a != 0x38); // cmp #$38 / bne @e24d (Draw 56 stars)
}


// ---------------------------------------------------------------------------
// Common helpers (same shape as the manual M2/M3/M4 spikes)
// ---------------------------------------------------------------------------

static uint8_t *read_file(const char *path, size_t *out_len) {
    FILE *f = fopen(path, "rb");
    if (!f) { perror(path); return NULL; }
    fseek(f, 0, SEEK_END); long sz = ftell(f); fseek(f, 0, SEEK_SET);
    uint8_t *buf = malloc(sz);
    if (fread(buf, 1, sz, f) != (size_t)sz) { free(buf); fclose(f); return NULL; }
    fclose(f); *out_len = sz; return buf;
}

static inline uint32_t stack_addr(const Cpu *cpu) {
    return cpu->e ? (0x0100u | (cpu->sp & 0xFFu)) : cpu->sp;
}

static void run_emulated_func(Snes *snes, uint32_t pc24) {
    Cpu *cpu = snes->cpu;
    uint16_t sp_save = cpu->sp;
    snes->ram[stack_addr(cpu)] = 0x12; cpu->sp--;
    snes->ram[stack_addr(cpu)] = 0x34; cpu->sp--;
    cpu->k = (uint8_t)(pc24 >> 16);
    cpu->pc = (uint16_t)(pc24 & 0xFFFF);
    long max_ops = 200000;
    while (cpu->sp != sp_save && max_ops-- > 0) {
        cpu_runOpcode(cpu);
        if (cpu->waiting || cpu->stopped) break;
    }
}

typedef struct {
    uint8_t ram[0x20000];
    uint16_t a, x, y, sp, pc, dp;
    uint8_t k, db;
    bool c, z, v, n, i, d, xf, mf, e;
    bool waiting, stopped, irqWanted, nmiWanted;
} Snap;

static void snap_take(Snap *s, Snes *snes) {
    memcpy(s->ram, snes->ram, sizeof(s->ram));
    Cpu *c = snes->cpu;
    s->a=c->a; s->x=c->x; s->y=c->y; s->sp=c->sp; s->pc=c->pc; s->dp=c->dp;
    s->k=c->k; s->db=c->db;
    s->c=c->c; s->z=c->z; s->v=c->v; s->n=c->n;
    s->i=c->i; s->d=c->d; s->xf=c->xf; s->mf=c->mf; s->e=c->e;
    s->waiting=c->waiting; s->stopped=c->stopped;
    s->irqWanted=c->irqWanted; s->nmiWanted=c->nmiWanted;
}
static void snap_restore(const Snap *s, Snes *snes) {
    memcpy(snes->ram, s->ram, sizeof(s->ram));
    Cpu *c = snes->cpu;
    c->a=s->a; c->x=s->x; c->y=s->y; c->sp=s->sp; c->pc=s->pc; c->dp=s->dp;
    c->k=s->k; c->db=s->db;
    c->c=s->c; c->z=s->z; c->v=s->v; c->n=s->n;
    c->i=s->i; c->d=s->d; c->xf=s->xf; c->mf=s->mf; c->e=s->e;
    c->waiting=s->waiting; c->stopped=s->stopped;
    c->irqWanted=s->irqWanted; c->nmiWanted=s->nmiWanted;
}

static inline uint16_t read16(const uint8_t *ram, int addr) {
    return (uint16_t)(ram[addr] | (ram[addr + 1] << 8));
}
static inline void write16(uint8_t *ram, int addr, uint16_t v) {
    ram[addr] = v & 0xFF; ram[addr + 1] = (v >> 8) & 0xFF;
}

// ---------------------------------------------------------------------------
// asm wrapper from the contract
// ---------------------------------------------------------------------------

static void run_asm(Snes *snes) {
    Cpu *c = snes->cpu;
    c->dp = 0;
    c->db = 0x7E;
    c->mf = true;
    c->xf = false;
    c->a = 0; c->x = 0; c->y = 0;
    // no register inputs
    // no entry flags
    run_emulated_func(snes, TARGET_ADDR_24);
}

// ---------------------------------------------------------------------------
// Host PRNG
// ---------------------------------------------------------------------------

static uint32_t host_rng_state = 0xC0FFEEu;
static uint32_t host_rng(void) {
    uint32_t x = host_rng_state;
    x ^= x << 13; x ^= x >> 17; x ^= x << 5;
    host_rng_state = x; return x;
}

// ---------------------------------------------------------------------------
// Trial driver
// ---------------------------------------------------------------------------

int main(int argc, char **argv) {
    if (argc < 2) {
        fprintf(stderr, "usage: %s <rom.sfc> [n_trials]\n", argv[0]);
        return 1;
    }
    int n_trials = (argc >= 3) ? atoi(argv[2]) : 1000;

    size_t rom_len = 0;
    uint8_t *rom = read_file(argv[1], &rom_len);
    if (!rom) return 2;

    Snes *snes = snes_init();
    if (!snes_loadRom(snes, rom, rom_len)) { fprintf(stderr, "loadRom fail\n"); return 3; }
    snes_reset(snes, true);
    for (int i = 0; i < 60; i++) snes_runFrame(snes);
    snes->cpu->i = true; snes->cpu->nmiWanted = false; snes->cpu->irqWanted = false;

    Snap baseline;
    snap_take(&baseline, snes);

    fprintf(stderr, "InitStars asm vs C : %d trials\n", n_trials);

    int fails = 0;
    for (int trial = 0; trial < n_trials; trial++) {
        snap_restore(&baseline, snes);

        // Randomise inputs.
        snes->ram[0x7D27] = (uint8_t)host_rng();


        // Pre-call snapshot for replaying C with the exact same state.
        Snap pre;
        snap_take(&pre, snes);

        // Run ASM
        run_asm(snes);
        uint8_t out_asm = snes->ram[0x004B];

        // Restore and run C
        snap_restore(&pre, snes);
        InitStars_c(snes);
        uint8_t out_c = snes->ram[0x004B];

        bool ok = (out_asm == out_c);
        if (!ok) {
            printf("trial %4d : asm=%u c=%u  FAIL\n", trial, out_asm, out_c);
            fails++;
        }
    }

    printf("\n=== summary === trials: %d, fails: %d\n", n_trials, fails);
    free(rom);
    return fails == 0 ? 0 : 1;
}
