// AUTO-GENERATED parity spike for battle::Mult8 @ $03:83E0.
// Generated by translator/generate_spike.py from port/battle/Mult8.c.
// DO NOT EDIT BY HAND — regenerate via:
//   python translator/generate_spike.py port/battle/Mult8.c

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdint.h>
#include <stdbool.h>

#include "snes.h"
#include "cpu.h"

#define TARGET_ADDR_24 0x0383E0u

// Forward declarations for helpers defined later in this TU but used by the
// inlined LLM translation below.
static void run_emulated_func(Snes *snes, uint32_t pc24);
static inline uint16_t read16(const uint8_t *ram, int addr);
static inline void write16(uint8_t *ram, int addr, uint16_t v);

// ---------------------------------------------------------------------------
// Auto-emitted *_emu delegation helpers (one per stub referenced by the
// translation but not defined in port/battle/Mult8.c).
// ---------------------------------------------------------------------------

// (no auto-emitted helpers)

// ---------------------------------------------------------------------------
// LLM-translated C function (verbatim copy from port/battle/Mult8.c)
// ---------------------------------------------------------------------------

// Entry mode: A 8-bit (mf=1), X 16-bit (xf=0), DB=$7E, DP=0
//
// This routine performs an 8-bit multiplication of the value in A (at entry)
// by a value stored at $DF.
// The multiplication is implemented via a shift-and-add loop (16 iterations).
//
// Logic:
//   Multiplier = A (initial)
//   Multiplicand = ram[$DF]
//   Result = ram[$E0:$E3] (32-bit result stored as 4 bytes)
static void Mult8_c(Snes *snes) {
    uint8_t *ram = snes->ram;
    
    // Initial state
    ram[0xE0] = 0; 
    ram[0xE2] = 0;
    ram[0xE3] = 0;
    ram[0x394D] = 0;

    // The routine reads the initial A (8-bit) and stores it effectively in ram[$E1]
    // Since the asm does `ror $e1` without an explicit load, it implies the 
    // accumulator was shifted/stored there or the loop relies on the value 
    // existing at $E1. Based on the logic of 8-bit mults in FF4:
    // The value being shifted (the multiplier) is the input A.
    uint8_t multiplier = (uint8_t)snes->cpu->a;
    uint8_t multiplicand = ram[0xDF];
    
    uint32_t result = 0;
    uint8_t carry = 0; // CPU Carry flag

    for (int i = 0; i < 16; i++) {
        // ror $e1
        // Shift the multiplier right; the bit goes into Carry
        uint8_t bit = (multiplier >> 0) & 1;
        multiplier >>= 1;
        carry = bit;

        if (carry) { // bcc @83fb (not taken if carry=1)
            // clc / lda $df / adc $394d / sta $394d
            // Add multiplicand to the temporary accumulator $394d
            uint8_t tmp = ram[0x394D];
            tmp = (uint8_t)(multiplicand + tmp); // Pitfall 7: truncate to 8-bit
            ram[0x394D] = tmp;
            
            // Note: The original asm 'adc' also sets the carry flag for the 
            // subsequent 'ror $394d'.
            snes->cpu->c = (uint16_t)multiplicand + tmp > 0xFF;
        } else {
            snes->cpu->c = false;
        }

        // ror $394d / ror $e3
        // Shift the 16-bit result (ram[394D] and ram[E3]) right, pulling from Carry
        uint8_t low = ram[0x394D];
        uint8_t high = ram[0xE3];
        
        uint8_t low_bit = (low >> 0) & 1;
        low = (uint8_t)((low >> 1) | (carry << 7));
        carry = low_bit;
        
        uint8_t high_bit = (high >> 0) & 1;
        high = (uint8_t)((high >> 1) | (carry << 7));
        carry = high_bit;
        
        ram[0x394D] = low;
        ram[0xE3] = high;
    }

    // The result is actually shifted back into the destination bytes
    // Based on the loop, ram[E3] holds the high byte and ram[394D] the low.
    // However, looking at the stz $e0/$e2, this specific routine 
    // is a bit-bang multiplication where the final result is shifted 
    // into the memory range $E0-$E3.
    
    // The loop effectively computes (A * ram[DF]) and shifts it right 16 times.
    // The logic result is the lower 16 bits of the product.
    uint16_t final_res = (uint16_t)(ram[0x394D] | (ram[0xE3] << 8));
    write16(ram, 0xE0, final_res);

    // shorta0: A = 0, mode = 8-bit
    snes->cpu->a = 0;
    snes->cpu->mf = true;
}


// ---------------------------------------------------------------------------
// Common helpers (same shape as the manual M2/M3/M4 spikes)
// ---------------------------------------------------------------------------

static uint8_t *read_file(const char *path, size_t *out_len) {
    FILE *f = fopen(path, "rb");
    if (!f) { perror(path); return NULL; }
    fseek(f, 0, SEEK_END); long sz = ftell(f); fseek(f, 0, SEEK_SET);
    uint8_t *buf = malloc(sz);
    if (fread(buf, 1, sz, f) != (size_t)sz) { free(buf); fclose(f); return NULL; }
    fclose(f); *out_len = sz; return buf;
}

static inline uint32_t stack_addr(const Cpu *cpu) {
    return cpu->e ? (0x0100u | (cpu->sp & 0xFFu)) : cpu->sp;
}

static void run_emulated_func(Snes *snes, uint32_t pc24) {
    Cpu *cpu = snes->cpu;
    uint16_t sp_save = cpu->sp;
    snes->ram[stack_addr(cpu)] = 0x12; cpu->sp--;
    snes->ram[stack_addr(cpu)] = 0x34; cpu->sp--;
    cpu->k = (uint8_t)(pc24 >> 16);
    cpu->pc = (uint16_t)(pc24 & 0xFFFF);
    long max_ops = 200000;
    while (cpu->sp != sp_save && max_ops-- > 0) {
        cpu_runOpcode(cpu);
        if (cpu->waiting || cpu->stopped) break;
    }
}

typedef struct {
    uint8_t ram[0x20000];
    uint16_t a, x, y, sp, pc, dp;
    uint8_t k, db;
    bool c, z, v, n, i, d, xf, mf, e;
    bool waiting, stopped, irqWanted, nmiWanted;
} Snap;

static void snap_take(Snap *s, Snes *snes) {
    memcpy(s->ram, snes->ram, sizeof(s->ram));
    Cpu *c = snes->cpu;
    s->a=c->a; s->x=c->x; s->y=c->y; s->sp=c->sp; s->pc=c->pc; s->dp=c->dp;
    s->k=c->k; s->db=c->db;
    s->c=c->c; s->z=c->z; s->v=c->v; s->n=c->n;
    s->i=c->i; s->d=c->d; s->xf=c->xf; s->mf=c->mf; s->e=c->e;
    s->waiting=c->waiting; s->stopped=c->stopped;
    s->irqWanted=c->irqWanted; s->nmiWanted=c->nmiWanted;
}
static void snap_restore(const Snap *s, Snes *snes) {
    memcpy(snes->ram, s->ram, sizeof(s->ram));
    Cpu *c = snes->cpu;
    c->a=s->a; c->x=s->x; c->y=s->y; c->sp=s->sp; c->pc=s->pc; c->dp=s->dp;
    c->k=s->k; c->db=s->db;
    c->c=s->c; c->z=s->z; c->v=s->v; c->n=s->n;
    c->i=s->i; c->d=s->d; c->xf=s->xf; c->mf=s->mf; c->e=s->e;
    c->waiting=s->waiting; c->stopped=s->stopped;
    c->irqWanted=s->irqWanted; c->nmiWanted=s->nmiWanted;
}

static inline uint16_t read16(const uint8_t *ram, int addr) {
    return (uint16_t)(ram[addr] | (ram[addr + 1] << 8));
}
static inline void write16(uint8_t *ram, int addr, uint16_t v) {
    ram[addr] = v & 0xFF; ram[addr + 1] = (v >> 8) & 0xFF;
}

// ---------------------------------------------------------------------------
// asm wrapper from the contract
// ---------------------------------------------------------------------------

static void run_asm(Snes *snes, uint8_t arg_a) {
    Cpu *c = snes->cpu;
    c->dp = 0;
    c->db = 0x7E;
    c->mf = true;
    c->xf = false;
    c->a = 0; c->x = 0; c->y = 0;
    c->a = arg_a;
    c->z = (arg_a == 0);
    c->n = ((arg_a & 0x80) != 0);
    run_emulated_func(snes, TARGET_ADDR_24);
}

// ---------------------------------------------------------------------------
// Host PRNG
// ---------------------------------------------------------------------------

static uint32_t host_rng_state = 0xC0FFEEu;
static uint32_t host_rng(void) {
    uint32_t x = host_rng_state;
    x ^= x << 13; x ^= x >> 17; x ^= x << 5;
    host_rng_state = x; return x;
}

// ---------------------------------------------------------------------------
// Trial driver
// ---------------------------------------------------------------------------

int main(int argc, char **argv) {
    if (argc < 2) {
        fprintf(stderr, "usage: %s <rom.sfc> [n_trials]\n", argv[0]);
        return 1;
    }
    int n_trials = (argc >= 3) ? atoi(argv[2]) : 1000;

    size_t rom_len = 0;
    uint8_t *rom = read_file(argv[1], &rom_len);
    if (!rom) return 2;

    Snes *snes = snes_init();
    if (!snes_loadRom(snes, rom, rom_len)) { fprintf(stderr, "loadRom fail\n"); return 3; }
    snes_reset(snes, true);
    for (int i = 0; i < 60; i++) snes_runFrame(snes);
    snes->cpu->i = true; snes->cpu->nmiWanted = false; snes->cpu->irqWanted = false;

    Snap baseline;
    snap_take(&baseline, snes);

    fprintf(stderr, "Mult8 asm vs C : %d trials\n", n_trials);

    int fails = 0;
    for (int trial = 0; trial < n_trials; trial++) {
        snap_restore(&baseline, snes);

        // Randomise inputs.
        snes->ram[0x00DF] = (uint8_t)host_rng();
        uint8_t arg_a = (uint8_t)host_rng();

        // Pre-call snapshot for replaying C with the exact same state.
        Snap pre;
        snap_take(&pre, snes);

        // Run ASM
        run_asm(snes, arg_a);
        uint16_t out_asm = read16(snes->ram, 0x00E0);

        // Restore and run C
        snap_restore(&pre, snes);
        Mult8_c(snes, arg_a);
        uint16_t out_c = read16(snes->ram, 0x00E0);

        bool ok = (out_asm == out_c);
        if (!ok) {
            printf("trial %4d : asm=%u c=%u  FAIL\n", trial, out_asm, out_c);
            fails++;
        }
    }

    printf("\n=== summary === trials: %d, fails: %d\n", n_trials, fails);
    free(rom);
    return fails == 0 ? 0 : 1;
}
