// AUTO-GENERATED parity spike for field::DrawNpcsEntry @ $00:BB6A.
// Generated by translator/generate_spike.py from port/field/DrawNpcsEntry.c.
// DO NOT EDIT BY HAND — regenerate via:
//   python translator/generate_spike.py port/field/DrawNpcsEntry.c

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdint.h>
#include <stdbool.h>

#include "snes.h"
#include "cpu.h"

#define TARGET_ADDR_24 0x00BB6Au

// Forward declarations for helpers defined later in this TU but used by the
// inlined LLM translation below.
static void run_emulated_func(Snes *snes, uint32_t pc24);
// External linkage (not "static inline"): a SPIKE_EXTRA_SRC file (e.g. an
// already-dispatched sibling ff4-gnw/*.c called directly, not via an
// auto-emitted _emu wrapper) compiles as its own translation unit and needs
// a real symbol to link against -- ff4-gnw's own read16/write16 (in
// ff4_helpers.c) are implicitly declared (int) by such callers, same as on
// the device. Only one spike .c ever defines these per binary, so external
// linkage can't collide.
uint16_t read16(const uint8_t *ram, int addr);
void write16(uint8_t *ram, int addr, uint16_t v);

// ---------------------------------------------------------------------------
// Auto-emitted *_emu delegation helpers (one per stub referenced by the
// translation but not defined in port/field/DrawNpcsEntry.c).
// ---------------------------------------------------------------------------

// (no auto-emitted helpers)

// ---------------------------------------------------------------------------
// LLM-translated C function (verbatim copy from port/field/DrawNpcsEntry.c)
// ---------------------------------------------------------------------------

#include "snes/snes.h"

uint8_t snes_read(Snes *snes, uint32_t adr);          /* harness/LakeSnes: read any bank (ROM tables) */
void CalcObjScreenPos_c(Snes *snes);  /* $00:BDB2 sibling, ff4-gnw/field/CalcObjScreenPos.c (L2) */

/* $00:BB6A — draw all field NPCs. For each of the $08FE active objects it
 * selects an animation frame (direction/walk-cycle/scripted logic), converts
 * the object's map coordinates + a per-tile OAM template ($14:F846) into a
 * screen position via CalcObjScreenPos ($00:BDB2), and emits four sub-sprites
 * into the two interleaved OAM shadow blocks at $0400 (cursor $40) and $0480.
 * A trailing block (gated by $128A bit6) redraws the 16 party/formation
 * sprites into the $0300 OAM block from the $14:FC76/86/96/A6/B6 tables.
 * Measured at ~55% of ALL remaining interpreted opcodes on 009-first-free-roam
 * under a walking workload — the #1 interpreted target.
 *
 * ROM-bytes-are-truth: the reference disassembly annotates this routine at
 * $00:BB68, two bytes early. The bytes there ($BB68/$BB69 = 03 00) are the
 * tail of the preceding routine; the real `LDA $08FE` (AD FE 08) is at $BB6A.
 * All six call sites hold `20 6A BB` (JSR $BB6A) — `20 68 BB` occurs zero times
 * in the whole ROM. SEVENTH off-by-2 of this class (D00F533/F535, D00BDB2,
 * D00C357, D009FC2, D009F6E, D009179). The entire region is uniformly shifted
 * +2, so every internal JMP/JSR target and every data-table base is +2 vs the
 * listing: the callee at the listed "$BDB0" is really $BDB2 (CalcObjScreenPos,
 * bytes `20 B2 BD` at $BC8C), and the tables listed at $BDF6/$BDFA/$BDFE/$BE06
 * are really $BDF8/$BDFC/$BE00/$BE08 (dumped from ROM below). The bank-$14 long
 * tables ($14:F846, $14:FCC6, $14:FC76/86/96/A6/B6) live outside the shifted
 * region and match the listing exactly.
 *
 * Entry: DP = caller's D = $0600 (field engine); every `$nn` operand is
 * (dp + nn). m=1 (8-bit A) throughout; x=0 (16-bit X/Y). The accumulator high
 * byte B is 0 at entry and no 16-bit A op runs before any TAX/TAY, so those
 * transfers zero-extend the 8-bit value. Absolute operands ($08FE/$09xx,X/
 * $0300-$0583,Y/$128A) use DB=$00 → low-WRAM mirror. The two callees are
 * CalcObjScreenPos ($BDB2, native sibling) and "next sprite" ($88E2, trivial:
 * X+=4/Y+=4, inlined below). */
void DrawNpcs_c(Snes *snes) {
    uint8_t *ram = snes->ram;
    const uint16_t dp = snes->cpu->dp;
#define DP(n) ram[(uint16_t)(dp + (n))]

    /* Local bank-$00 ROM tables (real +2-shifted addresses, dumped from ROM). */
    static const uint8_t tbl_BDF8[4] = { 0x04, 0x03, 0x02, 0x01 };  /* walk-cycle shift by dir>>6 */
    static const uint8_t tbl_BDFC[4] = { 0x00, 0x00, 0x10, 0x30 };  /* frame mask by dir&3 */
    static const uint8_t tbl_BE00[8] = { 0x03, 0x00, 0x01, 0x02, 0x03, 0x00, 0x01, 0x02 };
    static const uint8_t tbl_BE08[8] = { 0x02, 0x02, 0x03, 0x00, 0x01, 0x02, 0x02, 0x02 };

    uint8_t a;
    uint16_t x, y;

    if (ram[0x08FE] == 0) return;                       // $BB6A LDA $08FE; BNE; RTS
    DP(0xAF) = 0; DP(0xB0) = 0;                          // LDX #$0000; STX $AF
    DP(0x40) = 0; DP(0x41) = 0;                          // STX $40  (OAM cursor)
    DP(0xAE) = 0;                                        // STZ $AE  (object counter)
    DP(0x43) = 0x20; DP(0x44) = 0x00;                    // LDX #$0020; STX $43 (tile-base accumulator)

loop_object:                                            // $BB7E
    x = (uint16_t)(DP(0xAF) | (DP(0xB0) << 8));          // LDX $AF (object index)
    a = ram[(uint16_t)(0x090B + x)];                    // LDA $090B,X (active?)
    if (a == 0) goto next_group;                         // BNE $BB88; else JMP $BD18

    a = (uint8_t)(ram[(uint16_t)(0x0901 + x)] & 0x03);   // LDA $0901,X; AND #$03
    if (a == 0) goto still;                              // BEQ $BBD9
    y = a;                                               // TAY (dir&3, 1..3)
    a = (uint8_t)(ram[(uint16_t)(0x0901 + x)] & 0x20);   // LDA $0901,X; AND #$20
    if (a != 0) goto animated;                           // BNE $BB9F
    /* moving, not animated ($BB97) */
    DP(0x3D) = 0x00; DP(0x3E) = 0x01;                    // LDY #$0100; STY $3D
    goto have_frame;                                     // JMP $BC4F

animated:                                               // $BB9F
    if (y != 0x0001) goto anim_multi;                    // CPY #$0001; BNE $BBB3
    a = (uint8_t)(DP(0x7A) & 0x10);                      // LDA $7A; AND #$10
    a = (uint8_t)(a << 1); a = (uint8_t)(a << 1);        // ASL; ASL
    DP(0x3D) = a;                                        // STA $3D
    DP(0x3E) = 0x01;                                     // LDA #$01; STA $3E
    goto have_frame;                                     // JMP $BC4F

anim_multi:                                             // $BBB3
    a = (uint8_t)(ram[(uint16_t)(0x0901 + x)] >> 6);     // LDA $0901,X; LSR x6
    x = a;                                               // TAX (0..3)
    a = tbl_BDF8[x];                                     // LDA $BDF8,X
    x = a;                                               // TAX (shift count 4/3/2/1)
    a = DP(0x7A);                                        // LDA $7A
    do {                                                 // $BBC3: LSR; DEX; BNE
        a = (uint8_t)(a >> 1);
        x--;
    } while (x != 0);
    x = (uint16_t)(DP(0xAF) | (DP(0xB0) << 8));          // LDX $AF (restore object index)
    a = (uint8_t)(a & 0x0C);                             // AND #$0C
    a = (uint8_t)(a << 1); a = (uint8_t)(a << 1);        // ASL; ASL
    a = (uint8_t)(a & tbl_BDFC[y]);                      // AND $BDFC,Y (y = dir&3)
    DP(0x3D) = a;                                        // STA $3D
    DP(0x3E) = 0x01;                                     // LDA #$01; STA $3E
    goto have_frame;                                     // JMP $BC4F

still:                                                  // $BBD9
    a = (uint8_t)(ram[(uint16_t)(0x090C + x)] & 0x02);   // LDA $090C,X; AND #$02
    if (a == 0) goto still2;                             // BEQ $BBFF
    a = (uint8_t)(ram[(uint16_t)(0x08FF + x)] & 0x7F);   // LDA $08FF,X; AND #$7F
    a = (uint8_t)(a >> 4);                               // LSR x4
    y = a;                                               // TAY (0..7)
    a = (uint8_t)(ram[(uint16_t)(0x090C + x)] & 0x01);   // LDA $090C,X; AND #$01
    a = a ? tbl_BE08[y] : tbl_BE00[y];                   // BNE $BBF7: LDA $BE08,Y / else $BE00,Y
    DP(0x3D) = 0x00;                                     // STZ $3D
    goto combine;                                        // JMP $BC43 (A = table value)

still2:                                                 // $BBFF
    a = (uint8_t)(ram[(uint16_t)(0x0902 + x)] & 0x7F);   // LDA $0902,X; AND #$7F
    if (a != 0) goto s_bc12;                             // BNE $BC12
    a = (uint8_t)(ram[(uint16_t)(0x0901 + x)] & 0x20);   // LDA $0901,X; AND #$20
    if (a != 0) goto s_bc34;                             // BNE $BC32(->$BC34)
    a = 0x00;                                            // LDA #$00
    goto s_bc3c;                                         // JMP $BC3A(->$BC3C)
s_bc12:                                                 // $BC12
    a = (uint8_t)(ram[(uint16_t)(0x08FF + x)] & 0x40);   // LDA $08FF,X; AND #$40
    if (a == 0) goto s_bc1e;                             // BEQ $BC1C(->$BC1E)
    a = 0x00;                                            // LDA #$00
    goto s_bc3c;                                         // JMP $BC3A(->$BC3C)
s_bc1e:                                                 // $BC1E
    a = ram[(uint16_t)(0x0908 + x)];                    // LDA $0908,X
    if (a == 0) goto s_bc2a;                             // BEQ $BC28(->$BC2A)
    a = (uint8_t)(ram[(uint16_t)(0x08FF + x)] >> 1);     // LDA $08FF,X; LSR
    goto s_bc36;                                         // JMP $BC34(->$BC36)
s_bc2a:                                                 // $BC2A
    a = DP(0xB1);                                        // LDA $B1
    if (a != 0) goto s_bc34;                             // BNE $BC32(->$BC34)
    a = ram[(uint16_t)(0x08FF + x)];                    // LDA $08FF,X
    goto s_bc36;                                         // JMP $BC34(->$BC36)
s_bc34:                                                 // $BC34
    a = DP(0x7A);                                        // LDA $7A
s_bc36:                                                 // $BC36
    a = (uint8_t)(a & 0x10);                             // AND #$10
    a = (uint8_t)(a >> 4);                               // LSR x4
s_bc3c:                                                 // $BC3C
    DP(0x3D) = a;                                        // STA $3D
    a = (uint8_t)(ram[(uint16_t)(0x0909 + x)] & 0x7F);   // LDA $0909,X; AND #$7F
combine:                                                // $BC43
    a = (uint8_t)(a << 1);                               // ASL
    a = (uint8_t)(a + DP(0x3D));                         // CLC; ADC $3D
    a = (uint8_t)(a << 1); a = (uint8_t)(a << 1);        // ASL x4
    a = (uint8_t)(a << 1); a = (uint8_t)(a << 1);
    DP(0x3D) = a;                                        // STA $3D
    DP(0x3E) = 0x00;                                     // STZ $3E

have_frame:                                             // $BC4F
    a = (uint8_t)(ram[(uint16_t)(0x090D + x)] << 1);     // LDA $090D,X; ASL
    DP(0x07) = a;                                        // STA $07 (palette)
    DP(0x08) = 0x00;                                     // STZ $08 (jump y-offset)
    a = (uint8_t)(ram[(uint16_t)(0x090C + x)] & 0x01);   // LDA $090C,X; AND #$01
    if (a != 0) {                                        // BEQ $BC6C skips this
        a = (uint8_t)(ram[(uint16_t)(0x08FF + x)] >> 2); // LDA $08FF,X; LSR; LSR
        a = (uint8_t)(a & 0x1F);                         // AND #$1F
        x = a;                                           // TAX (0..0x1F)
        DP(0x08) = snes_read(snes, 0x14FCC6u + x);       // LDA $14FCC6,X; STA $08
    }
    x = (uint16_t)(DP(0x3D) | (DP(0x3E) << 8));          // LDX $3D (OAM template index)
    DP(0x06) = 0x04;                                     // LDA #$04; STA $06 (sub-sprite count)

subsprite_loop:                                         // $BC72
    y = (uint16_t)(DP(0xAF) | (DP(0xB0) << 8));          // LDY $AF (object index)
    a = (uint8_t)(ram[(uint16_t)(0x0903 + y)]
                  + snes_read(snes, 0x14F846u + x));      // LDA $0903,Y; CLC; ADC $14F846,X
    DP(0x0C) = a; DP(0x0D) = 0x00;                        // STA $0C; STZ $0D
    a = (uint8_t)(ram[(uint16_t)(0x0905 + y)]
                  + snes_read(snes, 0x14F847u + x));      // LDA $0905,Y; CLC; ADC $14F847,X
    DP(0x0E) = a; DP(0x0F) = 0x00;                        // STA $0E; STZ $0F
    CalcObjScreenPos_c(snes);                            // JSR $BDB2 → $18/$1A screen pos, $D7 flag
    if (DP(0xD7) != 0) goto advance;                     // LDA $D7; BNE $BD01
    y = (uint16_t)(DP(0x40) | (DP(0x41) << 8));          // LDY $40 (OAM cursor)
    if (DP(0x06) & 1) goto write_0480;                   // LDA $06; LSR; BCS $BCC8

    /* $0400 block ($BC98) */
    ram[(uint16_t)(0x0400 + y)] = DP(0x18);             // LDA $18; STA $0400,Y
    a = (uint8_t)(DP(0x1A) - 0x04);                      // LDA $1A; SEC; SBC #$04
    a = (uint8_t)(a - DP(0x08));                         // SEC; SBC $08
    ram[(uint16_t)(0x0401 + y)] = a;                    // STA $0401,Y
    {
        uint16_t sum = (uint16_t)snes_read(snes, 0x14F848u + x) + DP(0x43);  // LDA $14F848,X; CLC; ADC $43
        ram[(uint16_t)(0x0402 + y)] = (uint8_t)sum;    // STA $0402,Y
        a = (uint8_t)(DP(0x44) + (sum >> 8));            // LDA $44; ADC #$00
    }
    a = (uint8_t)(a + snes_read(snes, 0x14F849u + x));   // CLC; ADC $14F849,X
    a = (uint8_t)(a & 0xF1);                             // AND #$F1
    a = (uint8_t)(a + DP(0x07));                         // CLC; ADC $07
    ram[(uint16_t)(0x0403 + y)] = a;                    // STA $0403,Y
    goto advance;                                        // JMP $BD01

write_0480:                                             // $BCC8
    ram[(uint16_t)(0x0480 + y)] = DP(0x18);             // LDA $18; STA $0480,Y
    a = (uint8_t)(DP(0x1A) - 0x04);                      // LDA $1A; SEC; SBC #$04
    a = (uint8_t)(a - DP(0x08));                         // SEC; SBC $08
    ram[(uint16_t)(0x0481 + y)] = a;                    // STA $0481,Y
    {
        uint16_t sum = (uint16_t)snes_read(snes, 0x14F848u + x) + DP(0x43);  // LDA $14F848,X; CLC; ADC $43
        ram[(uint16_t)(0x0482 + y)] = (uint8_t)sum;    // STA $0482,Y
        a = (uint8_t)(DP(0x44) + (sum >> 8));            // LDA $44; ADC #$00
    }
    a = (uint8_t)(a + snes_read(snes, 0x14F849u + x));   // CLC; ADC $14F849,X
    a = (uint8_t)(a & 0xF1);                             // AND #$F1
    a = (uint8_t)(a + DP(0x07));                         // CLC; ADC $07
    ram[(uint16_t)(0x0483 + y)] = a;                    // STA $0483,Y
    y = (uint16_t)(DP(0xAF) | (DP(0xB0) << 8));          // LDY $AF
    a = ram[(uint16_t)(0x090A + y)];                    // LDA $090A,Y
    if (a == 0) goto advance;                            // BEQ $BD01
    y = (uint16_t)(DP(0x40) | (DP(0x41) << 8));          // LDY $40
    ram[(uint16_t)(0x0481 + y)] = 0xF8;                 // LDA #$F8; STA $0481,Y (park 2nd line)

advance:                                                // $BD01
    x = (uint16_t)(x + 4);                               // INX x4 (template index)
    if (DP(0x06) & 1) {                                 // LDA $06; LSR; BCC $BD11 skips
        DP(0x40) = (uint8_t)(DP(0x40) + 0x04);           // LDA $40; CLC; ADC #$04; STA $40
    }
    DP(0x06) = (uint8_t)(DP(0x06) - 1);                  // DEC $06
    if (DP(0x06) != 0) goto subsprite_loop;              // BNE; else BEQ $BD18

next_group:                                             // $BD18
    {
        uint16_t sum = (uint16_t)DP(0x43) + 0x20;        // LDA $43; CLC; ADC #$20
        DP(0x43) = (uint8_t)sum;                         // STA $43
        DP(0x44) = (uint8_t)(DP(0x44) + (sum >> 8));     // LDA $44; ADC #$00; STA $44
    }
    DP(0xAF) = (uint8_t)(DP(0xAF) + 0x0F);               // LDA $AF; CLC; ADC #$0F; STA $AF (8-bit; $B0 untouched)
    DP(0xAE) = (uint8_t)(DP(0xAE) + 1);                  // INC $AE
    if (DP(0xAE) != ram[0x08FE]) goto loop_object;       // LDA $AE; CMP $08FE; BNE JMP $BB7E

    /* party/formation block ($BD38) */
    if ((ram[0x128A] & 0x40) == 0) return;              // LDA $128A; AND #$40; BEQ $BDB1 (RTS)
    DP(0xAE) = 0x00;                                     // STZ $AE
party_loop:                                             // $BD41
    x = DP(0xAE);                                        // LDA $AE; TAX
    DP(0x0C) = snes_read(snes, 0x14FC96u + x);           // LDA $14FC96,X; STA $0C
    DP(0x0E) = snes_read(snes, 0x14FCA6u + x);           // LDA $14FCA6,X; STA $0E
    DP(0x07) = snes_read(snes, 0x14FC76u + x);           // LDA $14FC76,X; STA $07
    DP(0x08) = snes_read(snes, 0x14FCB6u + x);           // LDA $14FCB6,X; STA $08
    {
        uint16_t v = (uint16_t)(DP(0xAE) << 4);          // LDA $AE; STZ $3E; ASL/ROL x4
        DP(0x3D) = (uint8_t)v;                           // STA $3D
        DP(0x3E) = (uint8_t)(v >> 8);                    // (ROL $3E result)
    }
    y = (uint16_t)(DP(0x3D) | (DP(0x3E) << 8));          // LDY $3D
    x = DP(0xAE);                                        // LDA $AE; TAX
    x = snes_read(snes, 0x14FC86u + x);                  // LDA $14FC86,X; TAX (template base)
party_inner:                                            // $BD78
    a = (uint8_t)(DP(0x0C) + snes_read(snes, 0x14F846u + x)); // LDA $0C; CLC; ADC $14F846,X
    ram[(uint16_t)(0x0300 + y)] = a;                    // STA $0300,Y
    a = (uint8_t)(DP(0x0E) + snes_read(snes, 0x14F847u + x)); // LDA $0E; CLC; ADC $14F847,X
    ram[(uint16_t)(0x0301 + y)] = a;                    // STA $0301,Y
    a = (uint8_t)(DP(0x07) + snes_read(snes, 0x14F848u + x)); // LDA $07; CLC; ADC $14F848,X
    ram[(uint16_t)(0x0302 + y)] = a;                    // STA $0302,Y
    a = (uint8_t)(snes_read(snes, 0x14F849u + x) & 0xF1);    // LDA $14F849,X; AND #$F1
    a = (uint8_t)(a | DP(0x08));                         // ORA $08
    ram[(uint16_t)(0x0303 + y)] = a;                    // STA $0303,Y
    x = (uint16_t)(x + 4); y = (uint16_t)(y + 4);        // JSR $88E2 (next sprite: INX x4; INY x4)
    if (((uint8_t)y & 0x0F) != 0) goto party_inner;      // TYA; AND #$0F; BNE $BD78
    DP(0xAE) = (uint8_t)(DP(0xAE) + 1);                  // INC $AE
    if (DP(0xAE) != 0x10) goto party_loop;               // LDA $AE; CMP #$10; BNE $BD41
    /* RTS ($BDB1) */
#undef DP
}

/* Spike-only shim: the auto-generated spike calls <file-stem>_c. The real
 * function keeps its production name — the file is deliberately named
 * DrawNpcsEntry.c so generate_spike.py's ca65-bridge lookup of the stem fails
 * ("label not found") and falls back to the REVERSED_FUNCTION address below,
 * instead of resolving the asm label `DrawNPCs` to the annotated (off-by-2
 * WRONG) $00:BB68. The production file in ff4-gnw/field/ keeps the plain name. */
void DrawNpcsEntry_c(Snes *snes) { DrawNpcs_c(snes); }


// ---------------------------------------------------------------------------
// Common helpers (same shape as the manual M2/M3/M4 spikes)
// ---------------------------------------------------------------------------

static uint8_t *read_file(const char *path, size_t *out_len) {
    FILE *f = fopen(path, "rb");
    if (!f) { perror(path); return NULL; }
    fseek(f, 0, SEEK_END); long sz = ftell(f); fseek(f, 0, SEEK_SET);
    uint8_t *buf = malloc(sz);
    if (fread(buf, 1, sz, f) != (size_t)sz) { free(buf); fclose(f); return NULL; }
    fclose(f); *out_len = sz; return buf;
}

static inline uint32_t stack_addr(const Cpu *cpu) {
    return cpu->e ? (0x0100u | (cpu->sp & 0xFFu)) : cpu->sp;
}

static void run_emulated_func(Snes *snes, uint32_t pc24) {
    Cpu *cpu = snes->cpu;
    uint16_t sp_save = cpu->sp;
    snes->ram[stack_addr(cpu)] = 0x12; cpu->sp--;
    snes->ram[stack_addr(cpu)] = 0x34; cpu->sp--;
    cpu->k = (uint8_t)(pc24 >> 16);
    cpu->pc = (uint16_t)(pc24 & 0xFFFF);
    long max_ops = 200000;
    while (cpu->sp != sp_save && max_ops-- > 0) {
        cpu_runOpcode(cpu);
        if (cpu->waiting || cpu->stopped) break;
    }
}

typedef struct {
    uint8_t ram[0x20000];
    uint16_t a, x, y, sp, pc, dp;
    uint8_t k, db;
    bool c, z, v, n, i, d, xf, mf, e;
    bool waiting, stopped, irqWanted, nmiWanted;
} Snap;

static void snap_take(Snap *s, Snes *snes) {
    memcpy(s->ram, snes->ram, sizeof(s->ram));
    Cpu *c = snes->cpu;
    s->a=c->a; s->x=c->x; s->y=c->y; s->sp=c->sp; s->pc=c->pc; s->dp=c->dp;
    s->k=c->k; s->db=c->db;
    s->c=c->c; s->z=c->z; s->v=c->v; s->n=c->n;
    s->i=c->i; s->d=c->d; s->xf=c->xf; s->mf=c->mf; s->e=c->e;
    s->waiting=c->waiting; s->stopped=c->stopped;
    s->irqWanted=c->irqWanted; s->nmiWanted=c->nmiWanted;
}
static void snap_restore(const Snap *s, Snes *snes) {
    memcpy(snes->ram, s->ram, sizeof(s->ram));
    Cpu *c = snes->cpu;
    c->a=s->a; c->x=s->x; c->y=s->y; c->sp=s->sp; c->pc=s->pc; c->dp=s->dp;
    c->k=s->k; c->db=s->db;
    c->c=s->c; c->z=s->z; c->v=s->v; c->n=s->n;
    c->i=s->i; c->d=s->d; c->xf=s->xf; c->mf=s->mf; c->e=s->e;
    c->waiting=s->waiting; c->stopped=s->stopped;
    c->irqWanted=s->irqWanted; c->nmiWanted=s->nmiWanted;
}

uint16_t read16(const uint8_t *ram, int addr) {
    return (uint16_t)(ram[addr] | (ram[addr + 1] << 8));
}
void write16(uint8_t *ram, int addr, uint16_t v) {
    ram[addr] = v & 0xFF; ram[addr + 1] = (v >> 8) & 0xFF;
}

// ---------------------------------------------------------------------------
// asm wrapper from the contract
// ---------------------------------------------------------------------------

static void run_asm(Snes *snes) {
    Cpu *c = snes->cpu;
    c->dp = 0x0600;
    c->db = 0x00;
    c->mf = true;
    c->xf = false;
    c->a = 0; c->x = 0; c->y = 0;
    // no register inputs
    // no entry flags
    run_emulated_func(snes, TARGET_ADDR_24);
}

// ---------------------------------------------------------------------------
// Host PRNG
// ---------------------------------------------------------------------------

static uint32_t host_rng_state = 0xC0FFEEu;
static uint32_t host_rng(void) {
    uint32_t x = host_rng_state;
    x ^= x << 13; x ^= x >> 17; x ^= x << 5;
    host_rng_state = x; return x;
}

// ---------------------------------------------------------------------------
// Trial driver
// ---------------------------------------------------------------------------

int main(int argc, char **argv) {
    if (argc < 2) {
        fprintf(stderr, "usage: %s <rom.sfc> [n_trials]\n", argv[0]);
        return 1;
    }
    int n_trials = (argc >= 3) ? atoi(argv[2]) : 1000;

    size_t rom_len = 0;
    uint8_t *rom = read_file(argv[1], &rom_len);
    if (!rom) return 2;

    Snes *snes = snes_init();
    if (!snes_loadRom(snes, rom, rom_len)) { fprintf(stderr, "loadRom fail\n"); return 3; }
    snes_reset(snes, true);
    for (int i = 0; i < 60; i++) snes_runFrame(snes);
    snes->cpu->i = true; snes->cpu->nmiWanted = false; snes->cpu->irqWanted = false;

    Snap baseline;
    snap_take(&baseline, snes);

    fprintf(stderr, "DrawNpcsEntry asm vs C : %d trials\n", n_trials);

    int fails = 0;
    for (int trial = 0; trial < n_trials; trial++) {
        snap_restore(&baseline, snes);

        // Randomise inputs.
        snes->ram[0x08FE] = (uint8_t)host_rng();
        snes->ram[0x08FF] = (uint8_t)host_rng();
        snes->ram[0x0900] = (uint8_t)host_rng();
        snes->ram[0x0901] = (uint8_t)host_rng();
        snes->ram[0x0902] = (uint8_t)host_rng();
        snes->ram[0x0903] = (uint8_t)host_rng();
        snes->ram[0x0904] = (uint8_t)host_rng();
        snes->ram[0x0905] = (uint8_t)host_rng();
        snes->ram[0x0906] = (uint8_t)host_rng();
        snes->ram[0x0907] = (uint8_t)host_rng();
        snes->ram[0x0908] = (uint8_t)host_rng();
        snes->ram[0x0909] = (uint8_t)host_rng();
        snes->ram[0x090A] = (uint8_t)host_rng();
        snes->ram[0x090B] = (uint8_t)host_rng();
        snes->ram[0x090C] = (uint8_t)host_rng();
        snes->ram[0x090D] = (uint8_t)host_rng();
        snes->ram[0x065A] = (uint8_t)host_rng();
        snes->ram[0x065B] = (uint8_t)host_rng();
        snes->ram[0x065C] = (uint8_t)host_rng();
        snes->ram[0x065D] = (uint8_t)host_rng();
        snes->ram[0x067A] = (uint8_t)host_rng();
        snes->ram[0x06B1] = (uint8_t)host_rng();
        snes->ram[0x128A] = (uint8_t)host_rng();


        // Pre-call snapshot for replaying C with the exact same state.
        Snap pre;
        snap_take(&pre, snes);

        // Run ASM
        run_asm(snes);
        Snap asm_post; snap_take(&asm_post, snes);

        // Restore and run C
        snap_restore(&pre, snes);
        snes->cpu->dp = 0x0600;
        snes->cpu->db = 0x00;
        snes->cpu->mf = true;
        snes->cpu->xf = false;
        snes->cpu->a = 0; snes->cpu->x = 0; snes->cpu->y = 0;
        DrawNpcsEntry_c(snes);
        Snap c_post; snap_take(&c_post, snes);

        /* Mask the stack page relative to SP: the asm's push/pull and
         * run_emulated_func's return frame mutate it, the inlined C never
         * touches the stack. FF4's combat stack lives in $02xx (SP~$02E5),
         * the field stack in $01xx — so derive the page from pre.sp. */
        int sp_page = pre.sp & 0xFF00;
        int diff = -1;
        for (int a = 0; a < 0x20000; a++) {
            if (a >= sp_page && a < sp_page + 0x100) continue;  /* mask stack page */
            if (asm_post.ram[a] != c_post.ram[a]) { diff = a; break; }
        }
        bool ok = (diff < 0);
        if (!ok) {
            printf("trial %4d : first WRAM diff at $%05X  asm=%02X c=%02X  FAIL\n",
                   trial, diff, asm_post.ram[diff], c_post.ram[diff]);
            fails++;
        }
    }

    printf("\n=== summary === trials: %d, fails: %d\n", n_trials, fails);
    free(rom);
    return fails == 0 ? 0 : 1;
}
