// AUTO-GENERATED parity spike for field::_00bdb0 @ $00:BDB0.
// Generated by translator/generate_spike.py from port/field/_00bdb0.c.
// DO NOT EDIT BY HAND — regenerate via:
//   python translator/generate_spike.py port/field/_00bdb0.c

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdint.h>
#include <stdbool.h>

#include "snes.h"
#include "cpu.h"

#define TARGET_ADDR_24 0x00BDB0u

// Forward declarations for helpers defined later in this TU but used by the
// inlined LLM translation below.
static void run_emulated_func(Snes *snes, uint32_t pc24);
static inline uint16_t read16(const uint8_t *ram, int addr);
static inline void write16(uint8_t *ram, int addr, uint16_t v);

// ---------------------------------------------------------------------------
// Auto-emitted *_emu delegation helpers (one per stub referenced by the
// translation but not defined in port/field/_00bdb0.c).
// ---------------------------------------------------------------------------

// (no auto-emitted helpers)

// ---------------------------------------------------------------------------
// LLM-translated C function (verbatim copy from port/field/_00bdb0.c)
// ---------------------------------------------------------------------------

#include "snes/snes.h"

// This routine calculates a coordinate offset or range check based on 
// data indexed by the value at $af. It processes two 16-bit values from 
// a table at $0904, transforms them via shifts and arithmetic, 
// and stores the result in $18 and $1a. It also sets a flag at $d7.
static void _00bdb0_c(Snes *snes) {
    uint8_t *ram = snes->ram;
    
    // Save registers (phx, phy) - implicit in C as we don't mutate snes->cpu->x/y
    ram[0xD7] = 0; 
    uint16_t x = read16(ram, 0xAF); // ldx $af (X is 16-bit by field convention)

    // Process first value
    // longa: A becomes 16-bit. 
    // lda $0904,x: reads word at ($0904 + x)
    uint16_t val1 = read16(ram, 0x0904 + x);
    val1 &= 0x00FF;                      // and #$00ff
    val1 = (uint16_t)(val1 << 4);       // asl4 (Shift left 4)
    
    // clc / adc $0c / sec / sbc $5a
    // Note: $0c and $5a are DP-relative (DP=0)
    uint16_t term1 = (uint16_t)(val1 + ram[0x0C]); 
    uint16_t result1 = (uint16_t)(term1 - ram[0x5A]);
    result1 &= 0x03FF;                  // and #$03ff
    ram[0x18] = result1 & 0xFF;         // sta $18 (low byte)
    ram[0x19] = (result1 >> 8) & 0xFF;  // sta $18 (high byte - implied by longa)

    if (result1 >= 0x0100) {            // cmp #$0100 / bcs @bdec
        ram[0xD7]++;                     // inc $d7
        goto label_bdee;
    }

    // Process second value
    uint16_t val2 = read16(ram, 0x0906 + x);
    val2 &= 0x00FF;                      // and #$00ff
    val2 = (uint16_t)(val2 << 4);       // asl4
    
    uint16_t term2 = (uint16_t)(val2 + ram[0x0E]); 
    uint16_t result2 = (uint16_t)(term2 - ram[0x5C]);
    result2 &= 0x03FF;                  // and #$03ff
    ram[0x1A] = result2 & 0xFF;         // sta $1a
    ram[0x1B] = (result2 >> 8) & 0xFF;  // sta $1a (high byte)

    if (result2 < 0x00F0) {             // cmp #$00f0 / bcc @bdee
        goto label_bdee;
    }

    ram[0xD7]++;                        // inc $d7

label_bdee:;
    // lda #0 / shorta (A is now 8-bit 0)
    // ply / plx / rts (stack restored)
}


// ---------------------------------------------------------------------------
// Common helpers (same shape as the manual M2/M3/M4 spikes)
// ---------------------------------------------------------------------------

static uint8_t *read_file(const char *path, size_t *out_len) {
    FILE *f = fopen(path, "rb");
    if (!f) { perror(path); return NULL; }
    fseek(f, 0, SEEK_END); long sz = ftell(f); fseek(f, 0, SEEK_SET);
    uint8_t *buf = malloc(sz);
    if (fread(buf, 1, sz, f) != (size_t)sz) { free(buf); fclose(f); return NULL; }
    fclose(f); *out_len = sz; return buf;
}

static inline uint32_t stack_addr(const Cpu *cpu) {
    return cpu->e ? (0x0100u | (cpu->sp & 0xFFu)) : cpu->sp;
}

static void run_emulated_func(Snes *snes, uint32_t pc24) {
    Cpu *cpu = snes->cpu;
    uint16_t sp_save = cpu->sp;
    snes->ram[stack_addr(cpu)] = 0x12; cpu->sp--;
    snes->ram[stack_addr(cpu)] = 0x34; cpu->sp--;
    cpu->k = (uint8_t)(pc24 >> 16);
    cpu->pc = (uint16_t)(pc24 & 0xFFFF);
    long max_ops = 200000;
    while (cpu->sp != sp_save && max_ops-- > 0) {
        cpu_runOpcode(cpu);
        if (cpu->waiting || cpu->stopped) break;
    }
}

typedef struct {
    uint8_t ram[0x20000];
    uint16_t a, x, y, sp, pc, dp;
    uint8_t k, db;
    bool c, z, v, n, i, d, xf, mf, e;
    bool waiting, stopped, irqWanted, nmiWanted;
} Snap;

static void snap_take(Snap *s, Snes *snes) {
    memcpy(s->ram, snes->ram, sizeof(s->ram));
    Cpu *c = snes->cpu;
    s->a=c->a; s->x=c->x; s->y=c->y; s->sp=c->sp; s->pc=c->pc; s->dp=c->dp;
    s->k=c->k; s->db=c->db;
    s->c=c->c; s->z=c->z; s->v=c->v; s->n=c->n;
    s->i=c->i; s->d=c->d; s->xf=c->xf; s->mf=c->mf; s->e=c->e;
    s->waiting=c->waiting; s->stopped=c->stopped;
    s->irqWanted=c->irqWanted; s->nmiWanted=c->nmiWanted;
}
static void snap_restore(const Snap *s, Snes *snes) {
    memcpy(snes->ram, s->ram, sizeof(s->ram));
    Cpu *c = snes->cpu;
    c->a=s->a; c->x=s->x; c->y=s->y; c->sp=s->sp; c->pc=s->pc; c->dp=s->dp;
    c->k=s->k; c->db=s->db;
    c->c=s->c; c->z=s->z; c->v=s->v; c->n=s->n;
    c->i=s->i; c->d=s->d; c->xf=s->xf; c->mf=s->mf; c->e=s->e;
    c->waiting=s->waiting; c->stopped=s->stopped;
    c->irqWanted=s->irqWanted; c->nmiWanted=s->nmiWanted;
}

static inline uint16_t read16(const uint8_t *ram, int addr) {
    return (uint16_t)(ram[addr] | (ram[addr + 1] << 8));
}
static inline void write16(uint8_t *ram, int addr, uint16_t v) {
    ram[addr] = v & 0xFF; ram[addr + 1] = (v >> 8) & 0xFF;
}

// ---------------------------------------------------------------------------
// asm wrapper from the contract
// ---------------------------------------------------------------------------

static void run_asm(Snes *snes) {
    Cpu *c = snes->cpu;
    c->dp = 0;
    c->db = 0x7E;
    c->mf = true;
    c->xf = false;
    c->a = 0; c->x = 0; c->y = 0;
    // no register inputs
    // no entry flags
    run_emulated_func(snes, TARGET_ADDR_24);
}

// ---------------------------------------------------------------------------
// Host PRNG
// ---------------------------------------------------------------------------

static uint32_t host_rng_state = 0xC0FFEEu;
static uint32_t host_rng(void) {
    uint32_t x = host_rng_state;
    x ^= x << 13; x ^= x >> 17; x ^= x << 5;
    host_rng_state = x; return x;
}

// ---------------------------------------------------------------------------
// Trial driver
// ---------------------------------------------------------------------------

int main(int argc, char **argv) {
    if (argc < 2) {
        fprintf(stderr, "usage: %s <rom.sfc> [n_trials]\n", argv[0]);
        return 1;
    }
    int n_trials = (argc >= 3) ? atoi(argv[2]) : 1000;

    size_t rom_len = 0;
    uint8_t *rom = read_file(argv[1], &rom_len);
    if (!rom) return 2;

    Snes *snes = snes_init();
    if (!snes_loadRom(snes, rom, rom_len)) { fprintf(stderr, "loadRom fail\n"); return 3; }
    snes_reset(snes, true);
    for (int i = 0; i < 60; i++) snes_runFrame(snes);
    snes->cpu->i = true; snes->cpu->nmiWanted = false; snes->cpu->irqWanted = false;

    Snap baseline;
    snap_take(&baseline, snes);

    fprintf(stderr, "_00bdb0 asm vs C : %d trials\n", n_trials);

    int fails = 0;
    for (int trial = 0; trial < n_trials; trial++) {
        snap_restore(&baseline, snes);

        // Randomise inputs.
        write16(snes->ram, 0x00AF, (uint16_t)host_rng());
        snes->ram[0x000C] = (uint8_t)host_rng();
        snes->ram[0x005A] = (uint8_t)host_rng();
        snes->ram[0x000E] = (uint8_t)host_rng();
        snes->ram[0x005C] = (uint8_t)host_rng();
        write16(snes->ram, 0x0904, (uint16_t)host_rng());
        write16(snes->ram, 0x0906, (uint16_t)host_rng());


        // Pre-call snapshot for replaying C with the exact same state.
        Snap pre;
        snap_take(&pre, snes);

        // Run ASM
        run_asm(snes);
        uint16_t out_asm = read16(snes->ram, 0x0018);

        // Restore and run C
        snap_restore(&pre, snes);
        _00bdb0_c(snes);
        uint16_t out_c = read16(snes->ram, 0x0018);

        bool ok = (out_asm == out_c);
        if (!ok) {
            printf("trial %4d : asm=%u c=%u  FAIL\n", trial, out_asm, out_c);
            fails++;
        }
    }

    printf("\n=== summary === trials: %d, fails: %d\n", n_trials, fails);
    free(rom);
    return fails == 0 ? 0 : 1;
}
